"use client";

import {Fragment,useMemo,useState} from "react";

type Row={
  player_id:string;player_name:string;team:string;player_position:string;price:number;games_scored:number;
  season_ppg:number;form_ppg:number;opponent:string|null;next_game_at:string|null;is_home:boolean|null;
  data_confidence:string;next_round_no:number;next_round_name:string;next_round_games:number;next3_games:number;
  base_xfp_next_game:number;xfp_next_game:number;base_xfp_next_round:number;adjusted_xfp_next_round:number;
  base_xfp_next3:number;xfp_next3:number;value_next3:number;availability_status:string;availability_factor:number;
};
type FixtureRow={game_id:string;fixture_no:number;starts_at:string;opponent:string;is_home:boolean;season_ppg:number;form_ppg:number;venue_ppg:number;opponent_factor:number;fixture_xfp:number};
type SortKey="player_name"|"team"|"player_position"|"price"|"season_ppg"|"form_ppg"|"next_game_at"|"base_xfp_next_game"|"xfp_next_game"|"adjusted_xfp_next_round"|"next_round_games"|"xfp_next3"|"next3_games"|"value_next3"|"price_assessment"|"availability_factor"|"data_confidence";
type PriceAssessment={key:"under"|"fair"|"over"|"unknown";label:string;score:number;ratio:number|null};

const n=(v:unknown,d=2)=>Number(v||0).toFixed(d).replace(/\.00$/,".0");
const pos=(p:string)=>p==="C"||p==="W"||p==="F"?"F":p;
const conf=(v:string)=>v==="high"?"Høy":v==="medium"?"Middels":"Lav";
const confidenceRank=(v:string)=>v==="high"?3:v==="medium"?2:1;
const median=(values:number[])=>{const v=[...values].sort((a,b)=>a-b);if(!v.length)return 0;const m=Math.floor(v.length/2);return v.length%2?v[m]:(v[m-1]+v[m])/2};
const nextLabel=(r:Row)=>{if(!r.next_game_at||!r.opponent)return"—";const d=new Date(r.next_game_at);return`${r.is_home?"vs":"@"} ${r.opponent} · ${d.toLocaleDateString("nb-NO",{day:"2-digit",month:"2-digit"})} ${d.toLocaleTimeString("nb-NO",{hour:"2-digit",minute:"2-digit"})}`};
const fixtureDate=(value:string)=>{const d=new Date(value);return`${d.toLocaleDateString("nb-NO",{day:"2-digit",month:"2-digit",year:"2-digit"})} · ${d.toLocaleTimeString("nb-NO",{hour:"2-digit",minute:"2-digit"})}`};

export default function IntegratedXfpHorizons({rows,busy,onRefresh,token}:{rows:Row[];busy:boolean;onRefresh:()=>void;token:string|null}){
  const[q,setQ]=useState(""),[team,setTeam]=useState("ALL"),[position,setPosition]=useState("ALL"),[availability,setAvailability]=useState("ALL"),[onlyRoundGame,setOnlyRoundGame]=useState(false);
  const[sort,setSort]=useState<SortKey>("xfp_next3"),[sortDir,setSortDir]=useState<"asc"|"desc">("desc");
  const[expanded,setExpanded]=useState<string|null>(null),[fixtures,setFixtures]=useState<Record<string,FixtureRow[]>>({}),[fixtureBusy,setFixtureBusy]=useState<string|null>(null),[fixtureError,setFixtureError]=useState("");
  const teams=useMemo(()=>Array.from(new Set(rows.map(r=>r.team))).sort((a,b)=>a.localeCompare(b,"nb")),[rows]);
  const availabilityOptions=useMemo(()=>Array.from(new Set(rows.map(r=>r.availability_status||"available"))).sort(),[rows]);
  const positionMedians=useMemo(()=>{const out:Record<string,number>={F:0,D:0,G:0};for(const p of ["F","D","G"])out[p]=median(rows.filter(r=>pos(r.player_position)===p&&r.value_next3>0).map(r=>Number(r.value_next3)));return out},[rows]);
  const assess=(r:Row):PriceAssessment=>{const m=positionMedians[pos(r.player_position)]||0;if(!m||r.value_next3<=0)return{key:"unknown",label:"Uavklart",score:0,ratio:null};const ratio=r.value_next3/m;if(ratio>=1.15)return{key:"under",label:"Underpriset",score:3,ratio};if(ratio<=.85)return{key:"over",label:"Overpriset",score:1,ratio};return{key:"fair",label:"Rimelig",score:2,ratio}};
  const shown=useMemo(()=>rows.filter(r=>{const needle=q.trim().toLowerCase();return(!needle||`${r.player_name} ${r.team}`.toLowerCase().includes(needle))&&(team==="ALL"||r.team===team)&&(position==="ALL"||pos(r.player_position)===position)&&(availability==="ALL"||(r.availability_status||"available")===availability)&&(!onlyRoundGame||r.next_round_games>0)}).sort((a,b)=>{let cmp=0;if(sort==="player_name")cmp=a.player_name.localeCompare(b.player_name,"nb");else if(sort==="team")cmp=a.team.localeCompare(b.team,"nb");else if(sort==="player_position")cmp=pos(a.player_position).localeCompare(pos(b.player_position),"nb");else if(sort==="next_game_at")cmp=(a.next_game_at?new Date(a.next_game_at).getTime():Number.MAX_SAFE_INTEGER)-(b.next_game_at?new Date(b.next_game_at).getTime():Number.MAX_SAFE_INTEGER);else if(sort==="price_assessment")cmp=assess(a).score-assess(b).score;else if(sort==="data_confidence")cmp=confidenceRank(a.data_confidence)-confidenceRank(b.data_confidence);else cmp=Number(a[sort]||0)-Number(b[sort]||0);return sortDir==="asc"?cmp:-cmp}),[rows,q,team,position,availability,onlyRoundGame,sort,sortDir,positionMedians]);
  const hasFilters=!!q||team!=="ALL"||position!=="ALL"||availability!=="ALL"||onlyRoundGame;
  const reset=()=>{setQ("");setTeam("ALL");setPosition("ALL");setAvailability("ALL");setOnlyRoundGame(false)};
  const setTableSort=(key:SortKey)=>{if(sort===key){setSortDir(v=>v==="desc"?"asc":"desc");return}setSort(key);setSortDir(key==="player_name"||key==="team"||key==="player_position"||key==="next_game_at"?"asc":"desc")};
  const arrow=(key:SortKey)=>sort===key?(sortDir==="asc"?" ↑":" ↓"):" ↕";
  const round=rows[0]?.next_round_name||"Neste fantasy-runde";
  async function toggleFixtures(playerId:string){if(expanded===playerId){setExpanded(null);return}setExpanded(playerId);setFixtureError("");if(fixtures[playerId]||!token)return;setFixtureBusy(playerId);try{const res=await fetch(`/api/admin/fantasy/xfp?playerId=${encodeURIComponent(playerId)}`,{headers:{Authorization:`Bearer ${token}`},cache:"no-store"});const body=await res.json();if(!res.ok||!body.ok)throw new Error(body.error||"Kunne ikke hente kampdetaljer");setFixtures(v=>({...v,[playerId]:body.fixtures||[]}))}catch(e:any){setFixtureError(e?.message||"Kunne ikke hente kampdetaljer")}finally{setFixtureBusy(null)}}
  const cols:[SortKey,string][]=[["player_name","Spiller"],["team","Lag"],["player_position","Pos"],["price","Pris"],["season_ppg","Sesong"],["form_ppg","Form 5"],["next_game_at","Neste kamp"],["base_xfp_next_game","Base xFP kamp"],["xfp_next_game","Justert xFP kamp"],["adjusted_xfp_next_round","xFP neste runde"],["next_round_games","Kamper"],["xfp_next3","xFP 3 runder"],["next3_games","Kamper"],["value_next3","Verdi"],["price_assessment","Prisvurdering"],["availability_factor","Availability"],["data_confidence","Data"]];

  return <section className="xfp-panel">
    <div className="xfp-ranking-head"><div className="xfp-heading-tooltip" tabIndex={0}><h2>xFP-rangering <span>{shown.length} av {rows.length} spillere</span> <span className="xfp-info-mark">ⓘ</span></h2><div className="xfp-heading-tooltip-box"><strong>Base-xFP:</strong> modellprognosen før availability. <strong>Justert xFP:</strong> base-xFP × availability. <strong>Rundehorisonter:</strong> summerer alle kampene spilleren faktisk har i neste fantasy-runde og de neste tre fantasy-rundene. Rekke 1/2 og C/VC brukes først når en konkret lagoppstilling vurderes. <strong>Verdi:</strong> justert xFP tre runder per million.</div></div><p className="xfp-price-note">{round} · alle kolonner kan sorteres. Trykk på spillernavnet for kampdetaljer.</p></div><button className="xfp-primary" onClick={onRefresh} disabled={busy}>{busy?"Oppdaterer …":"↻ Oppdater"}</button></div>
    <div className="xfp-toolbar xfp-horizon-toolbar"><input value={q} onChange={e=>setQ(e.target.value)} placeholder="⌕  Søk spiller eller lag …"/><select value={team} onChange={e=>setTeam(e.target.value)}><option value="ALL">Alle lag</option>{teams.map(t=><option key={t}>{t}</option>)}</select><select value={position} onChange={e=>setPosition(e.target.value)}><option value="ALL">Alle posisjoner</option><option value="F">Forward</option><option value="D">Back</option><option value="G">Keeper</option></select><select value={availability} onChange={e=>setAvailability(e.target.value)}><option value="ALL">Alle statuser</option>{availabilityOptions.map(a=><option key={a}>{a}</option>)}</select><label className="xfp-toggle">Kun kamp i neste runde <input type="checkbox" checked={onlyRoundGame} onChange={e=>setOnlyRoundGame(e.target.checked)}/><i/></label><button className="xfp-secondary" onClick={reset} disabled={!hasFilters}>Nullstill filtre</button></div>
    <div className="xfp-table-wrap"><table className="xfp-table xfp-horizon-table"><thead><tr>{cols.map(([k,l])=><th key={`${k}-${l}`}><button onClick={()=>setTableSort(k)}>{l}{arrow(k)}</button></th>)}</tr></thead><tbody>{shown.map(r=>{const pa=assess(r),open=expanded===r.player_id,detail=fixtures[r.player_id]||[];return <Fragment key={r.player_id}><tr className={open?"xfp-main-row open":"xfp-main-row"}><td><button type="button" className="xfp-player-expand" onClick={()=>toggleFixtures(r.player_id)}><span>{open?"▾":"▸"}</span><strong>{r.player_name}</strong></button></td><td>{r.team}</td><td>{pos(r.player_position)}</td><td>{n(r.price,1)}m</td><td>{n(r.season_ppg)}</td><td>{n(r.form_ppg)}</td><td>{nextLabel(r)}</td><td>{n(r.base_xfp_next_game)}</td><td className="xfp-highlight">{n(r.xfp_next_game)}</td><td className="xfp-highlight">{n(r.adjusted_xfp_next_round)}</td><td>{r.next_round_games}</td><td className="xfp-value">{n(r.xfp_next3)}</td><td>{r.next3_games}</td><td>{n(r.value_next3,3)}</td><td><span className={`xfp-price-badge ${pa.key}`}>{pa.label}</span>{pa.ratio!==null&&<small>{Math.round((pa.ratio-1)*100)>0?"+":""}{Math.round((pa.ratio-1)*100)} % vs pos.</small>}</td><td><span className={`xfp-badge ${r.availability_status||"available"}`}>{r.availability_status||"available"}</span><small>{Math.round(Number(r.availability_factor??1)*100)} %</small></td><td><span className={`xfp-badge ${r.data_confidence}`}>{conf(r.data_confidence)}</span></td></tr>{open&&<tr className="xfp-fixture-detail-row"><td colSpan={17}>{fixtureBusy===r.player_id?<div className="xfp-fixture-loading">Henter kampdetaljer …</div>:fixtureError&&!detail.length?<div className="xfp-error">{fixtureError}</div>:detail.length?<div className="xfp-fixture-breakdown"><div className="xfp-fixture-head"><div><strong>{r.player_name} · kommende kamper</strong><span>Availability-justert kamp-for-kamp xFP</span></div></div><div className="xfp-fixture-grid">{detail.map(f=><article key={f.game_id}><div className="xfp-fixture-number">Kamp {f.fixture_no}</div><h4>{f.is_home?"Hjemme mot":"Borte mot"} {f.opponent}</h4><p>{fixtureDate(f.starts_at)}</p><dl><div><dt>H/B-PPG</dt><dd>{n(f.venue_ppg)}</dd></div><div><dt>Motstanderfaktor</dt><dd>{n(f.opponent_factor,3)}</dd></div><div><dt>Sesong</dt><dd>{n(f.season_ppg)}</dd></div><div><dt>Form 5</dt><dd>{n(f.form_ppg)}</dd></div></dl><div className="xfp-fixture-score"><span>xFP kamp</span><strong>{n(f.fixture_xfp)}</strong></div></article>)}</div></div>:<div className="xfp-fixture-loading">Ingen kommende kamper funnet.</div>}</td></tr>}</Fragment>})}{!busy&&!shown.length&&<tr><td colSpan={17} className="xfp-empty">Ingen spillere matcher filtrene.</td></tr>}</tbody></table></div>
    <p className="xfp-price-note"><strong>Viktig:</strong> Generisk spiller-xFP stopper etter availability. Rekke 1 = 100 %, rekke 2 = 50 %, kaptein ×2 og visekaptein ×1,5 legges først på i konkret lag/optimizer.</p>
  </section>;
}
