"use client";
import {useEffect,useMemo,useState} from "react";
import {getSupabaseBrowserClient} from "../../../../lib/supabase";
import "../../fantasy.css";

type H={saves:number};
type R={id:string;name:string;team:string;position:string;history:H[]};
const FASIT=["Joona Partanen","Alexander Johansson","Marcus Stensrud","Jere Huhtamaa","Mathias Schjerpen Arnkværn"];
const nk=(v:string)=>String(v||"").toLocaleLowerCase("nb-NO").normalize("NFD").replace(/[\u0300-\u036f]/g,"").replace(/[^a-z0-9]+/g," ").trim();
const toks=(v:string)=>nk(v).split(/\s+/).filter(Boolean);
function sameName(a:string,b:string){if(nk(a)===nk(b))return true;const x=toks(a),y=toks(b);return x.length>=2&&y.length>=2&&x[0]===y[0]&&x[x.length-1]===y[y.length-1]}
export default function KeeperSeason(){
 const[keepers,setKeepers]=useState<R[]>([]),[selected,setSelected]=useState(""),[season,setSeason]=useState<any>(null),[msg,setMsg]=useState("Laster …");
 useEffect(()=>{(async()=>{try{const s=getSupabaseBrowserClient();const{data}=await s!.auth.getSession();const a=data.session?.access_token;if(!a)throw new Error("Du må være logget inn som admin.");const res=await fetch("/api/fantasy-player-form?season=2025%2F26",{headers:{Authorization:`Bearer ${a}`}}),p=await res.json();if(!res.ok||!p.ok)throw new Error(p.error||"Kunne ikke hente data");const k=(p.result.rows||[]).filter((r:R)=>r.position==="G"&&FASIT.some(n=>sameName(r.name,n)));setKeepers(k);setSelected(k.find((r:R)=>sameName(r.name,"Joona Partanen"))?.id||k[0]?.id||"");setMsg(`${k.length} kontrollkeepere`)}catch(e:any){setMsg(e.message||"Feil")}})()},[]);
 const player=keepers.find(k=>k.id===selected);const matchSaves=useMemo(()=>player?player.history.reduce((a,h)=>a+Number(h.saves||0),0):0,[player]);
 useEffect(()=>{if(!player){setSeason(null);return}(async()=>{try{setSeason({loading:true});const s=getSupabaseBrowserClient();const{data}=await s!.auth.getSession();const a=data.session?.access_token;if(!a)return;const res=await fetch(`/api/fantasy-goalie-season-check?name=${encodeURIComponent(player.name)}`,{headers:{Authorization:`Bearer ${a}`}}),p=await res.json();if(!res.ok||!p.ok)throw new Error(p.error||"Feil");setSeason(p)}catch(e:any){setSeason({error:e.message||"Feil"})}})()},[player?.id]);
 const seasonSaves=season?.found?Number(season.row.saves||0):null,diff=seasonSaves==null?null:matchSaves-seasonSaves;
 return <main className="fantasy-shell"><section className="fantasy-hero"><div><p className="fantasy-kicker">STANG INN · ADMIN · FANTASY</p><h1>Keeper sesongavstemming</h1><p className="fantasy-lead">Sammenligner summerte kampredninger med HockeyLive sin sesongtotal.</p></div><a className="pill" href="/fantasy/diagnose/keeper-ab" style={{textDecoration:"none"}}>← Keeper A/B</a></section><section className="fantasy-card"><p>{msg}</p><select value={selected} onChange={e=>setSelected(e.target.value)} style={{padding:10,borderRadius:10,minWidth:300}}>{keepers.map(k=><option key={k.id} value={k.id}>{k.name} · {k.team}</option>)}</select>{player&&<div style={{marginTop:16,padding:14,border:"1px solid #cbd8e5",borderRadius:12,background:"white"}}><h2 style={{marginTop:0}}>{player.name}</h2><div style={{display:"grid",gridTemplateColumns:"repeat(auto-fit,minmax(180px,1fr))",gap:10}}><div><small>Sum kamp-SV</small><div style={{fontSize:26,fontWeight:800}}>{matchSaves}</div></div><div><small>HockeyLive sesong-SV</small><div style={{fontSize:26,fontWeight:800}}>{season?.loading?"…":seasonSaves??"—"}</div></div><div><small>Differanse SV</small><div style={{fontSize:26,fontWeight:800,color:diff===0?"#16794b":"#a23b2a"}}>{diff==null?"—":`${diff>0?"+":""}${diff}`}</div></div><div><small>FP-effekt (0,5/SV)</small><div style={{fontSize:26,fontWeight:800,color:diff===0?"#16794b":"#a23b2a"}}>{diff==null?"—":`${diff*0.5>0?"+":""}${diff*0.5}`}</div></div></div>{season?.found&&<p style={{marginBottom:0,color:"#607086"}}>HockeyLive: {season.row.gamesPlayed} kamper · {season.row.wins} seire · {season.row.shutouts} shutouts · {season.row.goalsAgainst} GA.</p>}{season?.error&&<p style={{color:"#a23b2a"}}>{season.error}</p>}</div>}</section></main>}
