-- MP-01: safe user lifecycle administration.
-- Preserves all competition/history rows; Auth blocking is handled server-side
-- and AuthGate also checks the public deactivation marker for still-valid JWTs.

alter table public.players
  add column if not exists deactivated_at timestamptz;

create table if not exists public.user_admin_audit (
  id bigint generated by default as identity primary key,
  actor_user_id uuid not null references auth.users(id) on delete restrict,
  target_user_id uuid not null references auth.users(id) on delete restrict,
  action text not null check (action in ('profile_name_changed','admin_role_changed','user_deactivated','user_reactivated')),
  details jsonb not null default '{}'::jsonb,
  created_at timestamptz not null default now()
);

create index if not exists user_admin_audit_target_created_idx
  on public.user_admin_audit(target_user_id, created_at desc);

create index if not exists user_admin_audit_actor_created_idx
  on public.user_admin_audit(actor_user_id, created_at desc);

alter table public.user_admin_audit enable row level security;

revoke all on table public.user_admin_audit from public, anon, authenticated;
revoke insert, update, delete, truncate, references, trigger on table public.players from anon, authenticated;

-- A still-valid JWT must be able to see this single marker so AuthGate can
-- fail closed immediately after an administrator disables the account.
grant select (deactivated_at) on table public.players to authenticated;

comment on column public.players.deactivated_at is
  'Administrative Stang Inn deactivation marker. Historical fantasy/tipping/league data is retained.';
comment on table public.user_admin_audit is
  'Immutable server-side audit trail for privileged user administration actions.';
