-- Stang Inn Fantasy Hockey – v0.46
-- Preseason data layer for 2026/27.
-- IMPORTANT: isolated from real Fantasy scoring. Admin analysis/xFP only.

create table if not exists fantasy_preseason_settings (
  season text primary key,
  max_weight numeric(5,4) not null default 0.25 check (max_weight between 0 and 1),
  games_for_full_weight integer not null default 5 check (games_for_full_weight > 0),
  fade_out_regular_games integer not null default 10 check (fade_out_regular_games > 0),
  updated_at timestamptz not null default now()
);

insert into fantasy_preseason_settings(season,max_weight,games_for_full_weight,fade_out_regular_games)
values ('2026/27',0.25,5,10)
on conflict (season) do nothing;

create table if not exists fantasy_preseason_league_strength (
  league_code text primary key,
  league_name text not null,
  strength_factor numeric(5,3) not null check (strength_factor between 0.25 and 2.00),
  notes text,
  updated_at timestamptz not null default now()
);

insert into fantasy_preseason_league_strength(league_code,league_name,strength_factor,notes)
values
  ('EHL','Elitehockeyligaen',1.000,'Reference level for preseason normalization.'),
  ('SHL','Swedish Hockey League',1.200,'Top Swedish tier.'),
  ('DEL','Deutsche Eishockey Liga',1.120,'Top German tier.'),
  ('CZE','Czech Extraliga',1.150,'Top Czech tier.'),
  ('SVK','Slovak Extraliga',1.040,'Top Slovak tier.'),
  ('HA','HockeyAllsvenskan',1.050,'Swedish second tier.'),
  ('DEL2','DEL2',0.950,'German second tier.'),
  ('HE','HockeyEttan',0.820,'Swedish third tier.'),
  ('NOR1','Norwegian 1st Division',0.750,'Norwegian senior level below EHL.'),
  ('NOR2','Norwegian lower senior level',0.650,'Fallback for lower Norwegian senior level.'),
  ('U20','U20 / junior',0.550,'Junior opposition.'),
  ('OTHER','Other / unknown',0.900,'Temporary fallback until level is verified.')
on conflict (league_code) do update
set league_name=excluded.league_name,
    strength_factor=excluded.strength_factor,
    notes=excluded.notes;

create table if not exists fantasy_preseason_games (
  id bigint generated by default as identity primary key,
  season text not null default '2026/27',
  game_date date not null,
  starts_at timestamptz,
  home_team text not null,
  away_team text not null,
  home_league_code text not null references fantasy_preseason_league_strength(league_code),
  away_league_code text not null references fantasy_preseason_league_strength(league_code),
  home_score integer,
  away_score integer,
  status text not null default 'scheduled' check (status in ('scheduled','finished','cancelled')),
  hockeylive_match_id bigint,
  source_url text,
  source_type text not null default 'manual' check (source_type in ('hockeylive','official','manual','web')),
  source_quality numeric(4,3) not null default 0.50 check (source_quality between 0 and 1),
  notes text,
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now(),
  unique(season,game_date,home_team,away_team)
);

create index if not exists fantasy_preseason_games_season_date_idx
  on fantasy_preseason_games(season,game_date,starts_at);
create index if not exists fantasy_preseason_games_hockeylive_idx
  on fantasy_preseason_games(hockeylive_match_id)
  where hockeylive_match_id is not null;

create table if not exists fantasy_preseason_player_stats (
  id bigint generated by default as identity primary key,
  preseason_game_id bigint not null references fantasy_preseason_games(id) on delete cascade,
  player_id uuid references fantasy_players(id) on delete set null,
  raw_player_name text not null,
  team text not null,
  position text,
  did_play boolean,
  goals integer not null default 0,
  assists integer not null default 0,
  shots integer not null default 0,
  plus_minus integer not null default 0,
  pim integer not null default 0,
  saves integer not null default 0,
  goals_against integer not null default 0,
  minutes_played numeric(7,2) not null default 0,
  win boolean,
  shutout boolean,
  powerplay_goals integer not null default 0,
  powerplay_assists integer not null default 0,
  shorthanded_goals integer not null default 0,
  shorthanded_assists integer not null default 0,
  source_type text not null default 'manual' check (source_type in ('hockeylive','official','manual','web')),
  source_quality numeric(4,3) not null default 0.50 check (source_quality between 0 and 1),
  raw jsonb not null default '{}'::jsonb,
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now(),
  unique(preseason_game_id,raw_player_name,team)
);

create index if not exists fantasy_preseason_player_stats_player_idx
  on fantasy_preseason_player_stats(player_id);
create index if not exists fantasy_preseason_player_stats_game_idx
  on fantasy_preseason_player_stats(preseason_game_id);

alter table fantasy_preseason_settings enable row level security;
alter table fantasy_preseason_league_strength enable row level security;
alter table fantasy_preseason_games enable row level security;
alter table fantasy_preseason_player_stats enable row level security;

drop policy if exists fantasy_preseason_settings_admin_read on fantasy_preseason_settings;
create policy fantasy_preseason_settings_admin_read on fantasy_preseason_settings
for select to authenticated
using (exists(select 1 from players p where p.id=auth.uid() and p.admin=true));

drop policy if exists fantasy_preseason_league_strength_admin_read on fantasy_preseason_league_strength;
create policy fantasy_preseason_league_strength_admin_read on fantasy_preseason_league_strength
for select to authenticated
using (exists(select 1 from players p where p.id=auth.uid() and p.admin=true));

drop policy if exists fantasy_preseason_games_admin_read on fantasy_preseason_games;
create policy fantasy_preseason_games_admin_read on fantasy_preseason_games
for select to authenticated
using (exists(select 1 from players p where p.id=auth.uid() and p.admin=true));

drop policy if exists fantasy_preseason_player_stats_admin_read on fantasy_preseason_player_stats;
create policy fantasy_preseason_player_stats_admin_read on fantasy_preseason_player_stats
for select to authenticated
using (exists(select 1 from players p where p.id=auth.uid() and p.admin=true));

-- 2026/27 preseason schedule supplied by admin.
-- Unknown start times are intentionally stored as NULL, never fabricated.
insert into fantasy_preseason_games
(season,game_date,starts_at,home_team,away_team,home_league_code,away_league_code,home_score,away_score,status,hockeylive_match_id,source_type,source_quality,notes)
values
('2026/27','2026-08-12','2026-08-12 19:00 Europe/Oslo','BIK Karlskoga','Storhamar','HA','EHL',1,5,'finished',null,'manual',0.80,'Result supplied by admin.'),
('2026/27','2026-08-12','2026-08-12 19:00 Europe/Oslo','Manglerud','Comet','NOR1','NOR1',4,2,'finished',8451148,'hockeylive',0.95,'HockeyLive match id supplied by admin.'),
('2026/27','2026-08-13','2026-08-13 18:30 Europe/Oslo','Vålerenga','Stjernen','EHL','EHL',2,3,'finished',8388163,'hockeylive',0.95,'OT result; HockeyLive match id supplied by admin.'),
('2026/27','2026-08-14','2026-08-14 19:00 Europe/Oslo','Gjøvik','Lillehammer','NOR1','EHL',null,null,'scheduled',8429085,'hockeylive',0.95,null),
('2026/27','2026-08-15','2026-08-15 16:00 Europe/Oslo','Frisk Asker','Sparta','EHL','EHL',null,null,'scheduled',null,'manual',0.60,null),
('2026/27','2026-08-15','2026-08-15 16:00 Europe/Oslo','Lørenskog','Comet','EHL','NOR1',null,null,'scheduled',null,'manual',0.60,null),
('2026/27','2026-08-15','2026-08-15 18:30 Europe/Oslo','Nidaros','Ringerike','EHL','EHL',null,null,'scheduled',null,'manual',0.60,null),
('2026/27','2026-08-16','2026-08-16 17:00 Europe/Oslo','Nidaros','Ringerike','EHL','EHL',null,null,'scheduled',null,'manual',0.60,null),
('2026/27','2026-08-17','2026-08-17 17:00 Europe/Oslo','Kiruna','Narvik','HE','EHL',null,null,'scheduled',null,'manual',0.60,null),
('2026/27','2026-08-18','2026-08-18 18:00 Europe/Oslo','Storhamar','Mora IK','EHL','HA',null,null,'scheduled',null,'manual',0.60,null),
('2026/27','2026-08-19','2026-08-19 18:00 Europe/Oslo','Storhamar','Mora IK','EHL','HA',null,null,'scheduled',null,'manual',0.60,null),
('2026/27','2026-08-19','2026-08-19 19:00 Europe/Oslo','Comet','Lørenskog','NOR1','EHL',null,null,'scheduled',null,'manual',0.60,null),
('2026/27','2026-08-20','2026-08-20 18:30 Europe/Oslo','Frisk Asker','Ringerike','EHL','EHL',null,null,'scheduled',null,'manual',0.60,null),
('2026/27','2026-08-20','2026-08-20 18:30 Europe/Oslo','Banska Bystrica','Stavanger Oilers','SVK','EHL',null,null,'scheduled',null,'manual',0.60,null),
('2026/27','2026-08-21','2026-08-21 14:30 Europe/Oslo','Krefeld','Vålerenga','DEL','EHL',null,null,'scheduled',null,'manual',0.60,null),
('2026/27','2026-08-21','2026-08-21 18:30 Europe/Oslo','Stjernen','Nybro','EHL','HA',null,null,'scheduled',null,'manual',0.60,null),
('2026/27','2026-08-21','2026-08-21 19:00 Europe/Oslo','Lillehammer','Gjøvik','EHL','NOR1',null,null,'scheduled',null,'manual',0.60,null),
('2026/27','2026-08-21','2026-08-21 19:00 Europe/Oslo','HK Vitkovice','Stavanger Oilers','CZE','EHL',null,null,'scheduled',null,'manual',0.60,null),
('2026/27','2026-08-21','2026-08-21 19:00 Europe/Oslo','Narvik','Boden','EHL','HE',null,null,'scheduled',null,'manual',0.60,null),
('2026/27','2026-08-21','2026-08-21 19:00 Europe/Oslo','Grüner','Vålerenga U20','NOR1','U20',null,null,'scheduled',null,'manual',0.60,null),
('2026/27','2026-08-22',null,'Sparta','Nybro','EHL','HA',null,null,'scheduled',null,'manual',0.45,'Start time not yet verified.'),
('2026/27','2026-08-22','2026-08-22 16:00 Europe/Oslo','Narvik','Boden','EHL','HE',null,null,'scheduled',null,'manual',0.60,null),
('2026/27','2026-08-22','2026-08-22 16:00 Europe/Oslo','Ski Elite','Kongsvinger','NOR1','NOR1',null,null,'scheduled',null,'manual',0.60,null),
('2026/27','2026-08-22','2026-08-22 16:00 Europe/Oslo','HKM Zvolen','Stavanger Oilers','SVK','EHL',null,null,'scheduled',null,'manual',0.60,null),
('2026/27','2026-08-22','2026-08-22 18:00 Europe/Oslo','Landshut','Vålerenga','DEL2','EHL',null,null,'scheduled',null,'manual',0.60,null),
('2026/27','2026-08-23','2026-08-23 16:00 Europe/Oslo','Lørenskog','Gjøvik','EHL','NOR1',null,null,'scheduled',null,'manual',0.60,null),
('2026/27','2026-08-23','2026-08-23 16:00 Europe/Oslo','Sparta','Stjernen','EHL','EHL',null,null,'scheduled',null,'manual',0.60,null),
('2026/27','2026-08-26','2026-08-26 18:00 Europe/Oslo','Sparta','Storhamar','EHL','EHL',null,null,'scheduled',null,'manual',0.60,null),
('2026/27','2026-08-26','2026-08-26 18:30 Europe/Oslo','Nidaros','Lillehammer','EHL','EHL',null,null,'scheduled',null,'manual',0.60,null),
('2026/27','2026-08-26','2026-08-26 19:00 Europe/Oslo','Manglerud','Ski Elite','NOR1','NOR1',null,null,'scheduled',null,'manual',0.60,null),
('2026/27','2026-08-26',null,'Grums','Comet','HE','NOR1',null,null,'scheduled',null,'manual',0.45,'Start time not yet verified.'),
('2026/27','2026-08-27','2026-08-27 18:00 Europe/Oslo','Nidaros','Lillehammer','EHL','EHL',null,null,'scheduled',null,'manual',0.60,null),
('2026/27','2026-08-27','2026-08-27 18:30 Europe/Oslo','Stjernen','Ringerike','EHL','EHL',null,null,'scheduled',null,'manual',0.60,null),
('2026/27','2026-08-28','2026-08-28 18:00 Europe/Oslo','Leksands','Frisk Asker','HA','EHL',null,null,'scheduled',null,'manual',0.60,'League classification follows supplied list; verify before weighting.'),
('2026/27','2026-08-28','2026-08-28 18:30 Europe/Oslo','Comet','Gjøvik','NOR1','NOR1',null,null,'scheduled',null,'manual',0.60,null),
('2026/27','2026-08-29','2026-08-29 15:00 Europe/Oslo','Västerås','Frisk Asker','HA','EHL',null,null,'scheduled',null,'manual',0.60,null),
('2026/27','2026-08-29','2026-08-29 15:00 Europe/Oslo','Kongsvinger','Ski Elite','NOR1','NOR1',null,null,'scheduled',null,'manual',0.60,null),
('2026/27','2026-08-29','2026-08-29 16:00 Europe/Oslo','Ringerike','Lørenskog','EHL','EHL',null,null,'scheduled',null,'manual',0.60,null),
('2026/27','2026-08-30','2026-08-30 18:00 Europe/Oslo','Grüner','Manglerud','NOR1','NOR1',null,null,'scheduled',null,'manual',0.60,null),
('2026/27','2026-09-01','2026-09-01 18:30 Europe/Oslo','Ringerike','Lillehammer','EHL','EHL',null,null,'scheduled',null,'manual',0.60,null),
('2026/27','2026-09-03','2026-09-03 18:30 Europe/Oslo','Lillehammer','Ringerike','EHL','EHL',null,null,'scheduled',null,'manual',0.60,null),
('2026/27','2026-09-03','2026-09-03 18:30 Europe/Oslo','Stjernen','Stavanger Oilers','EHL','EHL',null,null,'scheduled',null,'manual',0.60,null),
('2026/27','2026-09-03','2026-09-03 19:00 Europe/Oslo','Gjøvik','Comet','NOR1','NOR1',null,null,'scheduled',null,'manual',0.60,null),
('2026/27','2026-09-04',null,'AIK','Sparta','HA','EHL',null,null,'scheduled',null,'manual',0.45,'Start time not yet verified.'),
('2026/27','2026-09-04','2026-09-04 18:00 Europe/Oslo','Frisk Asker','Stavanger Oilers','EHL','EHL',null,null,'scheduled',null,'manual',0.60,null),
('2026/27','2026-09-04','2026-09-04 19:00 Europe/Oslo','Nidaros','Narvik','EHL','EHL',null,null,'scheduled',null,'manual',0.60,null),
('2026/27','2026-09-04','2026-09-04 19:00 Europe/Oslo','Vålerenga','Färjestad','EHL','SHL',null,null,'scheduled',null,'manual',0.60,null),
('2026/27','2026-09-05',null,'Almtuna','Sparta','HA','EHL',null,null,'scheduled',null,'manual',0.45,'Start time not yet verified.'),
('2026/27','2026-09-05','2026-09-05 15:00 Europe/Oslo','Nidaros','Narvik','EHL','EHL',null,null,'scheduled',null,'manual',0.60,null),
('2026/27','2026-09-05','2026-09-05 17:00 Europe/Oslo','Manglerud','Kongsvinger','NOR1','NOR1',null,null,'scheduled',null,'manual',0.60,null),
('2026/27','2026-09-06','2026-09-06 17:00 Europe/Oslo','Kongsvinger','Manglerud','NOR1','NOR1',null,null,'scheduled',null,'manual',0.60,null),
('2026/27','2026-09-09','2026-09-09 19:00 Europe/Oslo','Comet','Ski Elite','NOR1','NOR1',null,null,'scheduled',null,'manual',0.60,null),
('2026/27','2026-09-09','2026-09-09 19:00 Europe/Oslo','Manglerud','Grüner','NOR1','NOR1',null,null,'scheduled',null,'manual',0.60,null),
('2026/27','2026-09-10','2026-09-10 18:30 Europe/Oslo','Sparta','Stavanger Oilers','EHL','EHL',null,null,'scheduled',null,'manual',0.60,null),
('2026/27','2026-09-10','2026-09-10 19:00 Europe/Oslo','Narvik','Kiruna','EHL','HE',null,null,'scheduled',null,'manual',0.60,null),
('2026/27','2026-09-11','2026-09-11 18:30 Europe/Oslo','Ringerike','Stjernen','EHL','EHL',null,null,'scheduled',null,'manual',0.60,null),
('2026/27','2026-09-11','2026-09-11 19:00 Europe/Oslo','Gjøvik','Kongsvinger','NOR1','NOR1',null,null,'scheduled',null,'manual',0.60,null),
('2026/27','2026-09-11','2026-09-11 19:00 Europe/Oslo','Färjestad','Vålerenga','SHL','EHL',null,null,'scheduled',null,'manual',0.60,null)
on conflict (season,game_date,home_team,away_team) do update
set starts_at=coalesce(excluded.starts_at,fantasy_preseason_games.starts_at),
    home_league_code=excluded.home_league_code,
    away_league_code=excluded.away_league_code,
    home_score=coalesce(excluded.home_score,fantasy_preseason_games.home_score),
    away_score=coalesce(excluded.away_score,fantasy_preseason_games.away_score),
    status=excluded.status,
    hockeylive_match_id=coalesce(excluded.hockeylive_match_id,fantasy_preseason_games.hockeylive_match_id),
    source_type=excluded.source_type,
    source_quality=greatest(fantasy_preseason_games.source_quality,excluded.source_quality),
    notes=coalesce(excluded.notes,fantasy_preseason_games.notes),
    updated_at=now();

comment on table fantasy_preseason_games is 'Preseason/test games for admin xFP analysis only; never used by real Fantasy scoring.';
comment on table fantasy_preseason_player_stats is 'Player-level preseason statistics isolated from official Fantasy scoring data.';
comment on table fantasy_preseason_league_strength is 'Admin-tunable opponent-level normalization for preseason performance.';
comment on table fantasy_preseason_settings is 'Admin xFP preseason weighting settings; preseason fades out fully after configured regular-season games.';
