-- Stang Inn Fantasy Hockey – v0.55
-- MP-09.4 / MP-09.5: raw availability findings and safe roster-review queue.
-- Important: rows in this table are observations/candidates only. They must never
-- update fantasy_player_availability until an admin explicitly approves a match.

create table if not exists public.fantasy_availability_findings (
  id bigint generated by default as identity primary key,
  source_kind text not null check (source_kind in ('club','nitten','hockeylive','other')),
  source_label text not null,
  source_url text,
  source_published_at timestamptz,
  observed_at timestamptz not null default now(),

  raw_player_name text not null,
  raw_team text,
  raw_status text not null check (raw_status in ('available','questionable','out','long_term','returning','not_in_lineup')),
  raw_note text,

  proposed_player_id uuid references public.fantasy_players(id) on delete set null,
  match_method text check (match_method in ('external_id','exact_name_team','exact_name','normalized_name_team','manual')),
  match_confidence numeric(5,4) check (match_confidence is null or (match_confidence >= 0 and match_confidence <= 1)),
  match_reason text,

  review_status text not null default 'pending' check (review_status in ('pending','approved','rejected','needs_review')),
  reviewed_at timestamptz,
  reviewed_by uuid,
  review_note text,

  created_at timestamptz not null default now(),
  created_by uuid
);

create index if not exists fantasy_availability_findings_review_idx
  on public.fantasy_availability_findings(review_status, created_at desc);

create index if not exists fantasy_availability_findings_player_idx
  on public.fantasy_availability_findings(proposed_player_id, created_at desc);

create index if not exists fantasy_availability_findings_source_idx
  on public.fantasy_availability_findings(source_kind, source_published_at desc nulls last);

alter table public.fantasy_availability_findings enable row level security;
revoke all on public.fantasy_availability_findings from anon, authenticated;

comment on table public.fantasy_availability_findings is
'Raw availability observations and roster-match candidates. Admin approval is required before a finding may affect fantasy_player_availability.';

comment on column public.fantasy_availability_findings.match_confidence is
'0..1 confidence for the proposed roster match. Confidence is advisory only; uncertain findings remain subject to admin review.';

comment on column public.fantasy_availability_findings.review_status is
'pending/needs_review are non-authoritative. approved means an admin verified the player/status; rejected means the finding must not affect current availability.';

notify pgrst, 'reload schema';
