-- Stang Inn Fantasy Hockey – v0.56
-- MP-09.5: atomic admin approval of a reviewed availability finding.
-- One transaction updates current availability, appends history and marks the finding approved.
--
-- Replay safety: some Supabase branch histories have v0.56 registered without the
-- preceding v0.55 table migration. Keep this prerequisite idempotent so a fresh
-- branch can reconstruct the schema without changing existing production rows.

create table if not exists public.fantasy_availability_findings (
  id bigint generated by default as identity primary key,
  source_kind text not null check (source_kind in ('club','nitten','hockeylive','other')),
  source_label text not null,
  source_url text,
  source_published_at timestamptz,
  observed_at timestamptz not null default now(),
  raw_player_name text not null,
  raw_team text,
  raw_status text not null check (raw_status in ('available','questionable','out','long_term','returning','not_in_lineup')),
  raw_note text,
  proposed_player_id uuid references public.fantasy_players(id) on delete set null,
  match_method text check (match_method in ('external_id','exact_name_team','exact_name','normalized_name_team','manual')),
  match_confidence numeric(5,4) check (match_confidence is null or (match_confidence >= 0 and match_confidence <= 1)),
  match_reason text,
  review_status text not null default 'pending' check (review_status in ('pending','approved','rejected','needs_review')),
  reviewed_at timestamptz,
  reviewed_by uuid,
  review_note text,
  created_at timestamptz not null default now(),
  created_by uuid
);

create index if not exists fantasy_availability_findings_review_idx
  on public.fantasy_availability_findings(review_status, created_at desc);
create index if not exists fantasy_availability_findings_player_idx
  on public.fantasy_availability_findings(proposed_player_id, created_at desc);
create index if not exists fantasy_availability_findings_source_idx
  on public.fantasy_availability_findings(source_kind, source_published_at desc nulls last);

alter table public.fantasy_availability_findings enable row level security;
revoke all on public.fantasy_availability_findings from anon, authenticated;

create or replace function public.fantasy_approve_availability_finding(
  p_finding_id bigint,
  p_reviewer_id uuid,
  p_review_note text default null
)
returns table(player_id uuid, status text)
language plpgsql
security definer
set search_path = public
as $$
declare
  f public.fantasy_availability_findings%rowtype;
  roster_ok boolean;
begin
  select * into f
  from public.fantasy_availability_findings
  where id = p_finding_id
  for update;

  if not found then
    raise exception 'Availability-funn % finnes ikke', p_finding_id;
  end if;

  if f.review_status = 'approved' then
    raise exception 'Availability-funn % er allerede godkjent', p_finding_id;
  end if;

  if f.review_status = 'rejected' then
    raise exception 'Avvist availability-funn må åpnes for review før godkjenning';
  end if;

  if f.proposed_player_id is null then
    raise exception 'Funn % mangler verifisert spiller', p_finding_id;
  end if;

  select exists(
    select 1 from public.fantasy_players p
    where p.id = f.proposed_player_id
      and p.active = true
      and p.on_current_roster = true
  ) into roster_ok;

  if not roster_ok then
    raise exception 'Foreslått spiller finnes ikke i aktiv roster';
  end if;

  insert into public.fantasy_player_availability (
    player_id,status,note,expected_return,source_url,source_label,source_published_at,updated_at,updated_by
  ) values (
    f.proposed_player_id,f.raw_status,f.raw_note,null,f.source_url,f.source_label,f.source_published_at,now(),p_reviewer_id
  )
  on conflict (player_id) do update set
    status = excluded.status,
    note = excluded.note,
    expected_return = excluded.expected_return,
    source_url = excluded.source_url,
    source_label = excluded.source_label,
    source_published_at = excluded.source_published_at,
    updated_at = excluded.updated_at,
    updated_by = excluded.updated_by;

  insert into public.fantasy_player_availability_history (
    player_id,status,note,expected_return,source_url,source_label,source_published_at,created_by
  ) values (
    f.proposed_player_id,f.raw_status,f.raw_note,null,f.source_url,f.source_label,f.source_published_at,p_reviewer_id
  );

  update public.fantasy_availability_findings
  set review_status = 'approved',
      reviewed_at = now(),
      reviewed_by = p_reviewer_id,
      review_note = nullif(trim(coalesce(p_review_note,'')),'')
  where id = p_finding_id;

  return query select f.proposed_player_id, f.raw_status;
end;
$$;

revoke all on function public.fantasy_approve_availability_finding(bigint,uuid,text) from public;
revoke all on function public.fantasy_approve_availability_finding(bigint,uuid,text) from anon, authenticated;
grant execute on function public.fantasy_approve_availability_finding(bigint,uuid,text) to service_role;

comment on function public.fantasy_approve_availability_finding(bigint,uuid,text) is
'Atomically approves one reviewed availability finding: verifies current roster player, upserts current availability, appends audit history, and marks the finding approved. Service-role only.';

notify pgrst, 'reload schema';
