-- Stang Inn Fantasy Hockey – v0.53
-- Manual injury / availability tracking for admin use.

create table if not exists public.fantasy_player_availability (
  player_id uuid primary key references public.fantasy_players(id) on delete cascade,
  status text not null default 'available' check (status in ('available','questionable','out','long_term','returning')),
  note text,
  expected_return date,
  source_url text,
  source_label text,
  source_published_at timestamptz,
  updated_at timestamptz not null default now(),
  updated_by uuid
);

create table if not exists public.fantasy_player_availability_history (
  id bigint generated by default as identity primary key,
  player_id uuid not null references public.fantasy_players(id) on delete cascade,
  status text not null check (status in ('available','questionable','out','long_term','returning')),
  note text,
  expected_return date,
  source_url text,
  source_label text,
  source_published_at timestamptz,
  created_at timestamptz not null default now(),
  created_by uuid
);

create index if not exists fantasy_player_availability_status_idx on public.fantasy_player_availability(status);
create index if not exists fantasy_player_availability_history_player_idx on public.fantasy_player_availability_history(player_id,created_at desc);

alter table public.fantasy_player_availability enable row level security;
alter table public.fantasy_player_availability_history enable row level security;

revoke all on public.fantasy_player_availability from anon, authenticated;
revoke all on public.fantasy_player_availability_history from anon, authenticated;

comment on table public.fantasy_player_availability is 'Current documented injury/availability status. Admin analysis only until explicitly integrated into xFP/optimizer.';
comment on table public.fantasy_player_availability_history is 'Audit trail of documented availability changes and sources.';

notify pgrst, 'reload schema';
