"use client";

import {useMemo,useState} from "react";
import {getSupabaseBrowserClient} from "../../../../lib/supabase";
import {HISTORICAL_PRICES_2025} from "../../../../lib/fantasy/historical-prices-2025";
import {preEhlBacktestHistoryFor} from "../../../../lib/fantasy/import-backtest-history-2025";
import "../../fantasy.css";

const S24="2024/25",S25="2025/26";
const norm=(v:any)=>String(v??"").toLocaleLowerCase("nb-NO").normalize("NFD").replace(/[\u0300-\u036f]/g,"").replace(/ø/g,"o").replace(/æ/g,"ae").replace(/[^a-z0-9]+/g," ").trim();
const natural=(s:string)=>{const[last,...r]=String(s||"").split(",");return r.length?`${r.join(",").trim()} ${last.trim()}`:String(s||"")};
const arr=(s:string)=>norm(s).split(" ").filter(Boolean).filter(x=>x!=="jr"&&x!=="junior"),tok=(s:string)=>new Set(arr(s));
function siblingGuard(a:string,b:string){const A=arr(a),B=arr(natural(b));return A.length>=3&&B.length>=3&&A[A.length-1]===B[B.length-1]&&A[A.length-2]===B[B.length-2]&&A[0]!==B[0]}
function score(a:string,b:string){if(norm(a)===norm(natural(b)))return 1000;if(siblingGuard(a,b))return 0;const A=tok(a),B=tok(natural(b));let c=0;for(const x of A)if(B.has(x))c++;const mn=Math.min(A.size,B.size),mx=Math.max(A.size,B.size);if(c===mn&&mn>=2)return 800+c*10-mn*Math.abs(mx-mn);return c>=2?c*100-Math.abs(A.size-B.size)*10:0}
function best(name:string,src:any[]){let row:any=null,bs=0;for(const x of src){const s=score(name,x.name??x[0]);if(s>bs){bs=s;row=x}}return bs>=800?row:null}
async function auth(){const s=getSupabaseBrowserClient(),{data}=await s!.auth.getSession();if(!data.session?.access_token)throw new Error("Logg inn som admin");return data.session.access_token}

type Row={name:string;team:string;pos:string;games:number;fpPerGame:number;startPrice:number|null;value:number|null;status:string;prevLeague:string|null;prevGames:number|null;prevPpg:number|null;prevSavePct:number|null;track:string|null};
const avg=(xs:number[])=>xs.length?xs.reduce((a,b)=>a+b,0)/xs.length:0;

export default function Page(){
 const[busy,setBusy]=useState(false),[msg,setMsg]=useState("Klar for historisk backtest"),[rows,setRows]=useState<Row[]>([]);
 async function run(){setBusy(true);try{
  const t=await auth();const[a,b]=await Promise.all([fetch(`/api/fantasy-player-form?season=${encodeURIComponent(S24)}`,{headers:{Authorization:`Bearer ${t}`}}),fetch(`/api/fantasy-player-form?season=${encodeURIComponent(S25)}`,{headers:{Authorization:`Bearer ${t}`}})]);
  const p24=await a.json(),p25=await b.json();if(!a.ok||!p24.ok||!b.ok||!p25.ok)throw new Error("Kunne ikke hente historiske spillerdata");
  const old=p24.result?.rows||[],cur=p25.result?.rows||[],out:Row[]=[];
  for(const p of cur){const games=Number(p.games||0);if(games<10)continue;const prev=best(String(p.name),old);if(prev&&Number(prev.games||0)>=3)continue;const pr=best(String(p.name),HISTORICAL_PRICES_2025 as any[]);const startPrice=pr?Number(pr[2])/1e6:null,fpPerGame=Number(p.ppg||0),h=preEhlBacktestHistoryFor(String(p.name));out.push({name:String(p.name),team:String(p.team||pr?.[1]||""),pos:String(p.position||""),games,fpPerGame,startPrice,value:startPrice&&startPrice>0?fpPerGame/startPrice:null,status:h?"Beriket":startPrice?"Klar for ligaberikelse":"Mangler 19F-startpris",prevLeague:h?.league??null,prevGames:h?.games??null,prevPpg:h&&h.points!=null?h.points/h.games:null,prevSavePct:h?.savePct??null,track:h?.track??null});}
  out.sort((x,y)=>(x.status==="Beriket"?-1:0)-(y.status==="Beriket"?-1:0)||(y.value??-1)-(x.value??-1));setRows(out);setMsg(`Ferdig · ${out.length} kandidater · ${out.filter(x=>x.status==="Beriket").length} historisk beriket`);
 }catch(e:any){setMsg(`Feil: ${e.message||e}`)}finally{setBusy(false)}}
 const leagueSummary=useMemo(()=>{const m=new Map<string,Row[]>();for(const r of rows)if(r.prevLeague&&r.track==="senior-import"){const a=m.get(r.prevLeague)||[];a.push(r);m.set(r.prevLeague,a)}return[...m.entries()].map(([league,rs])=>({league,n:rs.length,pre:avg(rs.filter(r=>r.prevPpg!=null).map(r=>Number(r.prevPpg))),ehl:avg(rs.map(r=>r.fpPerGame))})).sort((a,b)=>b.n-a.n)},[rows]);
 const norway2=useMemo(()=>rows.filter(r=>r.track==="norway2-transition"&&r.prevPpg!=null),[rows]);
 const norway2Summary=useMemo(()=>({n:norway2.length,pre:avg(norway2.map(r=>Number(r.prevPpg))),ehl:avg(norway2.map(r=>r.fpPerGame)),value:avg(norway2.filter(r=>r.value!=null).map(r=>Number(r.value)))}),[norway2]);
 return <main className="fantasy-page"><section className="fantasy-card"><h1>V4.5 · Historisk import-backtest</h1><p>Backtesten kobler 2025/26-nykommere mot 19F-startpris, faktisk EHL-fantasyproduksjon og verifisert 2024/25-liga/produksjon. Seniorimporter, Norway2-opprykk og junior/talent holdes separat.</p><button onClick={run} disabled={busy}>{busy?"Analyserer…":"Kjør V4.5 kandidat-backtest"}</button><p><strong>{msg}</strong></p></section>{rows.length>0&&<><section className="fantasy-card"><h2>Norway2 → EHL · kontrollgruppe</h2><p>Dette er den viktigste kontrollgruppen for årets Ringerike-prising. Nidaros-spillere fra 2024/25 sammenlignes med faktisk fantasyproduksjon etter opprykket til EHL i 2025/26.</p><table><thead><tr><th>N</th><th>Snitt P/GP i Norway2</th><th>Snitt FP/K i EHL</th><th>Snitt FP/K per 19F-million</th></tr></thead><tbody><tr><td>{norway2Summary.n}</td><td>{norway2Summary.n?norway2Summary.pre.toFixed(2):"—"}</td><td>{norway2Summary.n?norway2Summary.ehl.toFixed(2):"—"}</td><td>{norway2Summary.value?norway2Summary.value.toFixed(3):"—"}</td></tr></tbody></table>{norway2.length>0&&<table><thead><tr><th>Spiller</th><th>Pos</th><th>24/25 P/GP</th><th>25/26 FP/K</th><th>19F start</th></tr></thead><tbody>{norway2.map(r=><tr key={`n2-${r.name}`}><td>{r.name}</td><td>{r.pos}</td><td>{Number(r.prevPpg).toFixed(2)}</td><td>{r.fpPerGame.toFixed(2)}</td><td>{r.startPrice==null?"—":`${r.startPrice.toFixed(1)}m`}</td></tr>)}</tbody></table>}</section><section className="fantasy-card"><h2>Foreløpig seniorimport-grunnlag</h2><p>Dette er fortsatt små utvalg. Ingen ny ligakoeffisient låses før flere spillere per liga er beriket.</p><table><thead><tr><th>Liga 24/25</th><th>N</th><th>P/GP før EHL</th><th>FP/K i EHL</th></tr></thead><tbody>{leagueSummary.map(x=><tr key={x.league}><td>{x.league}</td><td>{x.n}</td><td>{Number.isFinite(x.pre)?x.pre.toFixed(2):"—"}</td><td>{x.ehl.toFixed(2)}</td></tr>)}</tbody></table></section><section className="fantasy-card"><h2>Kandidater for historisk ligaberikelse</h2><table><thead><tr><th>Spiller</th><th>Lag 25/26</th><th>Pos</th><th>K</th><th>FP/K</th><th>19F start</th><th>24/25 liga</th><th>24/25 metric</th><th>Track</th><th>Status</th></tr></thead><tbody>{rows.map(r=><tr key={`${r.team}-${r.name}`}><td>{r.name}</td><td>{r.team}</td><td>{r.pos}</td><td>{r.games}</td><td>{r.fpPerGame.toFixed(2)}</td><td>{r.startPrice==null?"—":`${r.startPrice.toFixed(1)}m`}</td><td>{r.prevLeague??"—"}</td><td>{r.prevPpg!=null?`${r.prevPpg.toFixed(2)} P/GP`:r.prevSavePct!=null?`${(r.prevSavePct*100).toFixed(1)} SV%`:"—"}</td><td>{r.track??"—"}</td><td>{r.status}</td></tr>)}</tbody></table></section></>}</main>;
}
