import {NextRequest,NextResponse} from "next/server";
import {createClient} from "@supabase/supabase-js";

export const runtime="nodejs";
export const dynamic="force-dynamic";

function norm(v:any){return String(v??"").toLocaleLowerCase("nb-NO").normalize("NFD").replace(/[\u0300-\u036f]/g,"").replace(/ø/g,"o").replace(/æ/g,"ae").replace(/[^a-z0-9]+/g," ").trim()}
function canonTeam(v:any){const s=norm(v);if(s.includes("storhamar"))return"Storhamar";if(s.includes("stavanger")||s.includes("oilers"))return"Stavanger";if(s.includes("valerenga"))return"Vålerenga";if(s.includes("frisk"))return"Frisk Asker";if(s.includes("sparta"))return"Sparta";if(s.includes("narvik"))return"Narvik";if(s.includes("stjernen"))return"Stjernen";if(s.includes("lillehammer"))return"Lillehammer";if(s.includes("ringerike")||s.includes("comet"))return s.includes("ringerike")?"Ringerike":"Comet";if(s.includes("nidaros"))return"Nidaros";if(s.includes("lorenskog"))return"Lørenskog";return String(v||"").trim()}
async function requireAdmin(request:NextRequest){const url=process.env.NEXT_PUBLIC_SUPABASE_URL,key=process.env.NEXT_PUBLIC_SUPABASE_PUBLISHABLE_KEY;if(!url||!key)return null;const h=request.headers.get("authorization"),token=h?.startsWith("Bearer ")?h.slice(7):null;if(!token)return null;const c=createClient(url,key,{auth:{persistSession:false,autoRefreshToken:false},global:{headers:{Authorization:`Bearer ${token}`}}});const{data:u}=await c.auth.getUser(token);if(!u.user)return null;const{data:p}=await c.from("players").select("admin").eq("id",u.user.id).maybeSingle();return p?.admin?u.user.id:null}
function serverClient(){const url=process.env.NEXT_PUBLIC_SUPABASE_URL,key=process.env.SUPABASE_SECRET_KEY;if(!url||!key)throw new Error("Supabase server-variabler mangler");return createClient(url,key,{auth:{persistSession:false,autoRefreshToken:false}})}
export async function POST(request:NextRequest){try{if(!await requireAdmin(request))return NextResponse.json({ok:false,error:"Kun admin."},{status:403});const body=await request.json(),roster=Array.isArray(body?.rows)?body.rows:[];if(roster.length<200||roster.length>300)return NextResponse.json({ok:false,error:`Uventet rosterstørrelse: ${roster.length}.`},{status:400});const sb=serverClient();const{data:db,error}=await sb.from("fantasy_players").select("id,name,team,position,active,price");if(error)throw error;const active=(db||[]).filter((x:any)=>x.active!==false),byName=new Map<string,any[]>();for(const p of active){const k=norm(p.name),a=byName.get(k)||[];a.push(p);byName.set(k,a)}const matched:any[]=[],missing:any[]=[],ambiguous:any[]=[],used=new Set<string>();for(const r of roster){const candidates=byName.get(norm(r.name))||[];if(candidates.length===1){const p=candidates[0];used.add(p.id);matched.push({rosterName:r.name,rosterTeam:canonTeam(r.team),playerId:p.id,dbName:p.name,dbTeam:p.team,dbPosition:p.position,teamMatch:canonTeam(p.team)===canonTeam(r.team)})}else if(candidates.length===0)missing.push({name:r.name,team:canonTeam(r.team),position:r.position||null,personId:r.personId||null});else ambiguous.push({name:r.name,team:canonTeam(r.team),position:r.position||null,candidates:candidates.map((p:any)=>({id:p.id,name:p.name,team:p.team,position:p.position}))})}const stale=active.filter((p:any)=>!used.has(p.id)).map((p:any)=>({id:p.id,name:p.name,team:p.team,position:p.position,price:p.price}));const teamMismatch=matched.filter(x=>!x.teamMatch);const teamCounts=Object.entries(roster.reduce((acc:any,x:any)=>{const t=canonTeam(x.team);acc[t]=(acc[t]||0)+1;return acc},{})).sort((a:any,b:any)=>String(a[0]).localeCompare(String(b[0]),"nb-NO"));return NextResponse.json({ok:true,expected:roster.length,rosterCount:roster.length,databaseRows:(db||[]).length,activeDatabaseRows:active.length,matched:matched.length,missing:missing.length,ambiguous:ambiguous.length,teamMismatch:teamMismatch.length,stale:stale.length,ready:matched.length===roster.length&&missing.length===0&&ambiguous.length===0,details:{missing,ambiguous,teamMismatch,stale,teamCounts}})}catch(e:any){return NextResponse.json({ok:false,error:e?.message||"Preflight feilet"},{status:500})}}
