"use client";

import {useState} from "react";
import {getSupabaseBrowserClient} from "../../../../lib/supabase";
import "../../fantasy.css";

type Change={name:string;team:string;position:string;old_price:number|null;price:number;confidence:string;routing:string;source:string};
type Preview={ok:boolean;error?:string;season:string;modelVersion:string;confirmation:string;rosterCount:number;changeCount:number;drift:string[];changes:Change[]};

async function token(){const s=getSupabaseBrowserClient();const{data}=await s!.auth.getSession();if(!data.session?.access_token)throw new Error("Logg inn som admin");return data.session.access_token}

export default function Page(){
 const[preview,setPreview]=useState<Preview|null>(null),[msg,setMsg]=useState("Klar"),[busy,setBusy]=useState(false),[confirmation,setConfirmation]=useState("");
 async function load(){setBusy(true);try{const t=await token(),r=await fetch("/api/admin/fantasy/publish-price-calibration-v462",{headers:{Authorization:`Bearer ${t}`},cache:"no-store"}),j=await r.json();if(!r.ok||!j.ok)throw new Error(j.error||"Preview feilet");setPreview(j);setMsg(`Preview: ${j.rosterCount} spillere · ${j.changeCount} endringer · ${j.drift.length} drift`)}catch(e:any){setMsg(`Feil: ${e.message||e}`)}finally{setBusy(false)}}
 async function publish(){if(!preview)return;setBusy(true);try{const t=await token(),r=await fetch("/api/admin/fantasy/publish-price-calibration-v462",{method:"POST",headers:{Authorization:`Bearer ${t}`,"Content-Type":"application/json"},body:JSON.stringify({confirmation})}),j=await r.json();if(!r.ok||!j.ok)throw new Error([j.error,...(j.drift||[])].filter(Boolean).join(" · "));setMsg(`✓ ${j.modelVersion} publisert · ${j.playerCount} spillere · ${j.changed} kalibrerte · publication ${j.publicationId}`);await load()}catch(e:any){setMsg(`Publisering feilet: ${e.message||e}`)}finally{setBusy(false)}}
 return <main className="fantasy-shell"><section className="fantasy-hero"><div><p className="fantasy-kicker">MP-03.6 · FINAL CALIBRATION</p><h1>Publiser V4.6.2</h1><p className="fantasy-lead">Atomisk sluttkalibrering av hele 2026/27-poolen. 14 godkjente endringer; øvrige priser videreføres uendret. Scoring berøres ikke.</p></div><a className="pill" href="/fantasy/diagnose/price-calibration-2026">← Read-only rapport</a></section><section className="fantasy-card"><button disabled={busy} onClick={load}>{busy?"Kontrollerer …":"Last sikker preview"}</button> <b style={{marginLeft:10}}>{msg}</b>{preview&&<><div style={{display:"grid",gridTemplateColumns:"repeat(auto-fit,minmax(150px,1fr))",gap:10,margin:"18px 0"}}>{[["Roster",preview.rosterCount],["Endringer",preview.changeCount],["Drift",preview.drift.length],["Modell",preview.modelVersion]].map(([a,b]:any)=><div key={a} style={{padding:14,borderRadius:12,background:"#f5f7fa"}}><b>{a}</b><div style={{fontSize:24,fontWeight:900}}>{b}</div></div>)}</div>{preview.drift.length>0&&<div style={{padding:12,border:"1px solid #d99",borderRadius:12,background:"#fff0f0",marginBottom:12}}><b>Publisering er blokkert:</b><ul>{preview.drift.map(x=><li key={x}>{x}</li>)}</ul></div>}<div style={{overflowX:"auto"}}><table style={{width:"100%",minWidth:950,borderCollapse:"collapse",fontSize:12}}><thead><tr>{["Spiller","Lag","Pos","Før","Ny","Δ","Konfidens","Begrunnelse"].map(h=><th key={h} style={{textAlign:"left",padding:8,background:"#eef3f8"}}>{h}</th>)}</tr></thead><tbody>{preview.changes.map(x=><tr key={x.name} style={{borderBottom:"1px solid #edf0f2"}}><td style={{padding:8,fontWeight:800}}>{x.name}</td><td>{x.team}</td><td>{x.position}</td><td>{x.old_price==null?"ny":`${x.old_price.toFixed(1)}m`}</td><td style={{fontWeight:900}}>{x.price.toFixed(1)}m</td><td>{x.old_price==null?"—":`${(x.price-x.old_price)>0?"+":""}${(x.price-x.old_price).toFixed(1)}m`}</td><td>{x.confidence}</td><td>{x.source}</td></tr>)}</tbody></table></div><div style={{marginTop:18,padding:14,border:"1px solid #e1c66c",borderRadius:12,background:"#fff8e6"}}><b>Sikker publisering</b><p>RPC-en blokkerer ved roster-/prisdrift, ugyldige priser, økonomilås eller dersom et lagret lag blir dyrere enn 100m.</p><input value={confirmation} onChange={e=>setConfirmation(e.target.value)} placeholder={preview.confirmation} style={{padding:10,minWidth:240,marginRight:8}}/><button disabled={busy||preview.drift.length>0||confirmation!==preview.confirmation} onClick={publish}>Publiser atomisk</button></div></>}</section></main>;
}
