"use client";

import {useEffect,useState} from "react";
import {getSupabaseBrowserClient} from "../../../lib/supabase";
import "../fantasy.css";
import "../admin-analysis/xfp-admin.css";
import "../admin-analysis/optimizer/optimizer.css";

type RiskLabel="Lav"|"Middels"|"Høy";
type Player={id:string;name:string;team:string;pos:string;price:number;raw_base_score:number;base_score:number;score:number;line_no:number|null;is_captain:boolean;is_vice_captain:boolean;availability_status:string;data_confidence:"high"|"medium"|"low";risk_score:number;risk_label:RiskLabel};
type Change={out:Player;in:Player;price_change:number;xfp_gain:number;risk_score:number;risk_label:RiskLabel};
type Strategy={key:"balanced"|"conservative"|"offensive";label:string;description:string;changes:Change[];optimized_cost:number;optimized_score:number;xfp_gain:number;proposal_risk_score:number;proposal_risk_label:RiskLabel;modeled_upside:number};
type TransferPolicy={max_transfers:number;transfers_used:number;transfers_remaining:number;boost_active:boolean;active_booster:string|null;is_event_week:boolean;event_week_booster:string|null;permanent_transfers_allowed:boolean;reason:string;no_bank:boolean;no_points_hit:boolean};
type Result={team:{id:string;name:string}|null;current:Player[];strategies:Strategy[];current_cost:number;current_score:number;transfers_available:number;locked_player_ids:string[];transfer_policy:TransferPolicy;message?:string};

const fmt=(v:unknown,d=1)=>Number(v||0).toFixed(d);
const role=(p:Player)=>p.is_captain?" · C":p.is_vice_captain?" · VC":"";
const confidence=(v:Player["data_confidence"])=>v==="high"?"Høy":v==="low"?"Lav":"Middels";
const availability=(v:string)=>v==="questionable"?"Usikker · 60 %":v==="returning"?"Tilbake · 85 %":v==="out"?"Ute":v==="long_term"?"Langtid":v==="not_in_lineup"?"Ikke i tropp":"Tilgjengelig · 100 %";

function TeamList({players,locked,toggle}:{players:Player[];locked:Set<string>;toggle:(id:string)=>void}){
 const ordered=[...players].sort((a,b)=>(a.line_no||9)-(b.line_no||9)||a.pos.localeCompare(b.pos)||b.score-a.score);
 return <div className="optimizer-groups compact"><section className="optimizer-group"><h3>Ditt lag <span>{players.length}/12</span></h3>{ordered.map(p=><article key={p.id} className={`optimizer-player ${locked.has(p.id)?"is-locked":""}`}><b>{p.pos}</b><div><strong>{p.name}{role(p)}</strong><small>{p.team} · Rekke {p.line_no||"—"}</small></div><div><strong>{fmt(p.price)}m</strong><small>pris</small></div><div className="xfp-highlight"><strong>{fmt(p.score,2)}</strong><small>effektiv xFP</small></div><button type="button" className="optimizer-lock" aria-pressed={locked.has(p.id)} onClick={()=>toggle(p.id)}>{locked.has(p.id)?"🔒 Låst":"🔓 Lås"}</button></article>)}</section></div>;
}

function Changes({strategy,available}:{strategy:Strategy;available:number}){
 return <section className={`strategy-detail strategy-${strategy.key}`}><div className="strategy-detail-head"><div><p className="eyebrow">{strategy.label}</p><h3>{strategy.description}</h3></div><div className="strategy-metrics"><span><b className={strategy.xfp_gain>=0?"positive":"negative"}>{strategy.xfp_gain>=0?"+":""}{fmt(strategy.xfp_gain,2)}</b><small>forventet gevinst</small></span><span><b>{strategy.proposal_risk_label}</b><small>{strategy.proposal_risk_score}/100 risiko</small></span><span><b>{fmt(strategy.optimized_cost,1)}m</b><small>ny lagverdi</small></span><span><b>{fmt(strategy.modeled_upside,2)}</b><small>modellert oppside</small></span></div></div>{!strategy.changes.length?<p className="team-message">Ingen tillatte bytter forbedrer denne strategiens risiko-/oppsidejusterte vurdering akkurat nå.</p>:<div className="transfer-change-grid">{strategy.changes.map((c,i)=><article className="transfer-change-card" key={`${strategy.key}-${c.out.id}-${c.in.id}`}><div className="transfer-change-no">Bytte {i+1}/{Math.max(1,available)}</div><div className="transfer-side out"><span>UT</span><strong>{c.out.name}{role(c.out)}</strong><small>{c.out.team} · {c.out.pos} · {fmt(c.out.price)}m</small><small>Base {fmt(c.out.raw_base_score,2)} → availability {fmt(c.out.base_score,2)} → effektiv {fmt(c.out.score,2)} xFP</small></div><div className="transfer-arrow">→</div><div className="transfer-side in"><span>INN</span><strong>{c.in.name}{role(c.in)}</strong><small>{c.in.team} · {c.in.pos} · {fmt(c.in.price)}m</small><small>Base {fmt(c.in.raw_base_score,2)} → availability {fmt(c.in.base_score,2)} → effektiv {fmt(c.in.score,2)} xFP</small><small>{availability(c.in.availability_status)} · datatillit {confidence(c.in.data_confidence)} · risiko {c.in.risk_label} ({c.in.risk_score}/100)</small></div><footer><b className={c.xfp_gain>=0?"positive":"negative"}>{c.xfp_gain>=0?"+":""}{fmt(c.xfp_gain,2)} direkte effektiv xFP</b><span>{c.price_change>=0?"+":""}{fmt(c.price_change)}m</span></footer></article>)}</div>}</section>;
}

export default function FantasyOptimizerPage(){
 const[token,setToken]=useState<string|null>(null),[horizon,setHorizon]=useState<"next_game"|"next3">("next3"),[result,setResult]=useState<Result|null>(null),[locked,setLocked]=useState<Set<string>>(new Set()),[busy,setBusy]=useState(true),[message,setMessage]=useState("");
 useEffect(()=>{(async()=>{try{const sb=getSupabaseBrowserClient();if(!sb)throw new Error("Supabase er ikke tilgjengelig");const{data}=await sb.auth.getSession();const access=data.session?.access_token;if(!access)throw new Error("Du må være logget inn");setToken(access);await run(access,"next3",new Set())}catch(e:any){setMessage(e?.message||"Kunne ikke starte optimalisatoren");setBusy(false)}})()},[]);
 async function run(access=token,nextHorizon=horizon,nextLocked=locked){if(!access)return;setBusy(true);setMessage("");try{const qs=new URLSearchParams({horizon:nextHorizon});if(nextLocked.size)qs.set("locked",Array.from(nextLocked).join(","));const res=await fetch(`/api/fantasy/transfer-optimizer?${qs.toString()}`,{headers:{Authorization:`Bearer ${access}`},cache:"no-store"});const body=await res.json();if(!res.ok||!body.ok)throw new Error(body.error||"Kunne ikke analysere laget");setResult(body);setMessage(body.message||"")}catch(e:any){setResult(null);setMessage(e?.message||"Kunne ikke analysere laget")}finally{setBusy(false)}}
 function toggle(id:string){setLocked(prev=>{const next=new Set(prev);next.has(id)?next.delete(id):next.add(id);return next})}
 const policy=result?.transfer_policy;
 return <main className="fantasy-shell xfp-command-center"><section className="xfp-command-hero"><p className="fantasy-kicker">STANG INN XI · LAGHJELPER</p><h1>Lagoptimalisator</h1><p>Få forslag til de beste tillatte byttene for laget ditt. Modellen bruker pris, xFP, fixtures, availability, rekkeplassering og C/VC – og følger transferreglene for den aktuelle runden.</p></section>
  <section className="xfp-panel"><div className="xfp-panel-head"><div><p className="eyebrow">INNSTILLINGER</p><h2>Hva vil du optimalisere for?</h2><p>Lås spillere du absolutt vil beholde. De kan da ikke foreslås UT.</p></div><button className="xfp-primary" disabled={busy||!token} onClick={()=>run()}>{busy?"Analyserer …":"🧠 Analyser laget"}</button></div><div className="optimizer-controls"><label><span>Horisont</span><select value={horizon} onChange={e=>setHorizon(e.target.value as "next_game"|"next3")}><option value="next_game">Neste kamp</option><option value="next3">Neste 3 runder</option></select></label></div>{message&&<p className="team-message">{message}</p>}</section>
  {result&&<><section className="xfp-panel"><div className="optimizer-summary transfer-summary"><div><span>Ledige bytter</span><strong>{result.transfers_available}/{policy?.max_transfers??0}</strong><small>{policy?.boost_active?"Bytteboost aktiv":policy?.is_event_week?"Event Week":`${policy?.transfers_used||0} brukt`}</small></div><div><span>Nåværende xFP</span><strong>{fmt(result.current_score,2)}</strong><small>effektiv Fantasy-xFP</small></div><div><span>Lagverdi</span><strong>{fmt(result.current_cost,1)}m</strong><small>før foreslåtte bytter</small></div><div><span>Låst</span><strong>{locked.size}</strong><small>kan ikke foreslås UT</small></div></div><p className="team-message">{policy?.reason} Ingen byttebank og ingen poengtrekk for transfers.</p><TeamList players={result.current} locked={locked} toggle={toggle}/>{locked.size>0&&<div className="optimizer-lock-actions"><span>Kjør analysen på nytt etter at du har endret låser.</span><button type="button" className="xfp-secondary" onClick={()=>setLocked(new Set())}>Fjern alle låser</button></div>}</section>
   <section className="xfp-panel"><div className="xfp-panel-head"><div><p className="eyebrow">TRE STRATEGIER</p><h2>Sammenlign forslagene</h2><p>Balansert kombinerer forventning og risiko. Konservativ prioriterer trygghet. Offensiv kan godta mer usikkerhet for større modellert oppside.</p></div></div><div className="strategy-grid">{result.strategies.map(s=><article className={`strategy-card strategy-${s.key}`} key={s.key}><p className="eyebrow">{s.label}</p><strong className={s.xfp_gain>=0?"positive":"negative"}>{s.xfp_gain>=0?"+":""}{fmt(s.xfp_gain,2)} xFP</strong><span>{s.proposal_risk_label} risiko · {s.proposal_risk_score}/100</span><small>{s.changes.length} bytte{s.changes.length===1?"":"r"} · ny lagverdi {fmt(s.optimized_cost,1)}m</small></article>)}</div><p className="team-message">Base-xFP er rå prognose. Availability justerer den med 100/85/60/0 %. Effektiv Fantasy-xFP inkluderer deretter rekke 1/2 og C/VC. Risikoscore er usikkerhet, ikke Fantasy-poeng.</p>{result.strategies.map(s=><Changes key={s.key} strategy={s} available={result.transfers_available}/>)}</section></>}
 </main>;
}
