"use client";

import { useEffect, useMemo, useRef, useState } from "react";
import { getSupabaseBrowserClient } from "../../lib/supabase";
import TippingSectionNav from "../../components/TippingSectionNav";

type Player = { id: string; display_name: string };
type Match = { id: number; home_team: string; away_team: string; match_time: string | null; home_score: number | null; away_score: number | null; finished: boolean; round: number | null };
type Tip = { id?: number; player_id: string; match_id: number; home_tip: number; away_tip: number };
type TableTip = { team: string; position: number };
type Filter = "upcoming" | "untipped" | "finished" | "all";

function locked(match: Match, now = Date.now()) { return match.finished || (!!match.match_time && now >= new Date(match.match_time).getTime()); }
function countdown(value: string | null, now = Date.now()) { if (!value) return ""; const ms = new Date(value).getTime() - now; if (ms <= 0) return "låst"; const hours = Math.floor(ms / 3_600_000), days = Math.floor(hours / 24), minutes = Math.floor((ms % 3_600_000) / 60_000); return days > 0 ? `${days}d ${hours % 24}t` : `${hours}t ${minutes}m`; }
function displayTeam(value:string){const v=value.toLowerCase();if(v.includes("vålerenga"))return"Vålerenga";if(v.includes("stavanger"))return"Stavanger Oilers";if(v.includes("lillehammer"))return"Lillehammer";if(v.includes("ringerike"))return"Ringerike IHK";if(v.includes("storhamar"))return"Storhamar";if(v.includes("frisk asker"))return"Frisk Asker";if(v.includes("nidaros"))return"Nidaros";if(v.includes("sparta"))return"Sparta";if(v.includes("narvik"))return"Narvik";if(v.includes("stjernen"))return"Stjernen";if(v.includes("comet"))return"Comet Halden";if(v.includes("grüner")||v.includes("gruner"))return"Grüner";return value.replace(/\s*-\s*MEN\s*1$/i,"").replace(/\s+Elite$/i,"").trim();}
function matchDate(value:string|null){if(!value)return {weekday:"–",day:"–",month:"",time:"TBA"};const d=new Date(value);return{weekday:d.toLocaleDateString("no-NO",{weekday:"short"}).replace(".",""),day:d.toLocaleDateString("no-NO",{day:"2-digit"}),month:d.toLocaleDateString("no-NO",{month:"short"}).replace(".",""),time:d.toLocaleTimeString("no-NO",{hour:"2-digit",minute:"2-digit"})}}

function TipEditor({ match, existing, playerId, onSaved, now, nextId }: { match: Match; existing?: Tip; playerId: string; onSaved: () => Promise<void>; now: number; nextId?: number }) {
  const [home, setHome] = useState(existing?.home_tip ?? 0), [away, setAway] = useState(existing?.away_tip ?? 0), [saving, setSaving] = useState(false), [saved, setSaved] = useState(false);
  const awayRef = useRef<HTMLInputElement>(null); const isLocked = locked(match, now);
  useEffect(() => { setHome(existing?.home_tip ?? 0); setAway(existing?.away_tip ?? 0); }, [existing?.home_tip, existing?.away_tip]);
  async function save() { if (locked(match)) return; const supabase = getSupabaseBrowserClient(); if (!supabase) return; setSaving(true); setSaved(false); const { error } = await supabase.from("tips").upsert({ player_id: playerId, match_id: match.id, home_tip: home, away_tip: away }, { onConflict: "player_id,match_id" }); setSaving(false); if (error) { alert(error.message); return; } setSaved(true); await onSaved(); window.setTimeout(() => setSaved(false), 1800); if (nextId) window.setTimeout(() => document.getElementById(`tip-${nextId}`)?.scrollIntoView({ behavior: "smooth", block: "center" }), 250); }
  if (isLocked) return <div className="tipLockedSummary"><div><small>Ditt tips</small><strong>{existing ? `${existing.home_tip}–${existing.away_tip}` : "Ikke levert"}</strong></div></div>;
  return <div className="tipControls tipPickArea"><div className="tipPickLabel">Ditt tips</div><div className="tipScoreInputs"><label><span>{displayTeam(match.home_team)}</span><input aria-label={`Mål ${match.home_team}`} inputMode="numeric" type="number" min="0" value={home} onChange={e => setHome(Math.max(0, Number(e.target.value)))} onKeyDown={e => { if (e.key === "Enter") awayRef.current?.focus(); }} /></label><strong>–</strong><label><span>{displayTeam(match.away_team)}</span><input aria-label={`Mål ${match.away_team}`} ref={awayRef} inputMode="numeric" type="number" min="0" value={away} onChange={e => setAway(Math.max(0, Number(e.target.value)))} onKeyDown={e => { if (e.key === "Enter") save(); }} /></label></div><button className={`compactButton tipSaveButton ${saved ? "saved" : ""}`} disabled={saving} onClick={save}>{saving ? "Lagrer …" : saved ? "Lagret" : existing ? "Oppdater tips" : "Lagre tips"}</button></div>;
}

export default function TipsPage() {
  const [me, setMe] = useState<Player | null>(null), [players, setPlayers] = useState<Player[]>([]), [matches, setMatches] = useState<Match[]>([]), [tips, setTips] = useState<Tip[]>([]), [tableTips,setTableTips]=useState<TableTip[]>([]), [filter, setFilter] = useState<Filter>("upcoming"), [loading, setLoading] = useState(true), [query, setQuery] = useState(""), [clock, setClock] = useState(Date.now());
  async function load() { const supabase = getSupabaseBrowserClient(); if (!supabase) { setLoading(false); return; } const { data: session } = await supabase.auth.getSession(); const uid = session.session?.user.id; const [p,m,t,tt] = await Promise.all([supabase.from("players").select("id,display_name").order("created_at"), supabase.from("matches").select("id,home_team,away_team,match_time,home_score,away_score,finished,round").order("match_time"), supabase.from("tips").select("id,player_id,match_id,home_tip,away_tip"),uid?supabase.from("table_tips").select("team,position").eq("player_id",uid).order("position"):Promise.resolve({data:[] as TableTip[]})]); const ps=(p.data||[]) as Player[]; setPlayers(ps); setMe(ps.find(x=>x.id===uid)||null); setMatches((m.data||[]) as Match[]); setTips((t.data||[]) as Tip[]); setTableTips(((tt as any).data||[]) as TableTip[]); setClock(Date.now()); setLoading(false); }
  useEffect(()=>{load()},[]); useEffect(()=>{const timer=window.setInterval(()=>setClock(Date.now()),10000);return()=>window.clearInterval(timer)},[]);
  const ownTips=useMemo(()=>tips.filter(t=>t.player_id===me?.id),[tips,me]), ownTipMap=useMemo(()=>new Map(ownTips.map(t=>[t.match_id,t])),[ownTips]);
  const upcoming=useMemo(()=>matches.filter(m=>!locked(m,clock)),[matches,clock]), finished=useMemo(()=>matches.filter(m=>locked(m,clock)),[matches,clock]), untipped=useMemo(()=>upcoming.filter(m=>!ownTipMap.has(m.id)),[upcoming,ownTipMap]);
  const nextDeadline=useMemo(()=>untipped.map(m=>m.match_time).filter((x):x is string=>!!x).sort()[0]||null,[untipped]);
  const nextRound=useMemo(()=>{const rounds=[...new Set(upcoming.map(m=>m.round).filter((r):r is number=>r!==null))].sort((a,b)=>a-b);return rounds[0]??null},[upcoming]);
  const nextRoundMatches=useMemo(()=>nextRound===null?[]:upcoming.filter(m=>m.round===nextRound),[upcoming,nextRound]); const nextRoundDone=nextRoundMatches.filter(m=>ownTipMap.has(m.id)).length; const progress=nextRoundMatches.length?Math.round(nextRoundDone/nextRoundMatches.length*100):0;
  const filtered=useMemo(()=>{let source=filter==="upcoming"?upcoming:filter==="untipped"?untipped:filter==="finished"?finished:matches;const q=query.trim().toLowerCase();if(q)source=source.filter(m=>`${m.home_team} ${m.away_team}`.toLowerCase().includes(q));return [...source].sort((a,b)=>(a.round??999)-(b.round??999)||(a.match_time||"").localeCompare(b.match_time||""))},[filter,upcoming,untipped,finished,matches,query]);
  const groups=useMemo(()=>{const map=new Map<string,Match[]>();filtered.forEach(match=>{const key=match.round===null?"Uten runde":`Runde ${match.round}`;map.set(key,[...(map.get(key)||[]),match])});return[...map.entries()]},[filtered]);
  if(loading)return <main className="appShell"><p className="muted">Laster tips …</p></main>;
  return <main className="appShell tipsPage"><header className="topbar"><div className="tipsPageTitle"><div className="tipsPageTitleMark">SI</div><div><p className="eyebrow">EHL 2026/27</p><h1>Kamptips</h1></div></div><a href="/rules" className="textButton">Slik fungerer tippingen →</a></header><TippingSectionNav/>
    <section className={`heroCard tipsHero tipsOverviewHero ${untipped.length===0?"complete":""}`}><div><p className="eyebrow">Mine kamptips</p><h2>{untipped.length===0?"Alle kommende kamper er tippet":`${untipped.length} ${untipped.length===1?"kamp":"kamper"} mangler tips`}</h2><p className="muted">Tips kan endres frem til kampstart. Hver kamp låses automatisk når pucken droppes.</p></div><div className="tipsOverviewProgress"><span className="eyebrow">{nextRound!==null?`Runde ${nextRound}`:"Neste runde"}</span><strong>{nextRoundDone}/{nextRoundMatches.length||0} levert</strong><div className="tipsProgressLine"><span style={{width:`${progress}%`}}/></div><small>{nextDeadline?`Neste frist: ${countdown(nextDeadline,clock)}`:"Ingen kommende frist"}</small></div></section>
    <div className="tipsMainLayout"><section className="tipsMatchesPanel"><div className="tipsMatchesToolbar"><div className="tipsTools"><div className="matchFilters" aria-label="Filtrer kamper"><button className={filter==="upcoming"?"active":""} onClick={()=>setFilter("upcoming")}>Kommende <b>{upcoming.length}</b></button><button className={filter==="untipped"?"active warning":"warning"} onClick={()=>setFilter("untipped")}>Ikke tippet <b>{untipped.length}</b></button><button className={filter==="finished"?"active":""} onClick={()=>setFilter("finished")}>Låst <b>{finished.length}</b></button><button className={filter==="all"?"active":""} onClick={()=>setFilter("all")}>Alle</button></div><div className="matchToolbar"><input className="matchSearch" value={query} onChange={e=>setQuery(e.target.value)} placeholder="Søk etter lag …" aria-label="Søk etter lag" /></div></div></div>
      {groups.map(([round,roundMatches])=><section key={round} className="tipRoundBlock"><div className="tipRoundHeading"><div><p className="eyebrow" style={{marginBottom:2}}>{round}</p><strong>{roundMatches.length} kamper</strong></div><span className={`statusPill ${roundMatches.every(m=>ownTipMap.has(m.id)||locked(m,clock))?"complete":""}`}>{roundMatches.filter(m=>ownTipMap.has(m.id)).length}/{roundMatches.length} tippet</span></div>{roundMatches.map((match,index)=>{const existing=ownTipMap.get(match.id),delivered=tips.filter(t=>t.match_id===match.id).length,isLocked=locked(match,clock),next=roundMatches.slice(index+1).find(m=>!locked(m,clock)),date=matchDate(match.match_time);return <article id={`tip-${match.id}`} className={`tipCompactCard ${existing?"hasTip":""} ${isLocked?"isLocked":""}`} key={match.id}><div className="tipDateTile"><span>{date.weekday}</span><strong>{date.day}</strong><small>{date.month}</small><small>{date.time}</small></div><div className="tipTeams"><div className="tipTeamRow"><strong>{displayTeam(match.home_team)}</strong></div><div className="tipTeamRow"><strong>{displayTeam(match.away_team)}</strong></div></div>{me&&<TipEditor match={match} existing={existing} playerId={me.id} onSaved={load} now={clock} nextId={next?.id}/>}<div className="tipMatchStatus"><b className={existing?"done":""}>{isLocked?"Låst":existing?"Tippet":"Åpen"}</b><span>{match.finished&&match.home_score!==null&&match.away_score!==null?`Slutt ${match.home_score}–${match.away_score}`:existing?`${delivered}/${players.length} har tippet`:match.match_time?`Låses ${date.time}`:"Tid ikke satt"}</span><a href={`/match/${match.id}`} className="textButton">Detaljer →</a></div></article>})}</section>)}{groups.length===0&&<div className="unifiedEmpty">Ingen kamper her. Prøv et annet filter eller søk.</div>}</section>
      <aside className="tipsAside"><article className="tipsAsideCard"><h3>{nextRound!==null?`Runde ${nextRound} – oversikt`:"Rundeoversikt"}</h3><div className="tipsDonutWrap"><div className="tipsDonut" style={{"--tips-progress":`${progress}%`} as React.CSSProperties}/><div className="tipsDonutLabel"><strong>{nextRoundDone}</strong><small>av {nextRoundMatches.length}</small></div></div><div className="tipsAsideStats"><div><span>Tippet</span><b>{nextRoundDone}</b></div><div><span>Ikke tippet</span><b>{Math.max(0,nextRoundMatches.length-nextRoundDone)}</b></div><div><span>Låst</span><b>{finished.filter(m=>m.round===nextRound).length}</b></div></div></article><article className="tipsAsideCard"><h3>Tabelltips</h3><p className="muted">Ranger alle EHL-lag før sesongfristen og konkurrer på lavest avvik.</p><a className="tipsAsideLink" href="/tabletips">Åpne Tabelltips →</a></article><article className="tipsAsideCard tipsTablePreview"><h3>Ditt tabelltips</h3>{tableTips.length===10?<div className="tipsTableRows">{tableTips.map(row=><div key={row.position}><b>{row.position}</b><span>{displayTeam(row.team)}</span></div>)}</div>:<div className="tipsTableEmpty"><span>{tableTips.length}/10 lagret</span><small>Fullfør tabelltipset for å vise hele rangeringen her.</small></div>}<a className="tipsAsideTextLink" href="/tabletips">Se hele tabelltipset →</a></article><article className="tipsAsideCard"><h3>Slik får du poeng</h3><div className="tipsRuleList"><div><span>Eksakt resultat</span><b>5 p</b></div><div><span>Riktig utfall</span><b>3 p</b></div><div><span>Feil tips</span><b>0 p</b></div></div><a className="tipsAsideLink" href="/rules">Se alle regler →</a></article></aside></div>
    <section className="tipsFooterInfo"><div><strong>Tips før kampstart</strong><small>Du kan endre tips helt frem til kampstart.</small></div><div><strong>Automatisk låsing</strong><small>Tips låses automatisk når kampen starter.</small></div><div><strong>Følg med live</strong><small>Resultater og poeng oppdateres fortløpende.</small></div><div><strong>Konkurrer gjennom sesongen</strong><small>Leaderboard, miniligaer og awards følger resultatene.</small></div></section>
  </main>;
}
