"use client";

import { useEffect, useMemo, useState } from "react";
import { getSupabaseBrowserClient } from "../../lib/supabase";

type SyncRun={id:number;provider:string;started_at:string;finished_at:string|null;ok:boolean;imported_count:number;finished_count:number;error_message:string|null};
type Match={id:number;home_team:string;away_team:string;match_time:string|null;home_score:number|null;away_score:number|null;finished:boolean;round:number|null};

function syncAgeLabel(value:string|null){if(!value)return"Aldri";const ms=Date.now()-new Date(value).getTime();if(ms<60_000)return"nå nettopp";const min=Math.floor(ms/60_000);if(min<60)return`${min} min siden`;const hours=Math.floor(min/60);if(hours<24)return`${hours} t siden`;return`${Math.floor(hours/24)} d siden`}

export default function HockeytipsAdminPage(){
 const[allowed,setAllowed]=useState<boolean|null>(null),[runs,setRuns]=useState<SyncRun[]>([]),[matches,setMatches]=useState<Match[]>([]),[message,setMessage]=useState("");
 const[syncing,setSyncing]=useState(false);
 const[selectedMatchId,setSelectedMatchId]=useState<number|null>(null),[matchHome,setMatchHome]=useState(""),[matchAway,setMatchAway]=useState(""),[matchFinished,setMatchFinished]=useState(false),[matchTime,setMatchTime]=useState(""),[savingMatch,setSavingMatch]=useState(false);
 async function load(){const s=getSupabaseBrowserClient();if(!s)return;const{data:sessionData}=await s.auth.getSession();const user=sessionData.session?.user;if(!user){setAllowed(false);return}const{data:player}=await s.from("players").select("admin").eq("id",user.id).maybeSingle();if(!player?.admin){setAllowed(false);return}setAllowed(true);const[r,m]=await Promise.all([s.from("sync_runs").select("id,provider,started_at,finished_at,ok,imported_count,finished_count,error_message").order("started_at",{ascending:false}).limit(10),s.from("matches").select("id,home_team,away_team,match_time,home_score,away_score,finished,round").order("match_time")]);setRuns((r.data||[])as SyncRun[]);setMatches((m.data||[])as Match[])}
 useEffect(()=>{load();const timer=window.setInterval(load,60_000);return()=>window.clearInterval(timer)},[]);
 async function accessToken(){const s=getSupabaseBrowserClient();if(!s)return null;const{data}=await s.auth.getSession();return data.session?.access_token||null}
 async function sync(){const token=await accessToken();if(!token)return;setSyncing(true);setMessage("Synkroniserer EHL …");const response=await fetch("/api/admin/sync",{method:"POST",headers:{Authorization:`Bearer ${token}`}});const result=await response.json();setSyncing(false);setMessage(result.ok?`✓ ${result.imported} kamper synkronisert (${result.finished} ferdigspilt). Poeng endret: ${result.tipsChanged??0}.`:`Feil: ${result.error}`);await load()}
 function selectMatch(id:number){setSelectedMatchId(id);const m=matches.find(x=>x.id===id);if(!m)return;setMatchHome(m.home_score===null?"":String(m.home_score));setMatchAway(m.away_score===null?"":String(m.away_score));setMatchFinished(m.finished);setMatchTime(m.match_time?new Date(m.match_time).toISOString().slice(0,16):"")}
 async function saveMatch(){if(!selectedMatchId)return;const token=await accessToken();if(!token)return;if(!window.confirm("Lagre manuell kampkorrigering? Dette kan endre poeng og tabell."))return;setSavingMatch(true);setMessage("Lagrer kampkorrigering …");const response=await fetch("/api/admin/matches",{method:"PATCH",headers:{Authorization:`Bearer ${token}`,"Content-Type":"application/json"},body:JSON.stringify({id:selectedMatchId,home_score:matchHome===""?null:Number(matchHome),away_score:matchAway===""?null:Number(matchAway),finished:matchFinished,match_time:matchTime?new Date(matchTime).toISOString():null})});const result=await response.json();setSavingMatch(false);if(!result.ok){setMessage(`Feil: ${result.error}`);return}setMessage(`✓ Kampen er korrigert. ${result.scoring?.tipsChanged??0} tips fikk oppdaterte poeng.`);await load()}
 const correctionMatches=useMemo(()=>[...matches].sort((a,b)=>Math.abs((new Date(a.match_time||0).getTime()||0)-Date.now())-Math.abs((new Date(b.match_time||0).getTime()||0)-Date.now())).slice(0,30),[matches]);
 const syncHealth=useMemo(()=>{const last=runs[0]||null;const lastTs=last?.finished_at||last?.started_at||null;const ageMs=lastTs?Date.now()-new Date(lastTs).getTime():Infinity;let consecutiveFailures=0;for(const run of runs){if(run.ok)break;consecutiveFailures++}const stale=ageMs>15*60_000;const unhealthy=!last||!last.ok||stale;const label=!last?"Ingen synk logget":!last.ok?"Siste synk feilet":stale?"Synk ser ut til å ha stoppet":"Automatisk synk er frisk";return{last,lastTs,stale,unhealthy,consecutiveFailures,label}},[runs]);
 if(allowed===null)return <main className="appShell"><p className="muted">Sjekker admin-tilgang …</p></main>;
 if(!allowed)return <main className="appShell"><article className="panel"><h2>Ingen tilgang</h2><p className="muted">Denne siden er bare for administrator.</p><a href="/" className="textButton">← Tilbake til Stang Inn</a></article></main>;
 return <main className="appShell"><header className="topbar"><div className="brand"><div className="brandMark">🏒</div><div><p className="eyebrow">Administrasjon · Hockeytipset</p><h1>Hockeytipset</h1></div></div><a href="/admin" className="textButton">← Adminoversikt</a></header><section className="pageStack" style={{marginTop:24}}>
  <article className="heroCard"><div><p className="eyebrow">EHL-data</p><h2>Terminliste & resultater</h2><p className="muted">Henter HockeyLive-data og oppdaterer Supabase uten duplikater.</p></div><button className="compactButton" disabled={syncing} onClick={sync}>{syncing?"Synkroniserer …":"🔄 Synkroniser EHL"}</button></article>
  <article className="panel" style={{border:`1px solid ${syncHealth.unhealthy?"rgba(255,123,140,.48)":"rgba(84,222,168,.38)"}`,background:syncHealth.unhealthy?"rgba(255,123,140,.055)":"rgba(84,222,168,.045)"}}><div className="panelHeading"><div><p className="eyebrow">Automatisk HockeyLive-sync</p><h3>{syncHealth.unhealthy?"⚠️ ":"✅ "}{syncHealth.label}</h3></div><span className="statusPill">{syncAgeLabel(syncHealth.lastTs)}</span></div>{syncHealth.last?<div className="statsGrid" style={{marginTop:12}}><article className="miniCard"><span>Siste kjøring</span><strong>{new Date(syncHealth.last.started_at).toLocaleTimeString("no-NO",{hour:"2-digit",minute:"2-digit",second:"2-digit"})}</strong><small>{new Date(syncHealth.last.started_at).toLocaleDateString("no-NO")}</small></article><article className="miniCard"><span>Status</span><strong>{syncHealth.last.ok?"OK":"FEIL"}</strong><small>{syncHealth.last.ok?"HockeyLive svarte normalt":syncHealth.last.error_message||"Ukjent feil"}</small></article><article className="miniCard"><span>Kamper</span><strong>{syncHealth.last.imported_count}</strong><small>{syncHealth.last.finished_count} ferdige i synken</small></article><article className="miniCard"><span>Feil på rad</span><strong>{syncHealth.consecutiveFailures}</strong><small>{syncHealth.consecutiveFailures===0?"Ingen aktive feil":"Krever oppfølging"}</small></article></div>:<p className="muted">Ingen kjøringer er registrert i sync_runs ennå.</p>}{syncHealth.stale&&<p style={{marginTop:12,fontWeight:800,color:"#ff9baa"}}>Automatisk synk forventes hvert 5. minutt. Det er nå mer enn 15 minutter siden siste registrerte kjøring. Sjekk GitHub Actions og CRON_SECRET.</p>}{syncHealth.last&&!syncHealth.last.ok&&<p style={{marginTop:12,fontWeight:800,color:"#ff9baa"}}>Siste feil: {syncHealth.last.error_message||"Ukjent feil"}</p>}</article>
  {message&&<article className="quoteCard"><span>Status</span><p>{message}</p></article>}
  <article className="panel"><div className="panelHeading"><div><p className="eyebrow">Kampdata</p><h3>Manuell korrigering</h3></div><span className="statusPill">Admin only</span></div><p className="muted" style={{marginBottom:12}}>Brukes bare hvis HockeyLive har feil tidspunkt/status/resultat. Ved lagring beregnes poeng på nytt automatisk.</p><select className="roundSelect" value={selectedMatchId??""} onChange={e=>selectMatch(Number(e.target.value))}><option value="">Velg kamp …</option>{correctionMatches.map(m=><option key={m.id} value={m.id}>{m.round?`R${m.round} · `:""}{m.home_team} – {m.away_team} · {m.match_time?new Date(m.match_time).toLocaleString("no-NO"):"uten tid"}</option>)}</select>{selectedMatchId&&<div style={{display:"grid",gap:10,marginTop:12}}><label><span className="muted">Kampstart</span><input className="matchSearch" style={{width:"100%"}} type="datetime-local" value={matchTime} onChange={e=>setMatchTime(e.target.value)}/></label><div style={{display:"grid",gridTemplateColumns:"1fr 1fr",gap:10}}><label><span className="muted">Hjemmescore</span><input className="matchSearch" style={{width:"100%"}} type="number" min="0" value={matchHome} onChange={e=>setMatchHome(e.target.value)}/></label><label><span className="muted">Bortescore</span><input className="matchSearch" style={{width:"100%"}} type="number" min="0" value={matchAway} onChange={e=>setMatchAway(e.target.value)}/></label></div><label style={{display:"flex",gap:9,alignItems:"center"}}><input type="checkbox" checked={matchFinished} onChange={e=>setMatchFinished(e.target.checked)}/><span>Marker kampen som ferdig</span></label><button className="compactButton" disabled={savingMatch} onClick={saveMatch}>{savingMatch?"Lagrer …":"⚠️ Lagre korrigering"}</button></div>}</article>
  <article className="panel"><div className="panelHeading"><div><p className="eyebrow">Brukere</p><h3>Felles brukeradministrasjon</h3></div><span className="statusPill">Flyttet</span></div><p className="muted">Profiler, Auth-status, administratorroller, deaktivering/gjenåpning og auditlogg administreres nå kun i den felles Stang Inn-flaten.</p><a href="/admin/users" className="compactButton" style={{display:"inline-flex",marginTop:12,textDecoration:"none"}}>Åpne brukeradministrasjon →</a></article>
  <article className="panel"><div className="panelHeading"><div><p className="eyebrow">Historikk</p><h3>Siste synkroniseringer</h3></div><span className="statusPill">{runs.length} vist</span></div><div className="simpleList">{runs.length===0&&<p className="muted">Ingen synkroniseringer logget ennå.</p>}{runs.map(run=><div key={run.id}><span>{new Date(run.started_at).toLocaleString("no-NO")} · {run.provider}</span><strong>{run.ok?`✓ ${run.imported_count} kamper · ${run.finished_count} ferdige`:`✕ ${run.error_message||"Feil"}`}</strong></div>)}</div></article>
 </section></main>
}
