"use client";

import { useEffect, useMemo, useState } from "react";
import { getSupabaseBrowserClient } from "../../lib/supabase";

type SyncRun={id:number;provider:string;started_at:string;finished_at:string|null;ok:boolean;imported_count:number;finished_count:number;error_message:string|null};
type Player={id:string;display_name:string;email:string|null;admin:boolean;created_at:string};
type TipOwner={player_id:string};
type Match={id:number;home_team:string;away_team:string;match_time:string|null;home_score:number|null;away_score:number|null;finished:boolean;round:number|null};
type EditState={display_name:string;email:string;admin:boolean};

function syncAgeLabel(value:string|null){if(!value)return"Aldri";const ms=Date.now()-new Date(value).getTime();if(ms<60_000)return"nå nettopp";const min=Math.floor(ms/60_000);if(min<60)return`${min} min siden`;const hours=Math.floor(min/60);if(hours<24)return`${hours} t siden`;return`${Math.floor(hours/24)} d siden`}

export default function HockeytipsAdminPage(){
 const[allowed,setAllowed]=useState<boolean|null>(null),[runs,setRuns]=useState<SyncRun[]>([]),[players,setPlayers]=useState<Player[]>([]),[tips,setTips]=useState<TipOwner[]>([]),[matches,setMatches]=useState<Match[]>([]),[message,setMessage]=useState("");
 const[syncing,setSyncing]=useState(false),[savingId,setSavingId]=useState<string|null>(null),[deletingId,setDeletingId]=useState<string|null>(null),[editingId,setEditingId]=useState<string|null>(null),[edit,setEdit]=useState<EditState>({display_name:"",email:"",admin:false}),[currentUserId,setCurrentUserId]=useState<string|null>(null),[userSearch,setUserSearch]=useState("");
 const[selectedMatchId,setSelectedMatchId]=useState<number|null>(null),[matchHome,setMatchHome]=useState(""),[matchAway,setMatchAway]=useState(""),[matchFinished,setMatchFinished]=useState(false),[matchTime,setMatchTime]=useState(""),[savingMatch,setSavingMatch]=useState(false);
 async function load(){const s=getSupabaseBrowserClient();if(!s)return;const{data:sessionData}=await s.auth.getSession();const user=sessionData.session?.user;if(!user){setAllowed(false);return}setCurrentUserId(user.id);const{data:player}=await s.from("players").select("admin").eq("id",user.id).maybeSingle();if(!player?.admin){setAllowed(false);return}setAllowed(true);const[r,p,t,m]=await Promise.all([s.from("sync_runs").select("id,provider,started_at,finished_at,ok,imported_count,finished_count,error_message").order("started_at",{ascending:false}).limit(10),s.from("players").select("id,display_name,email,admin,created_at").order("created_at"),s.from("tips").select("player_id"),s.from("matches").select("id,home_team,away_team,match_time,home_score,away_score,finished,round").order("match_time")]);setRuns((r.data||[])as SyncRun[]);setPlayers((p.data||[])as Player[]);setTips((t.data||[])as TipOwner[]);setMatches((m.data||[])as Match[])}
 useEffect(()=>{load();const timer=window.setInterval(load,60_000);return()=>window.clearInterval(timer)},[]);
 async function accessToken(){const s=getSupabaseBrowserClient();if(!s)return null;const{data}=await s.auth.getSession();return data.session?.access_token||null}
 async function sync(){const token=await accessToken();if(!token)return;setSyncing(true);setMessage("Synkroniserer EHL …");const response=await fetch("/api/admin/sync",{method:"POST",headers:{Authorization:`Bearer ${token}`}});const result=await response.json();setSyncing(false);setMessage(result.ok?`✓ ${result.imported} kamper synkronisert (${result.finished} ferdigspilt). Poeng endret: ${result.tipsChanged??0}.`:`Feil: ${result.error}`);await load()}
 function startEdit(player:Player){setEditingId(player.id);setEdit({display_name:player.display_name,email:player.email||"",admin:player.admin});setMessage("")}
 async function saveUser(id:string){const token=await accessToken();if(!token)return;setSavingId(id);setMessage("Lagrer bruker …");const response=await fetch("/api/admin/users",{method:"PATCH",headers:{Authorization:`Bearer ${token}`,"Content-Type":"application/json"},body:JSON.stringify({id,...edit})});const result=await response.json();setSavingId(null);if(!result.ok){setMessage(`Feil: ${result.error}`);return}setEditingId(null);setMessage("✓ Brukeren er oppdatert.");await load()}
 async function deleteUser(player:Player){if(player.id===currentUserId){setMessage("Du kan ikke slette din egen administratorkonto.");return}if(!window.confirm(`Slette ${player.display_name}? Alle tips fra denne brukeren blir også slettet. Dette kan ikke angres.`))return;const token=await accessToken();if(!token)return;setDeletingId(player.id);const response=await fetch("/api/admin/users",{method:"DELETE",headers:{Authorization:`Bearer ${token}`,"Content-Type":"application/json"},body:JSON.stringify({id:player.id})});const result=await response.json();setDeletingId(null);if(!result.ok){setMessage(`Feil: ${result.error}`);return}setMessage(`✓ ${player.display_name} er slettet.`);if(editingId===player.id)setEditingId(null);await load()}
 function selectMatch(id:number){setSelectedMatchId(id);const m=matches.find(x=>x.id===id);if(!m)return;setMatchHome(m.home_score===null?"":String(m.home_score));setMatchAway(m.away_score===null?"":String(m.away_score));setMatchFinished(m.finished);setMatchTime(m.match_time?new Date(m.match_time).toISOString().slice(0,16):"")}
 async function saveMatch(){if(!selectedMatchId)return;const token=await accessToken();if(!token)return;if(!window.confirm("Lagre manuell kampkorrigering? Dette kan endre poeng og tabell."))return;setSavingMatch(true);setMessage("Lagrer kampkorrigering …");const response=await fetch("/api/admin/matches",{method:"PATCH",headers:{Authorization:`Bearer ${token}`,"Content-Type":"application/json"},body:JSON.stringify({id:selectedMatchId,home_score:matchHome===""?null:Number(matchHome),away_score:matchAway===""?null:Number(matchAway),finished:matchFinished,match_time:matchTime?new Date(matchTime).toISOString():null})});const result=await response.json();setSavingMatch(false);if(!result.ok){setMessage(`Feil: ${result.error}`);return}setMessage(`✓ Kampen er korrigert. ${result.scoring?.tipsChanged??0} tips fikk oppdaterte poeng.`);await load()}
 const tipCounts=useMemo(()=>{const c=new Map<string,number>();tips.forEach(t=>c.set(t.player_id,(c.get(t.player_id)||0)+1));return c},[tips]);
 const visiblePlayers=useMemo(()=>{const q=userSearch.trim().toLowerCase();return q?players.filter(p=>`${p.display_name} ${p.email||""}`.toLowerCase().includes(q)):players},[players,userSearch]);
 const correctionMatches=useMemo(()=>[...matches].sort((a,b)=>Math.abs((new Date(a.match_time||0).getTime()||0)-Date.now())-Math.abs((new Date(b.match_time||0).getTime()||0)-Date.now())).slice(0,30),[matches]);
 const syncHealth=useMemo(()=>{const last=runs[0]||null;const lastTs=last?.finished_at||last?.started_at||null;const ageMs=lastTs?Date.now()-new Date(lastTs).getTime():Infinity;let consecutiveFailures=0;for(const run of runs){if(run.ok)break;consecutiveFailures++}const stale=ageMs>15*60_000;const unhealthy=!last||!last.ok||stale;const label=!last?"Ingen synk logget":!last.ok?"Siste synk feilet":stale?"Synk ser ut til å ha stoppet":"Automatisk synk er frisk";return{last,lastTs,ageMs,stale,unhealthy,consecutiveFailures,label}},[runs]);
 if(allowed===null)return <main className="appShell"><p className="muted">Sjekker admin-tilgang …</p></main>;
 if(!allowed)return <main className="appShell"><article className="panel"><h2>Ingen tilgang</h2><p className="muted">Denne siden er bare for administrator.</p><a href="/" className="textButton">← Tilbake til Stang Inn</a></article></main>;
 return <main className="appShell"><header className="topbar"><div className="brand"><div className="brandMark">🏒</div><div><p className="eyebrow">Administrasjon · Hockeytipset</p><h1>Hockeytipset</h1></div></div><a href="/admin" className="textButton">← Adminoversikt</a></header><section className="pageStack" style={{marginTop:24}}>
  <article className="heroCard"><div><p className="eyebrow">EHL-data</p><h2>Terminliste & resultater</h2><p className="muted">Henter HockeyLive-data og oppdaterer Supabase uten duplikater.</p></div><button className="compactButton" disabled={syncing} onClick={sync}>{syncing?"Synkroniserer …":"🔄 Synkroniser EHL"}</button></article>
  <article className="panel" style={{border:`1px solid ${syncHealth.unhealthy?"rgba(255,123,140,.48)":"rgba(84,222,168,.38)"}`,background:syncHealth.unhealthy?"rgba(255,123,140,.055)":"rgba(84,222,168,.045)"}}><div className="panelHeading"><div><p className="eyebrow">Automatisk HockeyLive-sync</p><h3>{syncHealth.unhealthy?"⚠️ ":"✅ "}{syncHealth.label}</h3></div><span className="statusPill">{syncAgeLabel(syncHealth.lastTs)}</span></div>{syncHealth.last?<div className="statsGrid" style={{marginTop:12}}><article className="miniCard"><span>Siste kjøring</span><strong>{new Date(syncHealth.last.started_at).toLocaleTimeString("no-NO",{hour:"2-digit",minute:"2-digit",second:"2-digit"})}</strong><small>{new Date(syncHealth.last.started_at).toLocaleDateString("no-NO")}</small></article><article className="miniCard"><span>Status</span><strong>{syncHealth.last.ok?"OK":"FEIL"}</strong><small>{syncHealth.last.ok?"HockeyLive svarte normalt":syncHealth.last.error_message||"Ukjent feil"}</small></article><article className="miniCard"><span>Kamper</span><strong>{syncHealth.last.imported_count}</strong><small>{syncHealth.last.finished_count} ferdige i synken</small></article><article className="miniCard"><span>Feil på rad</span><strong>{syncHealth.consecutiveFailures}</strong><small>{syncHealth.consecutiveFailures===0?"Ingen aktive feil":"Krever oppfølging"}</small></article></div>:<p className="muted">Ingen kjøringer er registrert i sync_runs ennå.</p>}{syncHealth.stale&&<p style={{marginTop:12,fontWeight:800,color:"#ff9baa"}}>Automatisk synk forventes hvert 5. minutt. Det er nå mer enn 15 minutter siden siste registrerte kjøring. Sjekk GitHub Actions og CRON_SECRET.</p>}{syncHealth.last&&!syncHealth.last.ok&&<p style={{marginTop:12,fontWeight:800,color:"#ff9baa"}}>Siste feil: {syncHealth.last.error_message||"Ukjent feil"}</p>}</article>
  {message&&<article className="quoteCard"><span>Status</span><p>{message}</p></article>}
  <article className="panel"><div className="panelHeading"><div><p className="eyebrow">Kampdata</p><h3>Manuell korrigering</h3></div><span className="statusPill">Admin only</span></div><p className="muted" style={{marginBottom:12}}>Brukes bare hvis HockeyLive har feil tidspunkt/status/resultat. Ved lagring beregnes poeng på nytt automatisk.</p><select className="roundSelect" value={selectedMatchId??""} onChange={e=>selectMatch(Number(e.target.value))}><option value="">Velg kamp …</option>{correctionMatches.map(m=><option key={m.id} value={m.id}>{m.round?`R${m.round} · `:""}{m.home_team} – {m.away_team} · {m.match_time?new Date(m.match_time).toLocaleString("no-NO"):"uten tid"}</option>)}</select>{selectedMatchId&&<div style={{display:"grid",gap:10,marginTop:12}}><label><span className="muted">Kampstart</span><input className="matchSearch" style={{width:"100%"}} type="datetime-local" value={matchTime} onChange={e=>setMatchTime(e.target.value)}/></label><div style={{display:"grid",gridTemplateColumns:"1fr 1fr",gap:10}}><label><span className="muted">Hjemmescore</span><input className="matchSearch" style={{width:"100%"}} type="number" min="0" value={matchHome} onChange={e=>setMatchHome(e.target.value)}/></label><label><span className="muted">Bortescore</span><input className="matchSearch" style={{width:"100%"}} type="number" min="0" value={matchAway} onChange={e=>setMatchAway(e.target.value)}/></label></div><label style={{display:"flex",gap:9,alignItems:"center"}}><input type="checkbox" checked={matchFinished} onChange={e=>setMatchFinished(e.target.checked)}/><span>Marker kampen som ferdig</span></label><button className="compactButton" disabled={savingMatch} onClick={saveMatch}>{savingMatch?"Lagrer …":"⚠️ Lagre korrigering"}</button></div>}</article>
  <article className="panel"><div className="panelHeading"><div><p className="eyebrow">Brukere</p><h3>Administrer spillere</h3></div><span className="statusPill">{players.length} brukere</span></div><input className="matchSearch" value={userSearch} onChange={e=>setUserSearch(e.target.value)} placeholder="Søk navn eller e-post …" style={{width:"100%",marginBottom:12}}/><div className="pageStack">{visiblePlayers.map(player=>{const isEditing=editingId===player.id,isSelf=player.id===currentUserId;return <div key={player.id} style={{padding:14,border:"1px solid var(--line)",borderRadius:14,background:"#0a1729"}}>{!isEditing?<div style={{display:"flex",justifyContent:"space-between",gap:12,alignItems:"flex-start",flexWrap:"wrap"}}><div><strong style={{fontSize:18}}>{player.display_name}</strong><div className="muted" style={{marginTop:3}}>{player.email||"Ingen e-post"}</div><div className="muted" style={{marginTop:5,fontSize:12}}>{player.admin?"👑 Administrator":"Spiller"} · {tipCounts.get(player.id)||0} tips{isSelf?" · deg":""}</div></div><div style={{display:"flex",gap:8}}><button className="compactButton" onClick={()=>startEdit(player)}>✏️ Endre</button><button onClick={()=>deleteUser(player)} disabled={isSelf||deletingId===player.id} style={{padding:"10px 13px",borderRadius:12,border:"1px solid rgba(255,123,140,.45)",background:"rgba(255,123,140,.1)",color:"#ff9baa",fontWeight:900}}>{deletingId===player.id?"Sletter …":"🗑️ Slett"}</button></div></div>:<div style={{display:"grid",gap:10}}><input className="matchSearch" value={edit.display_name} onChange={e=>setEdit(v=>({...v,display_name:e.target.value}))}/><input className="matchSearch" type="email" value={edit.email} onChange={e=>setEdit(v=>({...v,email:e.target.value}))}/><label style={{display:"flex",alignItems:"center",gap:9}}><input type="checkbox" checked={edit.admin} disabled={isSelf} onChange={e=>setEdit(v=>({...v,admin:e.target.checked}))}/><span>Administrator{isSelf?" (kan ikke fjernes fra deg selv)":""}</span></label><div style={{display:"flex",gap:8}}><button className="compactButton" disabled={savingId===player.id} onClick={()=>saveUser(player.id)}>{savingId===player.id?"Lagrer …":"Lagre"}</button><button className="textButton" onClick={()=>setEditingId(null)}>Avbryt</button></div></div>}</div>})}</div></article>
  <article className="panel"><div className="panelHeading"><div><p className="eyebrow">Historikk</p><h3>Siste synkroniseringer</h3></div><span className="statusPill">{runs.length} vist</span></div><div className="simpleList">{runs.length===0&&<p className="muted">Ingen synkroniseringer logget ennå.</p>}{runs.map(run=><div key={run.id}><span>{new Date(run.started_at).toLocaleString("no-NO")} · {run.provider}</span><strong>{run.ok?`✓ ${run.imported_count} kamper · ${run.finished_count} ferdige`:`✕ ${run.error_message||"Feil"}`}</strong></div>)}</div></article>
 </section></main>
}
