"use client";
import {useEffect,useMemo,useState} from "react";
import {getSupabaseBrowserClient} from "../../../../../lib/supabase";
import "../../../fantasy.css";
import "../../xfp-admin.css";

type Player={id:string;name:string;team:string;position:string};
type Finding={id:number;source_kind:string;source_label:string;source_url?:string|null;source_published_at?:string|null;raw_player_name:string;raw_team?:string|null;raw_status:string;raw_note?:string|null;proposed_player_id?:string|null;match_method?:string|null;match_confidence?:number|null;match_reason?:string|null;review_status:string;review_note?:string|null;proposed_player?:Player|null};
const statusLabels:Record<string,string>={available:"Kampklar",questionable:"Usikker",out:"Bekreftet ute",long_term:"Langtidsskadd",returning:"Tilbake i trening",not_in_lineup:"Ikke i kamptropp"};
const reviewLabels:Record<string,string>={pending:"Foreslått",needs_review:"Krever kontroll",rejected:"Avvist",approved:"Godkjent"};

export default function AvailabilityFindingsPage(){
 const[token,setToken]=useState<string|null>(null),[rows,setRows]=useState<Finding[]>([]),[players,setPlayers]=useState<Player[]>([]),[msg,setMsg]=useState("Laster …"),[busy,setBusy]=useState<number|null>(null),[filter,setFilter]=useState("open");
 async function load(t=token){if(!t)return;const h={Authorization:`Bearer ${t}`};const[a,b]=await Promise.all([fetch("/api/admin/fantasy/availability-findings",{headers:h,cache:"no-store"}),fetch("/api/admin/fantasy/availability",{headers:h,cache:"no-store"})]);const fa=await a.json(),av=await b.json();if(!a.ok||!fa.ok)throw new Error(fa.error||"Kunne ikke hente funn");if(!b.ok||!av.ok)throw new Error(av.error||"Kunne ikke hente roster");setRows(fa.rows||[]);setPlayers((av.rows||[]).map((r:any)=>({id:r.id,name:r.name,team:r.team,position:r.position})));setMsg(`${(fa.rows||[]).length} funn`)}
 useEffect(()=>{(async()=>{try{const s=getSupabaseBrowserClient();const{data}=await s!.auth.getSession();const t=data.session?.access_token;if(!t)throw new Error("Du må være logget inn");setToken(t);await load(t)}catch(e:any){setMsg(e.message)}})()},[]);
 async function review(r:Finding,reviewStatus:"pending"|"needs_review"|"rejected",proposedPlayerId?:string|null){if(!token)return;setBusy(r.id);try{const res=await fetch("/api/admin/fantasy/availability-findings",{method:"PATCH",headers:{Authorization:`Bearer ${token}`,"Content-Type":"application/json"},body:JSON.stringify({id:r.id,reviewStatus,proposedPlayerId})});const b=await res.json();if(!res.ok||!b.ok)throw new Error(b.error||"Kunne ikke oppdatere funn");await load(token);setMsg(`✓ Funn #${r.id} oppdatert`)}catch(e:any){setMsg(e.message)}finally{setBusy(null)}}
 const shown=useMemo(()=>rows.filter(r=>filter==="all"||(filter==="open"?(r.review_status==="pending"||r.review_status==="needs_review"):r.review_status===filter)),[rows,filter]);
 return <main className="fantasy-shell xfp-command-center">
  <section className="xfp-command-hero"><p className="fantasy-kicker">STANG INN · MP-09</p><h1>Availability-funn</h1><p>Eksterne observasjoner er kandidater, ikke fasit. Ingen rad her endrer spillerens faktiske availability før en senere eksplisitt godkjenningsflyt.</p></section>
  <section className="xfp-panel">
   <div className="xfp-panel-head"><div><p className="eyebrow">SIKKER REVIEW-KØ</p><h2>Roster-matching</h2><p>Klubbavvik, manglende klubb og tvetydige navn må kontrolleres manuelt.</p></div><a className="xfp-secondary" href="/fantasy/admin-analysis/availability">← Spillerstatus</a></div>
   <div className="xfp-actions"><select className="xfp-select" value={filter} onChange={e=>setFilter(e.target.value)}><option value="open">Åpne funn</option><option value="needs_review">Krever kontroll</option><option value="pending">Foreslått</option><option value="rejected">Avvist</option><option value="all">Alle</option></select><span>{msg}</span></div>
   <div className="preseason-table-wrap"><table className="preseason-table"><thead><tr><th>Kilde</th><th>Observasjon</th><th>Foreslått spiller</th><th>Match</th><th>Review</th></tr></thead><tbody>{shown.map(r=><tr key={r.id}><td><strong>{r.source_label}</strong><small>{r.source_kind}{r.source_url&&<> · <a href={r.source_url} target="_blank" rel="noreferrer">åpne</a></>}</small></td><td><strong>{r.raw_player_name}</strong><small>{r.raw_team||"Klubb mangler"} · {statusLabels[r.raw_status]||r.raw_status}</small>{r.raw_note&&<small>{r.raw_note}</small>}</td><td>{r.proposed_player?<><strong>{r.proposed_player.name}</strong><small>{r.proposed_player.team} · {r.proposed_player.position}</small></>:<strong>Ingen sikker match</strong>}<select disabled={busy===r.id} value={r.proposed_player_id||""} onChange={e=>review(r,"needs_review",e.target.value||null)}><option value="">Velg spiller manuelt …</option>{players.map(p=><option key={p.id} value={p.id}>{p.name} · {p.team}</option>)}</select></td><td><strong>{r.match_confidence==null?"—":`${Math.round(r.match_confidence*100)} %`}</strong><small>{r.match_method||"ingen automatisk match"}</small><small>{r.match_reason||"—"}</small></td><td><strong>{reviewLabels[r.review_status]||r.review_status}</strong><div className="xfp-actions"><button className="xfp-secondary" disabled={busy===r.id} onClick={()=>review(r,"needs_review")}>Krever kontroll</button><button className="xfp-secondary" disabled={busy===r.id} onClick={()=>review(r,"rejected")}>Avvis</button></div></td></tr>)}</tbody></table>{!shown.length&&<p className="xfp-empty">Ingen funn i dette filteret.</p>}</div>
  </section>
 </main>;
}
