"use client";

import {useMemo,useState} from "react";
import {getSupabaseBrowserClient} from "../../../../lib/supabase";
import "../../fantasy.css";

type Row={name:string;team:string;position:string;price:number|null;available_for_purchase:boolean;model_version:string|null;publication_price:number|null;routing:string|null;confidence:string|null;source:string|null;historical_games:number;season_ppg:number|null;observed_value_per_million:number|null;preseason_games:number;baseline_xfp:number|null;preseason_xfp:number|null;preseason_delta_pct:number;action:string;suggested_delta:number;suggested_price:number|null;reason:string};
type Report={ok:boolean;error?:string;generated_at:string;publication:any;summary:{roster:number;priced:number;missing:number;review_up:number;review_down:number;average_price:number};rows:Row[]};

async function token(){const s=getSupabaseBrowserClient();const {data}=await s!.auth.getSession();if(!data.session?.access_token)throw new Error("Logg inn som admin");return data.session.access_token}
const fmt=(v:number|null,d=2)=>v==null?"—":v.toFixed(d);

export default function Page(){
  const[busy,setBusy]=useState(false),[msg,setMsg]=useState("Klar for read-only MP-03.6-kontroll"),[report,setReport]=useState<Report|null>(null),[filter,setFilter]=useState("review");
  async function run(){setBusy(true);try{const t=await token(),r=await fetch("/api/admin/fantasy/price-calibration",{headers:{Authorization:`Bearer ${t}`},cache:"no-store"}),j=await r.json();if(!r.ok||!j.ok)throw new Error(j.error||"Kunne ikke generere rapport");setReport(j);setMsg(`Ferdig · ${j.summary.roster} current-roster · ${j.summary.priced} priset · ${j.summary.missing} mangler pris · ingen writes`)}catch(e:any){setMsg(`Feil: ${e.message||e}`)}finally{setBusy(false)}}
  const rows=useMemo(()=>{const all=report?.rows||[];if(filter==="all")return all;if(filter==="missing")return all.filter(x=>x.action==="Mangler pris");if(filter==="up")return all.filter(x=>x.action==="Kontroller opp");if(filter==="down")return all.filter(x=>x.action==="Kontroller ned");return all.filter(x=>x.action!=="Behold")},[report,filter]);
  return <main className="fantasy-shell"><section className="fantasy-hero"><div><p className="fantasy-kicker">MP-03.6 · READ-ONLY · 2026/27</p><h1>Preseason priskalibrering</h1><p className="fantasy-lead">Kontrollrapport som sammenholder publisert V4.6.1-pris med historisk fantasyproduksjon, verdi per million og preseason-xFP. Rapporten endrer aldri priser.</p></div><a className="pill" href="/fantasy">← Fantasy-sentralen</a></section>
  <section className="fantasy-card"><button disabled={busy} onClick={run}>{busy?"Analyserer …":"Generer kalibreringsrapport"}</button> <span>{msg}</span>{report&&<><div style={{display:"grid",gridTemplateColumns:"repeat(auto-fit,minmax(150px,1fr))",gap:10,margin:"18px 0"}}>{[["Roster",report.summary.roster],["Priset",report.summary.priced],["Mangler pris",report.summary.missing],["Kontroller opp",report.summary.review_up],["Kontroller ned",report.summary.review_down],["Snittpris",`${report.summary.average_price.toFixed(2)}m`]].map(([a,b]:any)=><div key={a} style={{padding:14,borderRadius:12,background:"#f5f7fa"}}><b>{a}</b><div style={{fontSize:25,fontWeight:900}}>{b}</div></div>)}</div>
  <div style={{padding:12,borderRadius:12,background:"#fff8e6",border:"1px solid #ead7a2",marginBottom:14}}><b>Kalibreringsregel:</b> xFP er kontrollsignal, ikke prismotor. Automatisk review oppstår bare ved minst 20 historiske kamper og topp/bunn 10 % verdi per million innen egen posisjon. Preseason brukes kun som forsterkende forklaring. Manglende pris flagges separat.</div>
  <div style={{display:"flex",gap:8,flexWrap:"wrap",marginBottom:12}}>{[["review","Kun kontrollsaker"],["missing","Mangler pris"],["up","Opp"],["down","Ned"],["all","Alle"]].map(([v,l])=><button key={v} onClick={()=>setFilter(v)} style={{opacity:filter===v?1:.6}}>{l}</button>)}</div>
  <div style={{overflowX:"auto"}}><table style={{width:"100%",minWidth:1350,borderCollapse:"collapse",fontSize:12}}><thead><tr>{["Spiller","Lag","Pos","Pris","V4.6.1-rute","Hist K","FP/K","FP/m","Pre K","Pre-xFP","Δ pre","Vurdering","Forslag","Hvorfor"].map(h=><th key={h} style={{padding:8,textAlign:"left",background:"#eef3f8"}}>{h}</th>)}</tr></thead><tbody>{rows.map(x=><tr key={`${x.team}-${x.name}`} style={{borderBottom:"1px solid #edf0f3"}}><td style={{padding:8,fontWeight:800}}>{x.name}</td><td>{x.team}</td><td>{x.position}</td><td>{x.price==null?"—":`${x.price.toFixed(1)}m`}</td><td>{x.routing||"Ny etter publisering"}<br/><span style={{opacity:.65}}>{x.confidence||"—"}</span></td><td>{x.historical_games}</td><td>{fmt(x.season_ppg)}</td><td>{fmt(x.observed_value_per_million,3)}</td><td>{x.preseason_games}</td><td>{fmt(x.preseason_xfp)}</td><td>{x.preseason_games?`${x.preseason_delta_pct>0?"+":""}${x.preseason_delta_pct.toFixed(1)}%`:"—"}</td><td style={{fontWeight:800}}>{x.action}</td><td style={{fontWeight:900}}>{x.price==null?"Pris må modelleres":x.suggested_delta===0?"Behold":`${x.suggested_delta>0?"+":""}${x.suggested_delta.toFixed(1)}m → ${x.suggested_price?.toFixed(1)}m`}</td><td>{x.reason}</td></tr>)}</tbody></table></div></>}</section></main>
}
