"use client";
import { useEffect,useMemo,useState } from "react";
import { getSupabaseBrowserClient } from "../../../lib/supabase";
import "../fantasy.css";

type R={id:string;name:string;team:string;position:string;games:number;totalFP:number;ppg:number;last5FP:number;last5PPG:number;last10PPG:number;goals:number;assists:number;shots:number;plusMinus:number;pim:number};
export default function Page(){
 const[rows,setRows]=useState<R[]>([]),[msg,setMsg]=useState("Laster …"),[pos,setPos]=useState("ALL"),[sort,setSort]=useState("FORM5"),[busy,setBusy]=useState(false);
 async function load(){setBusy(true);try{const s=getSupabaseBrowserClient();const{data}=await s!.auth.getSession();const a=data.session?.access_token;if(!a)throw new Error("Du må være logget inn som admin.");const res=await fetch("/api/fantasy-player-form?season=2025%2F26",{headers:{Authorization:`Bearer ${a}`}});const p=await res.json();if(!res.ok||!p.ok)throw new Error(p.error||"Kunne ikke hente formdata");setRows(p.result.rows||[]);setMsg(`${p.result.players} spillere · ${p.result.games} kamper · ${p.result.statRows} spillerrader`)}catch(e:any){setMsg(e?.message||"Ukjent feil")}finally{setBusy(false)}}
 useEffect(()=>{load()},[]);
 const shown=useMemo(()=>{const x=pos==="ALL"?rows:rows.filter(r=>r.position===pos);return[...x].sort((a,b)=>sort==="TOTAL"?b.totalFP-a.totalFP:sort==="PPG"?b.ppg-a.ppg:sort==="FORM10"?b.last10PPG-a.last10PPG:b.last5PPG-a.last5PPG).slice(0,100)},[rows,pos,sort]);
 return <main className="fantasy-shell"><section className="fantasy-hero"><div><p className="fantasy-kicker">STANG INN · ADMIN · FANTASY</p><h1>Form & spiller-ranking</h1><p className="fantasy-lead">Historisk 19Fantasy-form fra EHL 2025/26.</p></div><a className="pill" href="/fantasy" style={{textDecoration:"none"}}>← Fantasy-sentralen</a></section><section className="fantasy-card"><div className="card-heading"><div><p className="eyebrow">SPILLERDATABASE</p><h2>Ranking</h2></div><button onClick={load} disabled={busy}>{busy?"Oppdaterer …":"Oppdater"}</button></div><p className="card-copy">{msg}</p><div style={{display:"flex",gap:8,flexWrap:"wrap",margin:"12px 0"}}><select value={pos} onChange={e=>setPos(e.target.value)} style={{padding:10,borderRadius:10}}><option value="ALL">Alle</option><option value="G">Keepere</option><option value="D">Backer</option><option value="C">Sentere</option><option value="W">Vinger</option></select><select value={sort} onChange={e=>setSort(e.target.value)} style={{padding:10,borderRadius:10}}><option value="FORM5">Form siste 5</option><option value="FORM10">Form siste 10</option><option value="PPG">FP per kamp</option><option value="TOTAL">Totale FP</option></select></div><div style={{overflowX:"auto",border:"1px solid #d7e0ea",borderRadius:12}}><table style={{width:"100%",borderCollapse:"collapse",minWidth:900,color:"#102033",fontSize:13}}><thead><tr>{["#","Spiller","Lag","Pos","K","FP","FP/K","S5","S5/K","S10/K","G","A","SOG","+/−","PIM"].map(h=><th key={h} style={{padding:8,textAlign:"left",background:"#eef3f8",whiteSpace:"nowrap"}}>{h}</th>)}</tr></thead><tbody>{shown.map((r,i)=><tr key={r.id}>{[i+1,r.name,r.team,r.position,r.games,r.totalFP,r.ppg,r.last5FP,r.last5PPG,r.last10PPG,r.goals,r.assists,r.shots,r.plusMinus>0?`+${r.plusMinus}`:r.plusMinus,r.pim].map((v,j)=><td key={j} style={{padding:8,borderBottom:"1px solid #e2e8f0",fontWeight:j===1||j===8?700:400,whiteSpace:j<3?"nowrap":"normal"}}>{v}</td>)}</tr>)}</tbody></table></div></section></main>
}
