"use client";
import { useEffect,useMemo,useState } from "react";
import { getSupabaseBrowserClient } from "../../../lib/supabase";
import { calculate19FantasyPoints } from "../../../lib/fantasy/scoring";
import "../fantasy.css";

type H={date:string;opponent:string;side:string;score:string;fp:number;goals:number;assists:number;shots:number;plusMinus:number;pim:number;saves:number;goalsAgainst:number;minutesPlayed:number;win:boolean;shutout:boolean};
type R={id:string;name:string;team:string;position:string;games:number;totalFP:number;ppg:number;last5FP:number;last5PPG:number;last10PPG:number;goals:number;assists:number;shots:number;plusMinus:number;pim:number;wins:number;shutouts:number;history:H[]};
type B={name:string;fp:number;g:number;a:number;pim:number};

const BENCHMARKS:B[]=[
{name:"Ludwig Wisten",fp:471,g:19,a:19,pim:6},{name:"Anton Öhman",fp:370,g:5,a:23,pim:22},{name:"Teemu Siironen",fp:356,g:8,a:28,pim:8},{name:"Lukas Fransson",fp:337,g:13,a:13,pim:37},{name:"Alexander Johansson",fp:267,g:0,a:0,pim:0},{name:"Ole Christian W Larssen",fp:172,g:3,a:9,pim:16},{name:"David Hallstrøm",fp:157,g:2,a:6,pim:8},{name:"Svein Petter Falk Larsen",fp:153,g:5,a:3,pim:16},{name:"Hugo Niemi",fp:146,g:1,a:5,pim:12},{name:"Daniel Sakshaug",fp:141,g:5,a:3,pim:18},
{name:"Linus Pettersson",fp:587,g:22,a:32,pim:40},{name:"Tobias Åhström",fp:498,g:16,a:28,pim:8},{name:"Theo Nordlund",fp:431,g:10,a:14,pim:14},{name:"Noah Andersson",fp:397,g:14,a:18,pim:36},{name:"Joona Partanen",fp:315,g:0,a:0,pim:0},{name:"Benjamin Byrkjeland",fp:292,g:8,a:18,pim:24},{name:"Tobias Tveter",fp:283,g:9,a:11,pim:8},{name:"Johan Ceder",fp:273,g:6,a:18,pim:10},{name:"Jeppe Meyer",fp:273,g:5,a:9,pim:22},{name:"Leonards Rimjans",fp:255,g:10,a:6,pim:28},
{name:"Christoffer Karlsen",fp:540,g:17,a:28,pim:22},{name:"Zach Andrusiak",fp:533,g:23,a:14,pim:38},{name:"Mathias Trettenes",fp:482,g:15,a:27,pim:12},{name:"Andreas Klavestad",fp:455,g:3,a:29,pim:32},{name:"Mathias Nørstebø",fp:449,g:3,a:29,pim:10},{name:"Cam Morrison",fp:436,g:18,a:13,pim:10},{name:"Andre Strandborg",fp:432,g:13,a:20,pim:8},{name:"Trenton Bliss",fp:403,g:13,a:17,pim:20},{name:"Patrick Elvsveen",fp:365,g:11,a:12,pim:28},{name:"Cliff Watson",fp:349,g:6,a:12,pim:26},
{name:"Jacob Berglund",fp:577,g:22,a:26,pim:12},{name:"Amil Krupic",fp:546,g:4,a:33,pim:28},{name:"Andreas Martinsen",fp:516,g:16,a:29,pim:46},{name:"Austin Cangelosi",fp:509,g:22,a:25,pim:26},{name:"Colin Campbell",fp:399,g:16,a:12,pim:12},{name:"Kenneth Pappalardo",fp:388,g:12,a:19,pim:8},{name:"Marcus Stensrud",fp:388,g:0,a:0,pim:0},{name:"Christian Bull",fp:387,g:7,a:12,pim:12},{name:"Martin Rønnild",fp:376,g:13,a:13,pim:44},{name:"Sander Hurrød",fp:368,g:3,a:20,pim:4},
{name:"Linus Hedman",fp:437,g:13,a:23,pim:18},{name:"Linus Westberg",fp:418,g:8,a:16,pim:30},{name:"Christian Blomqvist",fp:365,g:12,a:13,pim:26},{name:"William Magnusson",fp:361,g:10,a:20,pim:24},{name:"Sebastian Kaijser",fp:359,g:10,a:20,pim:12},{name:"Linus Rosdahl",fp:338,g:5,a:15,pim:24},{name:"Andreas Heier",fp:302,g:5,a:17,pim:16},{name:"Jere Huhtamaa",fp:297,g:0,a:0,pim:0},{name:"Sole Ryen",fp:283,g:9,a:11,pim:12},{name:"Håkon Imset Stormli",fp:256,g:5,a:13,pim:8},{name:"Mathias Schjerpen Arnkværn",fp:321,g:0,a:0,pim:0}
];
function nk(v:string){return String(v||"").toLocaleLowerCase("nb-NO").normalize("NFD").replace(/[\u0300-\u036f]/g,"").replace(/[^a-z0-9]+/g," ").trim()}
function tokens(v:string){return nk(v).split(/\s+/).filter(Boolean)}
function benchmarkFor(name:string){const exact=BENCHMARKS.find(b=>nk(b.name)===nk(name));if(exact)return exact;const t=tokens(name);if(t.length<2)return undefined;const matches=BENCHMARKS.filter(b=>{const q=tokens(b.name);return q[0]===t[0]&&q[q.length-1]===t[t.length-1]});return matches.length===1?matches[0]:undefined}
function r1(v:number){return Math.round(v*10)/10}

export default function DiagnosePage(){
 const[rows,setRows]=useState<R[]>([]),[selected,setSelected]=useState(""),[msg,setMsg]=useState("Laster …");
 useEffect(()=>{(async()=>{try{const s=getSupabaseBrowserClient();const{data}=await s!.auth.getSession();const a=data.session?.access_token;if(!a)throw new Error("Du må være logget inn som admin.");const res=await fetch("/api/fantasy-player-form?season=2025%2F26",{headers:{Authorization:`Bearer ${a}`}}),p=await res.json();if(!res.ok||!p.ok)throw new Error(p.error||"Kunne ikke hente formdata");const all:R[]=p.result.rows||[];const controls=all.filter(r=>benchmarkFor(r.name));setRows(controls);setSelected(controls[0]?.id||"");setMsg(`${controls.length} kontrollspillere`)}catch(e:any){setMsg(e?.message||"Ukjent feil")}})()},[]);
 const player=rows.find(r=>r.id===selected);const b=player?benchmarkFor(player.name):undefined;
 const diag=useMemo(()=>{if(!player)return null;const sums={participation:0,goals:0,assists:0,shots:0,plusMinus:0,pim:0,saves:0,goalsAgainst:0,shutout:0,win:0,total:0};for(const h of player.history){const x=calculate19FantasyPoints({position:player.position,didPlay:true,minutesPlayed:h.minutesPlayed,goals:h.goals,assists:h.assists,shots:h.shots,plusMinus:h.plusMinus,pim:h.pim,saves:h.saves,goalsAgainst:h.goalsAgainst,win:h.win,shutout:h.shutout});for(const k of Object.keys(sums) as (keyof typeof sums)[])sums[k]+=Number(x[k]||0)}return sums},[player]);
 const rowsBreak=diag?[
 ["Deltakelse",diag.participation],["Mål",diag.goals],["Assists",diag.assists],["Skudd",diag.shots],["+/−",diag.plusMinus],["PIM",diag.pim],["Redninger",diag.saves],["Baklengs",diag.goalsAgainst],["Shutout",diag.shutout],["Seier",diag.win]
 ]:[];
 return <main className="fantasy-shell"><section className="fantasy-hero"><div><p className="fantasy-kicker">STANG INN · ADMIN · FANTASY</p><h1>FP-diagnose</h1><p className="fantasy-lead">Bryter ned vår poengsum kategori for kategori mot 19Fantasy-fasiten.</p></div><a className="pill" href="/fantasy/form" style={{textDecoration:"none"}}>← Ranking</a></section><section className="fantasy-card"><p className="card-copy">{msg}</p><select value={selected} onChange={e=>setSelected(e.target.value)} style={{padding:10,borderRadius:10,minWidth:280}}>{rows.map(r=><option key={r.id} value={r.id}>{r.name} · {r.team}</option>)}</select>{player&&b&&diag&&<><div style={{marginTop:14,padding:12,border:"1px solid #cbd8e5",borderRadius:12,background:"white"}}><h2 style={{marginTop:0}}>{player.name}</h2><div style={{display:"flex",gap:16,flexWrap:"wrap"}}><span>Vår FP: <b>{r1(diag.total)}</b></span><span>19Fantasy: <b>{b.fp}</b></span><span style={{color:Math.abs(diag.total-b.fp)<.001?"#16794b":"#a23b2a",fontWeight:800}}>Avvik: {r1(diag.total-b.fp)>0?"+":""}{r1(diag.total-b.fp)}</span></div><div style={{marginTop:8,fontSize:13}}>Råstatistikk: G <b>{player.goals}/{b.g}</b> · A <b>{player.assists}/{b.a}</b> · PIM <b>{player.pim}/{b.pim}</b> <span style={{color:"#607086"}}>(Stang Inn / 19Fantasy)</span></div></div><div style={{marginTop:14,overflowX:"auto",border:"1px solid #d7e0ea",borderRadius:12}}><table style={{width:"100%",borderCollapse:"collapse",minWidth:520}}><thead><tr><th style={{padding:8,textAlign:"left",background:"#eef3f8"}}>Kategori</th><th style={{padding:8,textAlign:"left",background:"#eef3f8"}}>Våre FP</th></tr></thead><tbody>{rowsBreak.map(([label,value])=><tr key={String(label)}><td style={{padding:8,borderBottom:"1px solid #e2e8f0"}}>{label}</td><td style={{padding:8,borderBottom:"1px solid #e2e8f0",fontWeight:700}}>{r1(Number(value))}</td></tr>)}<tr><td style={{padding:8,fontWeight:800}}>SUM</td><td style={{padding:8,fontWeight:800}}>{r1(diag.total)}</td></tr></tbody></table></div><div style={{marginTop:14,overflowX:"auto"}}><table style={{width:"100%",borderCollapse:"collapse",minWidth:950,fontSize:12}}><thead><tr>{["Dato","Motstander","H/B","Resultat","G","A","SOG","+/−","PIM","SV","GA","W","SO","FP"].map(h=><th key={h} style={{padding:6,textAlign:"left",background:"#eef3f8"}}>{h}</th>)}</tr></thead><tbody>{player.history.map((h,i)=><tr key={i}>{[h.date?new Date(h.date).toLocaleDateString("nb-NO"):"—",h.opponent,h.side,h.score,h.goals,h.assists,h.shots,h.plusMinus,h.pim,player.position==="G"?h.saves:"—",player.position==="G"?h.goalsAgainst:"—",player.position==="G"?(h.win?"✓":"—"):"—",player.position==="G"?(h.shutout?"✓":"—"):"—",h.fp].map((v,j)=><td key={j} style={{padding:6,borderBottom:"1px solid #e2e8f0",fontWeight:j===13?700:400}}>{v}</td>)}</tr>)}</tbody></table></div></>}</section></main>}
