"use client";
import {useEffect,useState} from "react";
import {getSupabaseBrowserClient} from "../../lib/supabase";
const SEASON="2026/27";
type League={league_id:string;league_name:string;invite_code:string;my_role:string;member_count:number;created_at:string};
export default function Page(){
 const[leagues,setLeagues]=useState<League[]>([]),[name,setName]=useState(""),[code,setCode]=useState(""),[busy,setBusy]=useState(false),[message,setMessage]=useState("");
 async function load(){const sb=getSupabaseBrowserClient();if(!sb)return;const{data,error}=await sb.rpc("get_my_hockeytips_private_leagues_v1",{p_season:SEASON});if(error)setMessage(error.message);else setLeagues((data||[]) as League[])}
 useEffect(()=>{load()},[]);
 async function createLeague(){setBusy(true);const sb=getSupabaseBrowserClient();if(!sb)return;const{data,error}=await sb.rpc("create_hockeytips_private_league_v1",{p_season:SEASON,p_name:name.trim()});setBusy(false);if(error)setMessage(error.message);else window.location.assign(`/leagues/${data}`)}
 async function joinLeague(){setBusy(true);const sb=getSupabaseBrowserClient();if(!sb)return;const{data,error}=await sb.rpc("join_hockeytips_private_league_v1",{p_season:SEASON,p_invite_code:code});setBusy(false);if(error)setMessage(error.message);else window.location.assign(`/leagues/${data}`)}
 return <main className="appShell"><header className="topbar"><a className="brand brandButton" href="/" style={{textDecoration:"none"}}><div className="brandMark">🏒</div><div><p className="eyebrow">HOCKEYTIPSET · 2026/27</p><h1>Private ligaer</h1></div></a><a className="textButton" href="/">Til Hockeytipset →</a></header><section className="pageStack" style={{marginTop:24}}><div className="pageHeading"><div><p className="eyebrow">VENNEGJENGEN</p><h2>🤝 Mine ligaer</h2><p className="muted">Opprett en liga eller bli med via invitasjonskode.</p></div></div>{message&&<article className="panel"><p>{message}</p></article>}<section className="contentGrid"><article className="panel"><h3>Opprett liga</h3><input value={name} onChange={e=>setName(e.target.value)} placeholder="Lig navn"/><button className="primaryButton" disabled={busy||name.trim().length<2} onClick={createLeague}>Opprett liga</button></article><article className="panel"><h3>Bli med</h3><input value={code} onChange={e=>setCode(e.target.value.toUpperCase())} placeholder="Invitasjonskode"/><button className="primaryButton" disabled={busy||!code.trim()} onClick={joinLeague}>Bli med</button></article></section><article className="panel standings"><div className="panelHeading"><h3>Dine ligaer</h3></div>{leagues.map(l=><a key={l.league_id} href={`/leagues/${l.league_id}`} className="tableRow" style={{gridTemplateColumns:"1fr 100px 90px",textDecoration:"none",color:"inherit"}}><span><b>{l.league_name}</b><small>{l.my_role==="owner"?"Eier":"Medlem"} · {l.invite_code}</small></span><span>{l.member_count} medlem</span><span className="points">Åpne →</span></a>)}</article></section></main>;
}
