"use client";

import { useEffect, useMemo, useState } from "react";
import { getSupabaseBrowserClient } from "../../lib/supabase";

type Notice = { id: number; type: string; title: string; message: string; link: string | null; created_at: string; expires_at: string | null };
type ReadRow = { notification_id: number };
type Match = { id: number; home_team: string; away_team: string; match_time: string | null; home_score:number|null; away_score:number|null; finished: boolean; round: number | null };
type Tip = { player_id: string; match_id: number; points: number | null };
type AutoNotice={key:string;icon:string;title:string;message:string;link:string;time:number;kind:"live"|"result"|"warning"};

function icon(type: string) { if(type==="score")return"🎯";if(type==="warning")return"⏰";if(type==="round")return"🏒";if(type==="admin")return"📢";return"🔔"; }

export default function NotificationsPage() {
 const [uid,setUid]=useState<string|null>(null),[notices,setNotices]=useState<Notice[]>([]),[reads,setReads]=useState<ReadRow[]>([]),[matches,setMatches]=useState<Match[]>([]),[tips,setTips]=useState<Tip[]>([]),[loading,setLoading]=useState(true),[tick,setTick]=useState(Date.now());
 async function load(){const s=getSupabaseBrowserClient();if(!s){setLoading(false);return}const {data:session}=await s.auth.getSession();const userId=session.session?.user.id||null;setUid(userId);if(!userId){setLoading(false);return}const[n,r,m,t]=await Promise.all([s.from("notifications").select("id,type,title,message,link,created_at,expires_at").order("created_at",{ascending:false}),s.from("notification_reads").select("notification_id").eq("user_id",userId),s.from("matches").select("id,home_team,away_team,match_time,home_score,away_score,finished,round").order("match_time"),s.from("tips").select("player_id,match_id,points").eq("player_id",userId)]);setNotices((n.data||[])as Notice[]);setReads((r.data||[])as ReadRow[]);setMatches((m.data||[])as Match[]);setTips((t.data||[])as Tip[]);setTick(Date.now());setLoading(false)}
 useEffect(()=>{load();const timer=window.setInterval(load,30000);return()=>window.clearInterval(timer)},[]);
 const readIds=useMemo(()=>new Set(reads.map(r=>r.notification_id)),[reads]);
 const activeNotices=useMemo(()=>notices.filter(n=>!n.expires_at||new Date(n.expires_at).getTime()>tick),[notices,tick]);
 const tipped=useMemo(()=>new Set(tips.map(t=>t.match_id)),[tips]);
 const missing=useMemo(()=>matches.filter(m=>!m.finished&&!!m.match_time&&new Date(m.match_time).getTime()>tick&&!tipped.has(m.id)),[matches,tipped,tick]);
 const nextRound=useMemo(()=>missing.map(m=>m.round).filter((r):r is number=>r!==null).sort((a,b)=>a-b)[0]??null,[missing]);
 const recentPoints=useMemo(()=>tips.filter(t=>Number(t.points??0)>0).slice(-5).reverse(),[tips]);
 const automatic=useMemo<AutoNotice[]>(()=>{const out:AutoNotice[]=[];for(const m of matches){if(!m.match_time)continue;const start=new Date(m.match_time).getTime();const name=`${m.home_team} – ${m.away_team}`;if(m.finished){out.push({key:`result-${m.id}`,icon:"🏁",title:"Kampen er ferdig",message:`${name}: ${m.home_score??"–"}–${m.away_score??"–"}. Se hvordan tipsene slo ut.`,link:`/match/${m.id}`,time:start+3*60*60*1000,kind:"result"});continue}if(start<=tick&&tick-start<4*60*60*1000){out.push({key:`live-${m.id}`,icon:"🟢",title:"Kampen har startet",message:`${name} er i gang. Følg live-senteret og tippekonkurransen.`,link:"/live",time:start,kind:"live"})}else if(start>tick&&!tipped.has(m.id)&&start-tick<=24*60*60*1000){const hrs=Math.max(1,Math.ceil((start-tick)/3600000));out.push({key:`warning-${m.id}`,icon:"⏰",title:"Tips mangler",message:`Du har ikke tippet ${name}. Kampstart om ca. ${hrs} t.`,link:`/match/${m.id}`,time:start-24*60*60*1000,kind:"warning"})}}return out.sort((a,b)=>b.time-a.time).slice(0,12)},[matches,tipped,tick]);
 async function markRead(id:number){const s=getSupabaseBrowserClient();if(!s||!uid||readIds.has(id))return;await s.from("notification_reads").upsert({notification_id:id,user_id:uid},{onConflict:"notification_id,user_id"});await load()}
 async function markAllRead(){const s=getSupabaseBrowserClient();if(!s||!uid)return;const rows=activeNotices.filter(n=>!readIds.has(n.id)).map(n=>({notification_id:n.id,user_id:uid}));if(rows.length)await s.from("notification_reads").upsert(rows,{onConflict:"notification_id,user_id"});await load()}
 if(loading)return <main className="appShell"><p className="muted">Laster varsler …</p></main>;
 return <main className="appShell"><header className="topbar"><a href="/" className="brand brandButton" style={{textDecoration:"none"}}><div className="brandMark">🔔</div><div><p className="eyebrow">Stang Inn</p><h1>Varsler</h1></div></a><a href="/" className="textButton">Til appen →</a></header><section className="pageStack" style={{marginTop:24}}>
 <div className="pageHeading"><div><p className="eyebrow">Varslingssenter</p><h2>Det du bør få med deg</h2></div><button className="compactButton" onClick={markAllRead}>Marker meldinger som lest</button></div>
 {missing.length>0&&<article className="panel" style={{border:"1px solid rgba(245,196,81,.45)"}}><div className="panelHeading"><div><p className="eyebrow">⏰ Handling kreves</p><h3>Du mangler {missing.length} tips</h3></div><a className="compactButton" href="/tips">Lever tips</a></div><p className="muted">{nextRound?`Neste aktuelle runde er runde ${nextRound}. `:""}Tipsene låses ved kampstart.</p></article>}
 {automatic.length>0&&<article className="panel"><div className="panelHeading"><div><p className="eyebrow">⚡ Automatisk</p><h3>Kampvarsler</h3></div><span className="statusPill">30 sek live</span></div><div className="pageStack" style={{gap:8}}>{automatic.map(n=><a key={n.key} href={n.link} style={{padding:14,borderRadius:14,border:n.kind==="live"?"1px solid rgba(84,222,168,.35)":"1px solid var(--line)",background:n.kind==="live"?"rgba(84,222,168,.07)":"rgba(85,184,255,.045)",textDecoration:"none",color:"inherit"}}><strong>{n.icon} {n.title}</strong><p className="muted" style={{margin:"6px 0 0"}}>{n.message}</p></a>)}</div></article>}
 {recentPoints.length>0&&<article className="panel"><div className="panelHeading"><div><p className="eyebrow">🎯 Siste poeng</p><h3>Nylige treff</h3></div></div><div className="simpleList">{recentPoints.map(t=>{const m=matches.find(x=>x.id===t.match_id);return <div key={t.match_id}><span>{m?`${m.home_team} – ${m.away_team}`:`Kamp ${t.match_id}`}</span><strong>+{t.points} p</strong></div>})}</div></article>}
 <article className="panel"><div className="panelHeading"><div><p className="eyebrow">Innboks</p><h3>Meldinger</h3></div><span className="statusPill">{activeNotices.filter(n=>!readIds.has(n.id)).length} ulest</span></div><div className="pageStack" style={{gap:8}}>{activeNotices.map(n=><div key={n.id} onClick={()=>markRead(n.id)} style={{padding:14,borderRadius:14,border:"1px solid var(--line)",background:readIds.has(n.id)?"#0a1729":"rgba(85,184,255,.09)",cursor:"pointer"}}><div style={{display:"flex",justifyContent:"space-between",gap:12}}><strong>{icon(n.type)} {n.title}</strong>{!readIds.has(n.id)&&<span className="statusPill">Ny</span>}</div><p className="muted" style={{margin:"6px 0"}}>{n.message}</p><small className="muted">{new Date(n.created_at).toLocaleString("no-NO")}</small>{n.link&&<div style={{marginTop:8}}><a href={n.link} className="textButton">Åpne →</a></div>}</div>)}</div>{activeNotices.length===0&&<p className="muted">Ingen meldinger ennå.</p>}</article>
 </section></main>
}
