"use client";

import { useCallback, useEffect, useMemo, useState } from "react";
import { getSupabaseBrowserClient } from "../../lib/supabase";

type Player={id:string;display_name:string};
type Match={id:number;home_team:string;away_team:string;match_time:string|null;home_score:number|null;away_score:number|null;finished:boolean;round:number|null};
type Tip={id:number;player_id:string;match_id:number;home_tip:number;away_tip:number;points:number|null};
type Row=Player&{points:number;confirmedPoints:number;livePoints:number;exact:number;correctOutcome:number;tipped:number};
const validFinished=(m:Match)=>m.finished&&m.home_score!==null&&m.away_score!==null;
const started=(m:Match)=>m.finished||!!m.match_time&&Date.now()>=new Date(m.match_time).getTime();
const live=(m:Match)=>{if(m.finished||!m.match_time)return false;const d=Date.now()-new Date(m.match_time).getTime();return d>=0&&d<=4*60*60*1000};
const outcome=(h:number,a:number)=>h>a?"H":h<a?"A":"D";
const liveTipPoints=(m:Match,t?:Tip)=>{if(!t||m.home_score===null||m.away_score===null)return 0;if(t.home_tip===m.home_score&&t.away_tip===m.away_score)return 5;if(outcome(t.home_tip,t.away_tip)===outcome(m.home_score,m.away_score))return 3;return 0};
const fmt=(v:string|null)=>v?new Date(v).toLocaleString("no-NO",{weekday:"short",day:"2-digit",month:"2-digit",hour:"2-digit",minute:"2-digit"}):"Tidspunkt ikke satt";
const short=(n:string)=>n.replace(/Elitehockeyligaen|Ishockeyklubb|Ishockey|Hockey|\bIL\b|\bIK\b/gi,"").replace(/\s{2,}/g," ").trim();
const range=(ms:Match[])=>{const d=ms.map(m=>m.match_time).filter((x):x is string=>!!x).map(x=>new Date(x)).sort((a,b)=>a.getTime()-b.getTime());if(!d.length)return"Dato ikke satt";const a=d[0],b=d.at(-1)!;if(a.toDateString()===b.toDateString())return a.toLocaleDateString("no-NO",{weekday:"long",day:"numeric",month:"long",year:"numeric"});return `${a.toLocaleDateString("no-NO",{day:"numeric",month:"short"})}–${b.toLocaleDateString("no-NO",{day:"numeric",month:"short",year:"numeric"})}`};
const until=(v:string|null)=>{if(!v)return"–";const ms=new Date(v).getTime()-Date.now();if(ms<=0)return"I gang";const mins=Math.floor(ms/60000),d=Math.floor(mins/1440),h=Math.floor(mins%1440/60);return d?`${d} d ${h} t`:h?`${h} t ${mins%60} min`:`${Math.max(1,mins)} min`};

export default function RoundPage(){
 const[players,setPlayers]=useState<Player[]>([]),[matches,setMatches]=useState<Match[]>([]),[tips,setTips]=useState<Tip[]>([]);const[meId,setMeId]=useState<string|null>(null),[selectedRound,setSelectedRound]=useState<number|null>(null),[loading,setLoading]=useState(true),[updatedAt,setUpdatedAt]=useState<Date|null>(null);
 const load=useCallback(async()=>{const s=getSupabaseBrowserClient();if(!s){setLoading(false);return}const{data:session}=await s.auth.getSession();setMeId(session.session?.user.id||null);const[p,m,t]=await Promise.all([s.from("players").select("id,display_name").order("created_at"),s.from("matches").select("id,home_team,away_team,match_time,home_score,away_score,finished,round").order("match_time"),s.from("tips").select("id,player_id,match_id,home_tip,away_tip,points")]);setPlayers((p.data||[])as Player[]);setMatches((m.data||[])as Match[]);setTips((t.data||[])as Tip[]);setUpdatedAt(new Date());setLoading(false)},[]);
 useEffect(()=>{load();const t=window.setInterval(load,30000);return()=>window.clearInterval(t)},[load]);
 const rounds=useMemo(()=>[...new Set(matches.map(m=>m.round).filter((r):r is number=>r!==null))].sort((a,b)=>a-b),[matches]);
 useEffect(()=>{if(selectedRound!==null||!rounds.length)return;const active=rounds.find(r=>matches.filter(m=>m.round===r).some(live));const next=rounds.find(r=>matches.some(m=>m.round===r&&!validFinished(m)&&(!m.match_time||new Date(m.match_time).getTime()>=Date.now())));setSelectedRound(active??next??rounds[0])},[rounds,matches,selectedRound]);
 const roundMatches=useMemo(()=>matches.filter(m=>m.round===selectedRound).sort((a,b)=>(a.match_time||"").localeCompare(b.match_time||"")),[matches,selectedRound]);const ids=useMemo(()=>new Set(roundMatches.map(m=>m.id)),[roundMatches]);
 const rows=useMemo<Row[]>(()=>players.map(p=>{const pt=tips.filter(t=>t.player_id===p.id&&ids.has(t.match_id));let confirmedPoints=0,livePoints=0,exact=0,correctOutcome=0;for(const m of roundMatches){const tip=pt.find(t=>t.match_id===m.id);if(!tip)continue;if(validFinished(m)){const pts=Number(tip.points??liveTipPoints(m,tip));confirmedPoints+=pts;if(pts===5)exact++;if(pts===3)correctOutcome++;}else if(live(m)&&m.home_score!==null&&m.away_score!==null){const pts=liveTipPoints(m,tip);livePoints+=pts;if(pts===5)exact++;if(pts===3)correctOutcome++;}}return{...p,points:confirmedPoints+livePoints,confirmedPoints,livePoints,exact,correctOutcome,tipped:pt.length}}).sort((a,b)=>b.points-a.points||b.exact-a.exact||b.correctOutcome-a.correctOutcome||a.display_name.localeCompare(b.display_name,"no")),[players,tips,ids,roundMatches]);
 const completed=roundMatches.filter(validFinished).length,liveCount=roundMatches.filter(live).length,progress=roundMatches.length?Math.round(completed/roundMatches.length*100):0,finished=roundMatches.length>0&&completed===roundMatches.length;const first=roundMatches.map(m=>m.match_time).filter((x):x is string=>!!x).sort()[0]||null;const completeTips=roundMatches.length?rows.filter(r=>r.tipped===roundMatches.length).length:0;const leader=rows[0];
 if(loading)return <main className="appShell"><p className="muted">Laster runden …</p></main>;
 return <main className="appShell"><header className="topbar"><a href="/" className="brand brandButton" style={{textDecoration:"none"}}><div className="brandMark">🏒</div><div><p className="eyebrow">EHL 2026/27</p><h1>Runde</h1></div></a></header><section className="pageStack" style={{marginTop:20}}>
  <article className="heroCard"><div><p className="eyebrow">Runde-event</p><h2>{selectedRound!==null?`Runde ${selectedRound}`:"Velg runde"}</h2><p className="muted">{range(roundMatches)} · {finished?"Runden er ferdig":liveCount?`${liveCount} kamp${liveCount===1?"":"er"} live nå`:`Første kamp om ${until(first)}`}</p></div><div className="countdown"><strong>{finished?"100%":`${progress}%`}</strong><span>{completed}/{roundMatches.length} ferdig</span></div></article>
  <div className="roundProgress"><span style={{width:`${progress}%`}}/></div><div className="roundMetaGrid"><div><span>Kamper</span><strong>{roundMatches.length}</strong></div><div><span>Alle tips levert</span><strong>{completeTips}/{players.length}</strong></div><div><span>Oppdatert</span><strong>{updatedAt?.toLocaleTimeString("no-NO",{hour:"2-digit",minute:"2-digit"})||"–"}</strong></div></div>
  <select className="roundSelect" value={selectedRound??""} onChange={e=>setSelectedRound(Number(e.target.value))}>{rounds.map(r=><option key={r} value={r}>Runde {r}</option>)}</select>
  {leader&&<article className="quoteCard"><span>{finished?"🏆 RUNDEVINNER":liveCount?"🟢 LIVE-RUNDELEDER":"🏆 RUNDELEDER"}</span><p><strong>{leader.display_name}</strong> {finished?"vant":"leder"} med {leader.points} {liveCount&&!finished?"løpende":"bekreftede"} poeng.</p></article>}
  <article className="panel standings"><div className="panelHeading"><div><p className="eyebrow">Rundetabell</p><h3>{liveCount&&!finished?"Løpende poeng denne runden":"Bekreftede poeng denne runden"}</h3></div>{liveCount>0&&!finished&&<span className="statusPill">🟢 Live-estimat</span>}</div><div className="tableHead" style={{gridTemplateColumns:"42px 1fr 70px 70px"}}><span>#</span><span>Spiller</span><span>Eksakt</span><span>Poeng</span></div>{rows.map((r,i)=><div className="tableRow" style={{gridTemplateColumns:"42px 1fr 70px 70px"}} key={r.id}><span className="rank">{i===0?"🥇":i===1?"🥈":i===2?"🥉":i+1}</span><span><a href={`/player/${r.id}`} style={{color:"inherit",textDecoration:"none"}}><b>{r.display_name}{r.id===meId?" · deg":""}</b><small>{r.tipped}/{roundMatches.length} tips{r.livePoints>0?` · ${r.livePoints} live p`:""}</small></a></span><span>{r.exact}</span><span className="points">{r.points}</span></div>)}</article>
  <section className="roundCarouselSection"><div className="panelHeading"><div><p className="eyebrow">Kamper i runden</p><h3>Alle kampene</h3></div><strong className="roundCounter">{roundMatches.length} kamper</strong></div><div className="roundMatchList">{roundMatches.map(m=>{const done=validFinished(m),isLive=live(m),mt=tips.filter(t=>t.match_id===m.id),visible=started(m);const pointRows=players.map(p=>{const tip=mt.find(x=>x.player_id===p.id);const pts=done?Number(tip?.points??liveTipPoints(m,tip)):isLive?liveTipPoints(m,tip):0;return{player:p,tip,pts}}).sort((a,b)=>b.pts-a.pts||a.player.display_name.localeCompare(b.player.display_name,"no"));const exactCount=(done||isLive)&&m.home_score!==null&&m.away_score!==null?pointRows.filter(x=>x.pts===5).length:0,outcomeCount=(done||isLive)&&m.home_score!==null&&m.away_score!==null?pointRows.filter(x=>x.pts===3).length:0;return <article className={`roundSlide ${isLive?"isLive":""}`} key={m.id}><div className="roundSlideStatus">{done?`🏁 Slutt ${m.home_score}–${m.away_score}`:isLive?`🟢 LIVE ${m.home_score??""}${m.home_score!==null?"–":""}${m.away_score??""}`:started(m)?"🟡 Avventer sluttstatus":`🔵 ${fmt(m.match_time)}`}</div><div className="roundTeams"><div><span>HJEMME</span><strong>{short(m.home_team)}</strong></div><b>VS</b><div><span>BORTE</span><strong>{short(m.away_team)}</strong></div></div>{(done||isLive)&&m.home_score!==null&&m.away_score!==null&&<div className="matchPointSummary"><span>🎯 {exactCount} eksakte</span><span>✓ {outcomeCount} riktige utfall</span><span>0 p: {Math.max(0,mt.length-exactCount-outcomeCount)}</span>{isLive&&!done&&<span>Live-estimat</span>}</div>}<div className="roundSlideTips">{!visible?<div className="lockedTips">🔒 Alles tips vises ved kampstart</div>:pointRows.map(({player,tip,pts})=>{const cls=done||isLive?(pts===5?"pointExact":pts===3?"pointCorrect":"pointMiss"):"";return <div key={player.id} className={cls}><span>{(done||isLive)&&pts===5?"🎯 ":(done||isLive)&&pts===3?"✓ ":""}{player.display_name}{player.id===meId?" · deg":""}</span><strong>{tip?`${tip.home_tip}–${tip.away_tip}${done?` · +${pts} p`:isLive?` · ${pts} live p`:""}`:"Ikke levert"}</strong></div>})}</div><a className="primaryButton" href={`/match/${m.id}`}>Åpne kampside</a></article>})}</div></section>
 </section></main>
}
