"use client";

import {useMemo,useState} from "react";
import {getSupabaseBrowserClient} from "../../../../lib/supabase";
import {HISTORICAL_PRICES_2025} from "../../../../lib/fantasy/historical-prices-2025";
import {preEhlBacktestHistoryFor} from "../../../../lib/fantasy/import-backtest-history-2025";
import {importEstimateV43,type V43Position} from "../../../../lib/fantasy/import-pricing-v4-3";
import type {ImportHistory} from "../../../../lib/fantasy/import-history-2026";
import "../../fantasy.css";

const S24="2024/25",S25="2025/26",VALID=new Set(["C","W","D","G"]);
const norm=(v:any)=>String(v??"").toLocaleLowerCase("nb-NO").normalize("NFD").replace(/[\u0300-\u036f]/g,"").replace(/ø/g,"o").replace(/æ/g,"ae").replace(/[^a-z0-9]+/g," ").trim();
const natural=(s:string)=>{const[last,...r]=String(s||"").split(",");return r.length?`${r.join(",").trim()} ${last.trim()}`:String(s||"")};
const arr=(s:string)=>norm(s).split(" ").filter(Boolean).filter(x=>x!=="jr"&&x!=="junior"),tok=(s:string)=>new Set(arr(s));
function score(a:string,b:string){if(norm(a)===norm(natural(b)))return 1000;const A=tok(a),B=tok(natural(b));let c=0;for(const x of A)if(B.has(x))c++;const mn=Math.min(A.size,B.size),mx=Math.max(A.size,B.size);return c===mn&&mn>=2?800+c*10-mn*Math.abs(mx-mn):c>=2?c*100-Math.abs(A.size-B.size)*10:0}
function best(name:string,src:any[]){let row:any=null,bs=0;for(const x of src){const s=score(name,x.name??x[0]);if(s>bs){bs=s;row=x}}return bs>=800?row:null}
async function auth(){const s=getSupabaseBrowserClient(),{data}=await s!.auth.getSession();if(!data.session?.access_token)throw new Error("Logg inn som admin");return data.session.access_token}
function canonTeam(v:any){const s=norm(v);if(s.includes("storhamar"))return"Storhamar";if(s.includes("stavanger")||s.includes("oilers"))return"Stavanger";if(s.includes("valerenga"))return"Vålerenga";if(s.includes("frisk"))return"Frisk Asker";if(s.includes("sparta"))return"Sparta";if(s.includes("narvik"))return"Narvik";if(s.includes("stjernen"))return"Stjernen";if(s.includes("lillehammer"))return"Lillehammer";if(s.includes("ringerike"))return"Ringerike";if(s.includes("nidaros"))return"Nidaros";return String(v||"").trim()}
const avg=(xs:number[])=>xs.length?xs.reduce((a,b)=>a+b,0)/xs.length:0;
const mae=(xs:number[])=>xs.length?avg(xs.map(Math.abs)):0;
const rmse=(xs:number[])=>xs.length?Math.sqrt(avg(xs.map(x=>x*x))):0;
const clamp=(x:number,lo:number,hi:number)=>Math.max(lo,Math.min(hi,x));
const pg=(p:string)=>p==="G"?"G":p==="D"?"D":"F";

type R={name:string;team:string;pos:string;start:number;track:string;league:string;games:number;ppg:number|null;sv:number|null;gaa:number|null};
type M=R&{v43:number;loo:number;baseline:number;e43:number;eloo:number;ebase:number;cohort:string;n:number;bias:number};
function hist(r:R):ImportHistory|null{if(r.pos==="G"){if(r.sv==null||r.gaa==null)return null;return{kind:"goalie",season:"2025/26",previousTeam:"historical",league:r.league,games:r.games,savePct:r.sv,gaa:r.gaa,source:"EliteProspects"}}if(r.ppg==null)return null;return{kind:"skater",season:"2025/26",previousTeam:"historical",league:r.league,games:r.games,goals:0,assists:r.ppg*r.games,points:r.ppg*r.games,source:"EliteProspects"}}
function cohortFor(r:R,all:R[]){const others=all.filter(x=>x.name!==r.name&&pg(x.pos)===pg(r.pos));const exact=others.filter(x=>x.track===r.track&&x.league===r.league);if(exact.length>=2)return{rows:exact,label:`${r.track} · ${r.league} · ${pg(r.pos)}`};const track=others.filter(x=>x.track===r.track);if(track.length>=2)return{rows:track,label:`${r.track} · ${pg(r.pos)}`};return{rows:others,label:`posisjonsfallback · ${pg(r.pos)}`}}
function looPrice(r:R,all:R[],v43:number){const c=cohortFor(r,all),base=avg(c.rows.map(x=>x.start));let shift=0;if(r.pos!=="G"&&r.ppg!=null){const pp=c.rows.filter(x=>x.ppg!=null).map(x=>Number(x.ppg));if(pp.length){const center=avg(pp);const scale=r.track==="norway2-transition"?1.2:r.track==="junior/talent"?0.5:1.0;shift=clamp((r.ppg-center)*scale,-1.0,1.0)}}else if(r.pos==="G"&&r.sv!=null){const ss=c.rows.filter(x=>x.sv!=null).map(x=>Number(x.sv));if(ss.length)shift=clamp((r.sv-avg(ss))*100*0.18,-0.8,0.8)}const raw=base+shift;const w=clamp((c.rows.length/6)*(r.pos==="G"?0.16:r.track==="junior/talent"?0.18:r.track==="norway2-transition"?0.35:0.30),0.06,0.35);const d=clamp((raw-v43)*w,-1.5,1.5);return{price:v43+d,n:c.rows.length,label:c.label}}

export default function Page(){const[busy,setBusy]=useState(false),[msg,setMsg]=useState("Klar for V4.5.9"),[models,setModels]=useState<M[]>([]);
async function run(){setBusy(true);try{const t=await auth();const[a,b]=await Promise.all([fetch(`/api/fantasy-player-form?season=${encodeURIComponent(S24)}`,{headers:{Authorization:`Bearer ${t}`}}),fetch(`/api/fantasy-player-form?season=${encodeURIComponent(S25)}`,{headers:{Authorization:`Bearer ${t}`}})]);const p24=await a.json(),p25=await b.json();if(!a.ok||!p24.ok||!b.ok||!p25.ok)throw new Error("Kunne ikke hente historiske data");const old=p24.result?.rows||[],cur=p25.result?.rows||[],rows:R[]=[];for(const p of cur){if(Number(p.games||0)<10||!VALID.has(String(p.position||"")))continue;const prev=best(String(p.name),old);if(prev&&Number(prev.games||0)>=3)continue;const pr=best(String(p.name),HISTORICAL_PRICES_2025 as any[]),h=preEhlBacktestHistoryFor(String(p.name));if(!pr||!h)continue;rows.push({name:String(p.name),team:String(p.team||pr?.[1]||""),pos:String(p.position),start:Number(pr[2])/1e6,track:h.track,league:h.league,games:h.games,ppg:h.points!=null?h.points/h.games:null,sv:h.savePct??null,gaa:h.gaa??null})}const out:M[]=[];for(const r of rows){const h=hist(r);if(!h)continue;const v=importEstimateV43(h,r.pos as V43Position,canonTeam(r.team),r.name);if(!v)continue;const loo=looPrice(r,rows,v.raw);const posPeers=rows.filter(x=>x.name!==r.name&&pg(x.pos)===pg(r.pos));const baseline=avg(posPeers.map(x=>x.start));out.push({...r,v43:v.raw,loo:loo.price,baseline,e43:v.raw-r.start,eloo:loo.price-r.start,ebase:baseline-r.start,cohort:loo.label,n:loo.n,bias:loo.price-r.start})}setModels(out);setMsg(`Ferdig · ${out.length} leave-one-out-observasjoner`)}catch(e:any){setMsg(`Feil: ${e.message||e}`)}finally{setBusy(false)}}
const metrics=useMemo(()=>({n:models.length,mae43:mae(models.map(x=>x.e43)),rmse43:rmse(models.map(x=>x.e43)),maeL:mae(models.map(x=>x.eloo)),rmseL:rmse(models.map(x=>x.eloo)),maeB:mae(models.map(x=>x.ebase)),rmseB:rmse(models.map(x=>x.ebase)),bias43:avg(models.map(x=>x.e43)),biasL:avg(models.map(x=>x.eloo))}),[models]);
const groups=useMemo(()=>{const keys=["F","D","G","senior-import","norway2-transition","junior/talent"];return keys.map(k=>{const rs=models.filter(x=>k.length===1?pg(x.pos)===k:x.track===k);return{k,n:rs.length,m43:mae(rs.map(x=>x.e43)),ml:mae(rs.map(x=>x.eloo)),b:avg(rs.map(x=>x.eloo))}}).filter(x=>x.n)},[models]);
const worst=useMemo(()=>[...models].sort((a,b)=>Math.abs(b.loo-b.v43)-Math.abs(a.loo-a.v43)).slice(0,10),[models]);
return <main className="fantasy-page"><section className="fantasy-card"><h1>V4.5.9 · Leave-one-out validering</h1><p>Hver historisk spiller fjernes fra kontrollgruppen før den empiriske prioren beregnes. Dette reduserer datalekkasje og tester om forbedringen i V4.5.8 faktisk generaliserer.</p><button onClick={run} disabled={busy}>{busy?"Tester…":"Kjør V4.5.9 leave-one-out"}</button><p><strong>{msg}</strong></p></section>{models.length>0&&<><section className="fantasy-card"><h2>Hovedresultat</h2><table><thead><tr><th>Modell</th><th>N</th><th>MAE</th><th>RMSE</th><th>Bias</th></tr></thead><tbody><tr><td>V4.3.3</td><td>{metrics.n}</td><td>{metrics.mae43.toFixed(2)}m</td><td>{metrics.rmse43.toFixed(2)}m</td><td>{metrics.bias43>=0?"+":""}{metrics.bias43.toFixed(2)}m</td></tr><tr><td><strong>V4.5.9 LOO</strong></td><td>{metrics.n}</td><td><strong>{metrics.maeL.toFixed(2)}m</strong></td><td><strong>{metrics.rmseL.toFixed(2)}m</strong></td><td>{metrics.biasL>=0?"+":""}{metrics.biasL.toFixed(2)}m</td></tr><tr><td>Enkel posisjonsbaseline</td><td>{metrics.n}</td><td>{metrics.maeB.toFixed(2)}m</td><td>{metrics.rmseB.toFixed(2)}m</td><td>—</td></tr></tbody></table><p>MAE-endring mot V4.3.3: <strong>{(metrics.maeL-metrics.mae43).toFixed(2)}m</strong> · RMSE-endring: <strong>{(metrics.rmseL-metrics.rmse43).toFixed(2)}m</strong>.</p></section><section className="fantasy-card"><h2>MAE per posisjon og track</h2><table><thead><tr><th>Gruppe</th><th>N</th><th>V4.3.3 MAE</th><th>V4.5.9 MAE</th><th>LOO-bias</th></tr></thead><tbody>{groups.map(x=><tr key={x.k}><td>{x.k}</td><td>{x.n}</td><td>{x.m43.toFixed(2)}m</td><td><strong>{x.ml.toFixed(2)}m</strong></td><td>{x.b>=0?"+":""}{x.b.toFixed(2)}m</td></tr>)}</tbody></table></section><section className="fantasy-card"><h2>10 største LOO-flytt</h2><table><thead><tr><th>Spiller</th><th>Pos</th><th>Liga</th><th>19F</th><th>V4.3.3</th><th>V4.5.9</th><th>Flytt</th><th>N</th><th>Cohort</th></tr></thead><tbody>{worst.map(x=><tr key={x.name}><td>{x.name}</td><td>{x.pos}</td><td>{x.league}</td><td>{x.start.toFixed(1)}m</td><td>{x.v43.toFixed(1)}m</td><td><strong>{x.loo.toFixed(1)}m</strong></td><td>{x.loo-x.v43>=0?"+":""}{(x.loo-x.v43).toFixed(1)}m</td><td>{x.n}</td><td>{x.cohort}</td></tr>)}</tbody></table></section></>}</main>}
