"use client";
import {useEffect,useState} from "react";
import {getSupabaseBrowserClient} from "../../../../../lib/supabase";
import "../../../fantasy.css";
import "../../xfp-admin.css";

type SourceDiagnostic={source:string;articles:number;matches:number;staleOrUndated?:number;stale?:number;undated?:number;error?:string};
type SourceResult={scannedSources:number;candidates:number;inserted:number;duplicates:number;diagnostics:SourceDiagnostic[]};
type HockeyDiagnostic={gameId:string;game:string;matchId:number|null;tournamentId?:number|null;status:string;rawMembers?:number;keys?:string[];teamFieldValues?:Record<string,string[]>;teamRows?:number;homeOrgId?:string;awayOrgId?:string;homeMembers?:number;awayMembers?:number;missing?:number;error?:string};
type HockeyResult={gamesChecked:number;candidates:number;inserted:number;duplicates:number;diagnostics:HockeyDiagnostic[]};
type BacktestRow={playerName:string;expectedStatus:string;foundStatus:string|null;evidence:string|null;result:"correct"|"missing"|"misclassified"};
type BacktestTest={id:string;label:string;articleUrl:string;expected:number;found:number;correct:number;missing:number;misclassified:number;rows:BacktestRow[]};
type BacktestResult={expected:number;found:number;correct:number;missing:number;misclassified:number;tests:BacktestTest[]};
type PipelineRow=BacktestRow&{rosterMatch:boolean;matchMethod:string|null;matchConfidence:number|null;reviewStatus:string|null;matchReason:string|null};
type PipelineTest={id:string;label:string;articleUrl:string;publishedAt:string|null;expected:number;found:number;correct:number;missing:number;misclassified:number;rosterMatched:number;rows:PipelineRow[]};
type PipelineResult={readOnly:boolean;writes:number;expected:number;found:number;correct:number;missing:number;misclassified:number;rosterMatched:number;tests:PipelineTest[]};

export default function AvailabilityScanPage(){const[token,setToken]=useState<string|null>(null),[msg,setMsg]=useState("Kontrollerer admin-tilgang …"),[busy,setBusy]=useState<"web"|"hockey"|"backtest"|"pipeline"|null>(null),[result,setResult]=useState<SourceResult|null>(null),[hockey,setHockey]=useState<HockeyResult|null>(null),[backtest,setBacktest]=useState<BacktestResult|null>(null),[pipeline,setPipeline]=useState<PipelineResult|null>(null);
 useEffect(()=>{(async()=>{try{const s=getSupabaseBrowserClient();const{data}=await s!.auth.getSession();const t=data.session?.access_token;if(!t)throw new Error("Du må være logget inn");setToken(t);setMsg("Klar til å skanne dokumenterte availability-kilder")}catch(e:any){setMsg(e?.message||"Ingen tilgang")}})()},[]);
 async function scanWeb(){if(!token)return;setBusy("web");setMsg("Skanner nitten.no, klubber og lokalaviser …");try{const r=await fetch("/api/admin/fantasy/availability-source-scan",{method:"POST",headers:{Authorization:`Bearer ${token}`}}),b=await r.json();if(!r.ok||!b.ok)throw new Error(b.error||"Skann feilet");setResult(b);setMsg(`✓ Webkilder: ${b.inserted} nye funn · ${b.duplicates} duplikater`)}catch(e:any){setMsg(e?.message||"Skann feilet")}finally{setBusy(null)}}
 async function scanHockey(){if(!token)return;setBusy("hockey");setMsg("Kontrollerer HockeyLive-kamptropper …");try{const r=await fetch("/api/admin/fantasy/availability-hockeylive-scan",{method:"POST",headers:{Authorization:`Bearer ${token}`}}),b=await r.json();if(!r.ok||!b.ok)throw new Error(b.error||"HockeyLive-skann feilet");setHockey(b);setMsg(`✓ HockeyLive: ${b.inserted} nye not_in_lineup-funn · ${b.duplicates} duplikater`)}catch(e:any){setMsg(e?.message||"HockeyLive-skann feilet")}finally{setBusy(null)}}
 async function runBacktest(){if(!token)return;setBusy("backtest");setMsg("Kjører nitten.no golden-backtester …");try{const r=await fetch("/api/admin/fantasy/availability-nitten-backtest",{method:"POST",headers:{Authorization:`Bearer ${token}`}}),b=await r.json();if(!r.ok||!b.ok)throw new Error(b.error||"Backtest feilet");setBacktest(b);setMsg(`✓ Backtest: ${b.correct}/${b.expected} korrekte · ${b.missing} mangler · ${b.misclassified} feilklassifisert`)}catch(e:any){setMsg(e?.message||"Backtest feilet")}finally{setBusy(null)}}
 async function runPipeline(){if(!token)return;setBusy("pipeline");setMsg("Kjører read-only produksjonspipeline mot Golden-artiklene …");try{const r=await fetch("/api/admin/fantasy/availability-nitten-pipeline-backtest",{method:"POST",headers:{Authorization:`Bearer ${token}`}}),b=await r.json();if(!r.ok||!b.ok)throw new Error(b.error||"Pipeline-backtest feilet");setPipeline(b);setMsg(`✓ Pipeline: ${b.correct}/${b.expected} korrekte · ${b.rosterMatched} matcher nåværende roster · ${b.writes} writes`)}catch(e:any){setMsg(e?.message||"Pipeline-backtest feilet")}finally{setBusy(null)}}
 return <main className="fantasy-shell xfp-command-center"><section className="xfp-command-hero"><p className="fantasy-kicker">STANG INN · MP-09</p><h1>Automatisk kildeskann</h1><p>Klubbsider, nitten.no og lokalaviser gir dokumenterte skade-/fraværskandidater. HockeyLive sammenligner komplette kamptropper mot aktiv roster og kan bare foreslå den nøytrale statusen «ikke i kamptropp».</p></section>
 <section className="xfp-panel"><div className="xfp-panel-head"><div><p className="eyebrow">IKKE-AUTORITATIV INNHENTING</p><h2>Kjør kildekontroll</h2><p>Ingen funn publiseres automatisk. Faktisk availability endres bare etter eksplisitt admin-godkjenning i review-køen. Offisielle Facebook-/Instagram-innlegg registreres manuelt i review-køen med direkte lenke.</p></div><a className="xfp-secondary" href="/fantasy/admin-analysis/availability/findings">← Review-kø</a></div><div className="xfp-actions"><button className="xfp-primary" disabled={!!busy||!token} onClick={scanWeb}>{busy==="web"?"Skanner …":"Skann webkilder"}</button><button className="xfp-secondary" disabled={!!busy||!token} onClick={scanHockey}>{busy==="hockey"?"Kontrollerer …":"Kontroller HockeyLive-tropper"}</button><button className="xfp-secondary" disabled={!!busy||!token} onClick={runBacktest}>{busy==="backtest"?"Tester …":"Kjør nitten.no-backtest"}</button><button className="xfp-secondary" disabled={!!busy||!token} onClick={runPipeline}>{busy==="pipeline"?"Tester pipeline …":"Test nitten.no-produksjonspipeline"}</button><span>{msg}</span></div></section>
 {pipeline&&<section className="xfp-panel"><div className="xfp-panel-head"><div><p className="eyebrow">READ-ONLY PRODUKSJONSPIPELINE</p><h2>nitten.no end-to-end kontroll</h2><p>Samme artikkelhenting, HTML→tekst, parser og roster-matcher som produksjon. 45-dagersgrensen ignoreres kun for historiske Golden-artikler. Ingen database-skriving utføres.</p></div></div><p className="preseason-message"><strong>Totalt:</strong> {pipeline.correct}/{pipeline.expected} korrekte · {pipeline.missing} mangler · {pipeline.misclassified} feilklassifisert · nåværende roster-match {pipeline.rosterMatched} · writes {pipeline.writes}</p>{pipeline.tests.map(test=><div key={`pipeline-${test.id}`} style={{marginTop:24}}><div className="xfp-panel-head"><div><h3>{test.label}</h3><p className="preseason-message">Parser: {test.correct}/{test.expected} · roster-match: {test.rosterMatched}/{test.expected} · publisert: {test.publishedAt||"—"}</p></div><a className="xfp-secondary" href={test.articleUrl} target="_blank" rel="noreferrer">Åpne artikkel ↗</a></div><div className="preseason-table-wrap"><table className="preseason-table"><thead><tr><th>Spiller</th><th>Forventet</th><th>Funnet</th><th>Parser</th><th>Roster-match</th><th>Matchgrunnlag</th></tr></thead><tbody>{test.rows.map(r=><tr key={`pipeline-${test.id}-${r.playerName}`}><td><strong>{r.playerName}</strong></td><td>{r.expectedStatus}</td><td>{r.foundStatus||"—"}</td><td>{r.result==="correct"?"✓ korrekt":r.result==="missing"?"⚠️ mangler":"⚠️ feil"}</td><td>{r.rosterMatch?`✓ ${r.matchMethod||"match"}`:"—"}</td><td>{r.matchReason||r.evidence||"—"}</td></tr>)}</tbody></table></div></div>)}</section>}
 {backtest&&<section className="xfp-panel"><div className="xfp-panel-head"><div><p className="eyebrow">READ-ONLY GOLDEN TESTS</p><h2>nitten.no-backtester</h2><p>Historiske tester mot fastsatt fasit. De ignorerer 45-dagersgrensen kun i testmodus og skriver aldri til availability.</p></div></div><p className="preseason-message"><strong>Totalt:</strong> forventet {backtest.expected} · funnet {backtest.found} · korrekte {backtest.correct} · mangler {backtest.missing} · feilklassifisert {backtest.misclassified}</p>{backtest.tests.map(test=><div key={test.id} style={{marginTop:24}}><div className="xfp-panel-head"><div><h3>{test.label}</h3><p className="preseason-message">Forventet: {test.expected} · funnet: {test.found} · korrekte: {test.correct} · mangler: {test.missing} · feilklassifisert: {test.misclassified}</p></div><a className="xfp-secondary" href={test.articleUrl} target="_blank" rel="noreferrer">Åpne artikkel ↗</a></div><div className="preseason-table-wrap"><table className="preseason-table"><thead><tr><th>Spiller</th><th>Forventet</th><th>Funnet</th><th>Resultat</th><th>Tekstgrunnlag</th></tr></thead><tbody>{test.rows.map(r=><tr key={`${test.id}-${r.playerName}`}><td><strong>{r.playerName}</strong></td><td>{r.expectedStatus}</td><td>{r.foundStatus||"—"}</td><td>{r.result==="correct"?"✓ korrekt":r.result==="missing"?"⚠️ mangler":"⚠️ feilklassifisert"}</td><td>{r.evidence||"—"}</td></tr>)}</tbody></table></div></div>)}</section>}
 {result&&<section className="xfp-panel"><h2>Webkilder</h2><div className="preseason-table-wrap"><table className="preseason-table"><thead><tr><th>Kilde</th><th>Artikler</th><th>Funn</th><th>Gamle</th><th>Udaterte</th><th>Status</th></tr></thead><tbody>{result.diagnostics.map(d=><tr key={d.source}><td><strong>{d.source}</strong></td><td>{d.articles}</td><td>{d.matches}</td><td>{d.stale??0}</td><td>{d.undated??d.staleOrUndated??0}</td><td>{d.error?`⚠️ ${d.error}`:"✓ lest"}</td></tr>)}</tbody></table><p className="preseason-message">Kilder: {result.scannedSources} · kandidater: {result.candidates} · nye: {result.inserted} · duplikater: {result.duplicates}</p></div></section>}
 {hockey&&<section className="xfp-panel"><h2>HockeyLive-kamptropper</h2><p>Kun kamper de siste tre dagene med tilgjengelige og tilstrekkelig komplette MatchTeamMembers-data vurderes. Lag fordeles med TournamentTeams → teamOrgId; ved usikker kobling opprettes ingen funn.</p><div className="preseason-table-wrap"><table className="preseason-table"><thead><tr><th>Kamp</th><th>Match / turnering</th><th>Rå data</th><th>Org H/B</th><th>Tropp H/B</th><th>Mangler roster</th><th>Status</th></tr></thead><tbody>{hockey.diagnostics.map(d=><tr key={d.gameId}><td><strong>{d.game}</strong></td><td>{d.matchId||"—"}<small>{d.tournamentId?`turnering ${d.tournamentId}`:"turnering —"}</small></td><td>{d.rawMembers??"—"}</td><td>{d.homeOrgId||"—"} / {d.awayOrgId||"—"}</td><td>{d.homeMembers??"—"} / {d.awayMembers??"—"}</td><td>{d.missing??"—"}</td><td>{d.error?`⚠️ ${d.error}`:d.status}</td></tr>)}</tbody></table><p className="preseason-message">Kamper: {hockey.gamesChecked} · kandidater: {hockey.candidates} · nye: {hockey.inserted} · duplikater: {hockey.duplicates}</p></div>{hockey.diagnostics.filter(d=>d.keys?.length||Object.keys(d.teamFieldValues||{}).length).map(d=><div key={`${d.gameId}-structure`} style={{marginTop:16}}><strong>{d.game} · MatchTeamMembers-struktur</strong><p className="preseason-message">Felter: {(d.keys||[]).join(" · ")||"—"}</p>{Object.entries(d.teamFieldValues||{}).map(([field,values])=><p className="preseason-message" key={field}><strong>{field}:</strong> {values.join(" · ")}</p>)}</div>)}</section>}
 </main>;
}
