"use client";
import {useEffect,useState} from "react";
import {getSupabaseBrowserClient} from "../../../../../lib/supabase";
import "../../../fantasy.css";
import "../../xfp-admin.css";

type SourceDiagnostic={source:string;articles:number;matches:number;staleOrUndated?:number;error?:string};
type SourceResult={scannedSources:number;candidates:number;inserted:number;duplicates:number;diagnostics:SourceDiagnostic[]};
type HockeyDiagnostic={gameId:string;game:string;matchId:number|null;status:string;rawMembers?:number;rawTeams?:string[];homeMembers?:number;awayMembers?:number;missing?:number;error?:string};
type HockeyResult={gamesChecked:number;candidates:number;inserted:number;duplicates:number;diagnostics:HockeyDiagnostic[]};

export default function AvailabilityScanPage(){const[token,setToken]=useState<string|null>(null),[msg,setMsg]=useState("Kontrollerer admin-tilgang …"),[busy,setBusy]=useState<"web"|"hockey"|null>(null),[result,setResult]=useState<SourceResult|null>(null),[hockey,setHockey]=useState<HockeyResult|null>(null);
 useEffect(()=>{(async()=>{try{const s=getSupabaseBrowserClient();const{data}=await s!.auth.getSession();const t=data.session?.access_token;if(!t)throw new Error("Du må være logget inn");setToken(t);setMsg("Klar til å skanne dokumenterte availability-kilder")}catch(e:any){setMsg(e?.message||"Ingen tilgang")}})()},[]);
 async function scanWeb(){if(!token)return;setBusy("web");setMsg("Skanner nitten.no, klubber og lokalaviser …");try{const r=await fetch("/api/admin/fantasy/availability-source-scan",{method:"POST",headers:{Authorization:`Bearer ${token}`}}),b=await r.json();if(!r.ok||!b.ok)throw new Error(b.error||"Skann feilet");setResult(b);setMsg(`✓ Webkilder: ${b.inserted} nye funn · ${b.duplicates} duplikater`)}catch(e:any){setMsg(e?.message||"Skann feilet")}finally{setBusy(null)}}
 async function scanHockey(){if(!token)return;setBusy("hockey");setMsg("Kontrollerer HockeyLive-kamptropper …");try{const r=await fetch("/api/admin/fantasy/availability-hockeylive-scan",{method:"POST",headers:{Authorization:`Bearer ${token}`}}),b=await r.json();if(!r.ok||!b.ok)throw new Error(b.error||"HockeyLive-skann feilet");setHockey(b);setMsg(`✓ HockeyLive: ${b.inserted} nye not_in_lineup-funn · ${b.duplicates} duplikater`)}catch(e:any){setMsg(e?.message||"HockeyLive-skann feilet")}finally{setBusy(null)}}
 return <main className="fantasy-shell xfp-command-center"><section className="xfp-command-hero"><p className="fantasy-kicker">STANG INN · MP-09</p><h1>Automatisk kildeskann</h1><p>Klubbsider, nitten.no og lokalaviser gir dokumenterte skade-/fraværskandidater. HockeyLive sammenligner komplette kamptropper mot aktiv roster og kan bare foreslå den nøytrale statusen «ikke i kamptropp».</p></section>
 <section className="xfp-panel"><div className="xfp-panel-head"><div><p className="eyebrow">IKKE-AUTORITATIV INNHENTING</p><h2>Kjør kildekontroll</h2><p>Ingen funn publiseres automatisk. Faktisk availability endres bare etter eksplisitt admin-godkjenning i review-køen. Offisielle Facebook-/Instagram-innlegg registreres manuelt i review-køen med direkte lenke.</p></div><a className="xfp-secondary" href="/fantasy/admin-analysis/availability/findings">← Review-kø</a></div><div className="xfp-actions"><button className="xfp-primary" disabled={!!busy||!token} onClick={scanWeb}>{busy==="web"?"Skanner …":"Skann webkilder"}</button><button className="xfp-secondary" disabled={!!busy||!token} onClick={scanHockey}>{busy==="hockey"?"Kontrollerer …":"Kontroller HockeyLive-tropper"}</button><span>{msg}</span></div></section>
 {result&&<section className="xfp-panel"><h2>Webkilder</h2><div className="preseason-table-wrap"><table className="preseason-table"><thead><tr><th>Kilde</th><th>Artikler</th><th>Funn</th><th>Gamle/udaterte</th><th>Status</th></tr></thead><tbody>{result.diagnostics.map(d=><tr key={d.source}><td><strong>{d.source}</strong></td><td>{d.articles}</td><td>{d.matches}</td><td>{d.staleOrUndated??0}</td><td>{d.error?`⚠️ ${d.error}`:"✓ lest"}</td></tr>)}</tbody></table><p className="preseason-message">Kilder: {result.scannedSources} · kandidater: {result.candidates} · nye: {result.inserted} · duplikater: {result.duplicates}</p></div></section>}
 {hockey&&<section className="xfp-panel"><h2>HockeyLive-kamptropper</h2><p>Kun kamper de siste tre dagene med tilgjengelige og tilstrekkelig komplette MatchTeamMembers-data vurderes. Rå antall og lagverdier vises for å skille tomme datasett fra team-navn som ikke matcher.</p><div className="preseason-table-wrap"><table className="preseason-table"><thead><tr><th>Kamp</th><th>Match ID</th><th>Rå data</th><th>Tropp H/B</th><th>Mangler roster</th><th>Status</th></tr></thead><tbody>{hockey.diagnostics.map(d=><tr key={d.gameId}><td><strong>{d.game}</strong></td><td>{d.matchId||"—"}</td><td>{d.rawMembers??"—"}{d.rawTeams?.length?<small>{d.rawTeams.join(" · ")}</small>:null}</td><td>{d.homeMembers??"—"} / {d.awayMembers??"—"}</td><td>{d.missing??"—"}</td><td>{d.error?`⚠️ ${d.error}`:d.status}</td></tr>)}</tbody></table><p className="preseason-message">Kamper: {hockey.gamesChecked} · kandidater: {hockey.candidates} · nye: {hockey.inserted} · duplikater: {hockey.duplicates}</p></div></section>}
 </main>}
