"use client";

import {useMemo,useState} from "react";
import {getSupabaseBrowserClient} from "../../../../lib/supabase";
import {HISTORICAL_PRICES_2024} from "../../../../lib/fantasy/historical-prices-2024";
import {HISTORICAL_GOALIE_PRICES_2024} from "../../../../lib/fantasy/historical-goalie-prices-2024";
import {HISTORICAL_PRICES_2025} from "../../../../lib/fantasy/historical-prices-2025";
import {importHistoryFor} from "../../../../lib/fantasy/import-history-2026";
import {returnHistoryFor} from "../../../../lib/fantasy/return-history-2026";
import {importEstimateV43,talentEstimateV43,TALENT_HISTORY_2026_V43,type TalentHistoryV43,type V43Position} from "../../../../lib/fantasy/import-pricing-v4-3";
import {calibrateMarket,clamp,half,repricingScore,TEAM_BUDGET_M} from "../../../../lib/fantasy/market-calibration";
import "../../fantasy.css";

const S24="2024/25",S25="2025/26",POS=["C","W","D","G"] as const;
const EXTRA_TALENTS:TalentHistoryV43[]=[{name:"Markus Walberg",position:"G",league:"Norway U20",games:33,savePct:0.916,gaa:3.0,sourceNote:"Sparta U20 2025/26; promoted to A-team goalie duo."}];
const norm=(v:any)=>String(v??"").toLocaleLowerCase("nb-NO").normalize("NFD").replace(/[\u0300-\u036f]/g,"").replace(/ø/g,"o").replace(/æ/g,"ae").replace(/[^a-z0-9]+/g," ").trim();
const natural=(s:string)=>{const[last,...r]=String(s||"").split(",");return r.length?`${r.join(",").trim()} ${last.trim()}`:String(s||"")};
const arr=(s:string)=>norm(s).split(" ").filter(Boolean).filter(x=>x!=="jr"&&x!=="junior"),tok=(s:string)=>new Set(arr(s));
function siblingGuard(a:string,b:string){const A=arr(a),B=arr(natural(b));return A.length>=3&&B.length>=3&&A[A.length-1]===B[B.length-1]&&A[A.length-2]===B[B.length-2]&&A[0]!==B[0]}
function score(a:string,b:string){if(norm(a)===norm(natural(b)))return 1000;if(siblingGuard(a,b))return 0;const A=tok(a),B=tok(natural(b));let c=0;for(const x of A)if(B.has(x))c++;const mn=Math.min(A.size,B.size),mx=Math.max(A.size,B.size);if(c===mn&&mn>=2)return 800+c*10-mn*Math.abs(mx-mn);return c>=2?c*100-Math.abs(A.size-B.size)*10:0}
function match(name:string,src:any[],used?:Set<number>){let bi=-1,bs=0;for(let i=0;i<src.length;i++){if(used?.has(i))continue;const s=score(name,src[i][0]);if(s>bs){bs=s;bi=i}}return bi>=0&&bs>=200?{i:bi,row:src[bi],score:bs}:null}
function bestPlayerMatch(name:string,src:any[]){let best:any=null,bs=0;for(const x of src){const sc=score(name,x.name);if(sc>bs){bs=sc;best=x}}return bs>=800?best:null}
function solve(A:number[][],b:number[]){const n=b.length,m=A.map((r,i)=>[...r,b[i]]);for(let i=0;i<n;i++){let p=i;for(let j=i+1;j<n;j++)if(Math.abs(m[j][i])>Math.abs(m[p][i]))p=j;[m[i],m[p]]=[m[p],m[i]];const d=m[i][i]||1e-9;for(let k=i;k<=n;k++)m[i][k]/=d;for(let j=0;j<n;j++)if(j!==i){const f=m[j][i];for(let k=i;k<=n;k++)m[j][k]-=f*m[i][k]}}return m.map(r=>r[n])}
const feat=(r:any)=>[1,r.oldPrice/1e6,Number(r.ppg||0),Math.min(1,Number(r.games||0)/45),(r.oldPrice/1e6)*Math.min(1,Number(r.games||0)/45)];
const featStats=(r:any)=>[1,Number(r.ppg||0),Math.min(1,Number(r.games||0)/45),Number(r.ppg||0)*Math.min(1,Number(r.games||0)/45)];
function fit(rs:any[]){const n=5,A=Array.from({length:n},()=>Array(n).fill(0)),b=Array(n).fill(0);for(const r of rs){const x=feat(r),y=r.newPrice/1e6;for(let j=0;j<n;j++){b[j]+=x[j]*y;for(let k=0;k<n;k++)A[j][k]+=x[j]*x[k]}}for(let i=0;i<n;i++)A[i][i]+=0.4;return solve(A,b)}
function fitStats(rs:any[]){const n=4,A=Array.from({length:n},()=>Array(n).fill(0)),b=Array(n).fill(0);for(const r of rs){const x=featStats(r),y=r.newPrice/1e6;for(let j=0;j<n;j++){b[j]+=x[j]*y;for(let k=0;k<n;k++)A[j][k]+=x[j]*x[k]}}for(let i=0;i<n;i++)A[i][i]+=0.7;return solve(A,b)}
const predict=(c:number[],r:any)=>clamp(feat(r).reduce((s,v,i)=>s+v*c[i],0),1,20);
const predictStats=(c:number[],r:any)=>clamp(featStats(r).reduce((s,v,i)=>s+v*c[i],0),1,20);
const statsWeight=(g:any)=>clamp(Number(g||0)/35,0.15,0.9);
function median(v:number[]){const a=[...v].filter(Number.isFinite).sort((x,y)=>x-y);if(!a.length)return 5;const m=Math.floor(a.length/2);return a.length%2?a[m]:(a[m-1]+a[m])/2}
function canonTeam(v:any){const s=norm(v);if(s.includes("storhamar"))return"Storhamar";if(s.includes("stavanger")||s.includes("oilers"))return"Stavanger";if(s.includes("valerenga"))return"Vålerenga";if(s.includes("frisk"))return"Frisk Asker";if(s.includes("sparta"))return"Sparta";if(s.includes("narvik"))return"Narvik";if(s.includes("stjernen"))return"Stjernen";if(s.includes("lillehammer"))return"Lillehammer";if(s.includes("ringerike"))return"Ringerike";if(s.includes("nidaros"))return"Nidaros";return String(v||"").trim()}
async function auth(){const s=getSupabaseBrowserClient(),{data}=await s!.auth.getSession();if(!data.session?.access_token)throw new Error("Logg inn som admin");return data.session.access_token}
function avg(xs:number[]){return xs.length?xs.reduce((a,b)=>a+b,0)/xs.length:0}

export default function Page(){
 const[busy,setBusy]=useState(false),[msg,setMsg]=useState("Klar for fullmarkedstest"),[rows,setRows]=useState<any[]>([]),[market,setMarket]=useState<any>(null);
 async function run(){setBusy(true);try{
  const t=await auth();
  const[a,b,rr]=await Promise.all([fetch(`/api/fantasy-player-form?season=${encodeURIComponent(S24)}`,{headers:{Authorization:`Bearer ${t}`}}),fetch(`/api/fantasy-player-form?season=${encodeURIComponent(S25)}`,{headers:{Authorization:`Bearer ${t}`}}),fetch('/api/fantasy-roster-enriched-2026',{cache:'no-store'})]);
  const p24=await a.json(),p25=await b.json(),roster=await rr.json();if(!a.ok||!p24.ok)throw new Error(p24.error||"Kunne ikke hente 2024/25");if(!b.ok||!p25.ok)throw new Error(p25.error||"Kunne ikke hente 2025/26");if(!rr.ok||!roster.ok||!roster.rows?.length)throw new Error(roster.error||"Kunne ikke hente 2026/27-roster");
  const oldPlayers=p24.result?.rows||[],curPlayers=p25.result?.rows||[],oldSk=HISTORICAL_PRICES_2024.filter(x=>x[1]!=null),oldG=HISTORICAL_GOALIE_PRICES_2024.filter(x=>x[1]!=null),p25src=HISTORICAL_PRICES_2025.filter(x=>x[2]>0),uS=new Set<number>(),uG=new Set<number>(),uN=new Set<number>(),train:any[]=[];
  for(const pl of oldPlayers){const G=String(pl.position).toUpperCase()==="G",mo=match(pl.name,(G?oldG:oldSk) as any[],G?uG:uS),mn=match(pl.name,p25src as any[],uN);if(mo&&mn){(G?uG:uS).add(mo.i);uN.add(mn.i);train.push({...pl,oldPrice:mo.row[1],newPrice:mn.row[2]})}}
  const coef:any={},coefStats:any={};for(const z of POS){const sm=train.filter(x=>String(x.position).toUpperCase()===z&&x.games>=3);if(sm.length>=5){coef[z]=fit(sm);coefStats[z]=fitStats(sm)}}
  const statMap=new Map<string,any>();for(const x of curPlayers)statMap.set(norm(x.name),x);const oldStatMap=new Map<string,any>();for(const x of oldPlayers)oldStatMap.set(norm(x.name),x);const priceMap=new Map<string,any>();for(const x of p25src)priceMap.set(norm(natural(x[0])),x);
  const priceByPos:any={C:[],W:[],D:[],G:[]};for(const pl of curPlayers){const pos=String(pl.position||"").toUpperCase();if(!priceByPos[pos])continue;const pr=match(pl.name,p25src as any[]);if(pr)priceByPos[pos].push(Number(pr.row[2])/1e6)}const allMedian=median(p25src.map(x=>Number(x[2])/1e6)),posMedian:any={C:median(priceByPos.C),W:median(priceByPos.W),D:median(priceByPos.D),G:median(priceByPos.G)};
  const talents=new Map([...TALENT_HISTORY_2026_V43,...EXTRA_TALENTS].map(x=>[norm(x.name),x])),raw:any[]=[];
  for(const r of roster.rows){const name=String(r.name),team=canonTeam(r.team);let s=statMap.get(norm(name))||bestPlayerMatch(name,curPlayers),hist:any=null;if(!s)hist=oldStatMap.get(norm(name))||bestPlayerMatch(name,oldPlayers);let pr=priceMap.get(norm(name));if(!pr){const m=match(name,p25src as any[]);if(m&&m.score>=800)pr=m.row}const pos=String(r.position||s?.position||hist?.position||"").toUpperCase() as V43Position,valid=(POS as readonly string[]).includes(pos);let old=pr?Number(pr[2])/1e6:null,rawEst=0,cls="Provisorisk",confidence="Lav",reason="",metric="";
   if(valid&&s&&old!=null&&coef[pos]){const base=predict(coef[pos],{...s,oldPrice:old*1e6}),rs=repricingScore({...s,old,position:pos}),blend=0.35+0.65*(rs/100);rawEst=clamp(old+(base-old)*blend,1,20);cls="Modell";confidence="Høy";reason="2025/26-statistikk + pris"}
   else if(valid&&s&&old==null&&coefStats[pos]&&Number(s.games||0)>=3){const anchor=Number(posMedian[pos]),model=predictStats(coefStats[pos],s),w=statsWeight(s.games);old=anchor;rawEst=clamp(anchor+(model-anchor)*w,1,20);cls="Statsmodell";confidence=Number(s.games||0)>=15?"Middels":"Lav";reason="2025/26-statistikk uten historisk pris"}
   else if(valid&&hist&&old==null&&coefStats[pos]&&Number(hist.games||0)>=3){const anchor=Number(posMedian[pos]),model=predictStats(coefStats[pos],hist),w=statsWeight(hist.games)*0.75;old=anchor;rawEst=clamp(anchor+(model-anchor)*w,1,20);cls="Historikkmodell";confidence=Number(hist.games||0)>=20?"Middels":"Lav";reason="2024/25-returhistorikk"}
   else if(valid){const anchor=Number(posMedian[pos]||allMedian),ih=importHistoryFor(name),tal=talents.get(norm(name));if(ih){const est=importEstimateV43(ih,pos,team,name);if(est){old=anchor;rawEst=est.raw;cls=est.note;confidence=est.confidence;metric=est.metric;reason=`${ih.league} · ${est.metric}`;}else{old=anchor;rawEst=anchor;reason="Importdata utilstrekkelig"}}
    else if(tal){const est=talentEstimateV43(tal);old=anchor;rawEst=est.raw;cls="Talentmodell V4.3.3";confidence=est.confidence;metric=est.metric;reason=`${tal.league} · ${est.metric}`}
    else if(old!=null){rawEst=old;cls="Videreført";reason="Historisk pris"}
    else {const rh=returnHistoryFor(name);old=anchor;if(rh&&Number.isFinite(rh.seniorPoints)&&rh.seniorGames>=15){const ppg=Number(rh.seniorPoints)/rh.seniorGames,expected=pos==="D"?0.28:0.55,scale=pos==="D"?7:8,w=clamp(rh.seniorGames/70,0.35,0.65);rawEst=clamp(anchor+(ppg-expected)*scale*w,1,20);cls="Historikkmodell";metric=`${ppg.toFixed(2)} P/GP`;reason="EHL-returhistorikk"}else{rawEst=anchor;reason="Posisjonsmedian"}}
   }else{old=allMedian;rawEst=allMedian;reason="Mangler gyldig posisjon"}
   raw.push({name,team,pos:valid?pos:"—",old:Number(old??allMedian),rawEst,cls,confidence,reason,metric});
  }
  const calibrated=calibrateMarket(raw.map(x=>({...x,old:Number(x.old),rawEst:Number(x.rawEst)})));setRows(calibrated.rows);setMarket(calibrated.stats);setMsg(`Ferdig · ${calibrated.rows.length} spillere analysert`);
 }catch(e:any){setMsg(`Feil: ${e.message||e}`)}finally{setBusy(false)}}
 const byPos=useMemo(()=>POS.map(pos=>{const rs=rows.filter(r=>r.pos===pos);return{pos,n:rs.length,raw:avg(rs.map(r=>r.rawEst)),cal:avg(rs.map(r=>r.est)),med:median(rs.map(r=>r.est))}}),[rows]);
 const byTeam=useMemo(()=>{const m=new Map<string,any[]>();for(const r of rows)m.set(r.team,[...(m.get(r.team)||[]),r]);return[...m.entries()].map(([team,rs])=>({team,n:rs.length,avg:avg(rs.map(r=>r.est)),top:Math.max(...rs.map(r=>r.est)),cheap:rs.filter(r=>r.est<=6).length})).sort((a,b)=>b.avg-a.avg)},[rows]);
 const bands=useMemo(()=>[{x:"≤5m",n:rows.filter(r=>r.est<=5).length},{x:"5.5–8m",n:rows.filter(r=>r.est>=5.5&&r.est<=8).length},{x:"8.5–11m",n:rows.filter(r=>r.est>=8.5&&r.est<=11).length},{x:"11.5–14m",n:rows.filter(r=>r.est>=11.5&&r.est<=14).length},{x:"≥14.5m",n:rows.filter(r=>r.est>=14.5).length}], [rows]);
 const top=[...rows].sort((a,b)=>b.est-a.est).slice(0,20),cheapByPos=POS.map(pos=>({pos,rs:[...rows].filter(r=>r.pos===pos).sort((a,b)=>a.est-b.est).slice(0,8)}));
 return <main className="fantasy-page"><section className="fantasy-card"><h1>V4.3.3 · full markedstest 2026/27</h1><p>Samme etablerte spillerlogikk som V4.2, men V4.3.3 import-/talentmotor for nye spillere. Viser både råpris og global markedskalibrering mot 100m-budsjettet.</p><button onClick={run} disabled={busy}>{busy?"Analyserer…":"Kjør fullmarkedstest"}</button><p><strong>{msg}</strong></p></section>{rows.length>0&&<><section className="fantasy-card"><h2>Markedsøkonomi</h2><p>Rått snitt: <strong>{market.rawAvg.toFixed(2)}m</strong> · Kalibrert: <strong>{market.calibratedAvg.toFixed(2)}m</strong> · Historisk anker: <strong>{market.oldAvg.toFixed(2)}m</strong> · Skala: <strong>{(market.scale*100).toFixed(1)}%</strong> · Lagbudsjett: <strong>{TEAM_BUDGET_M}m</strong></p><table><thead><tr><th>Pos</th><th>N</th><th>Rått snitt</th><th>Kalibrert snitt</th><th>Median</th></tr></thead><tbody>{byPos.map(x=><tr key={x.pos}><td>{x.pos}</td><td>{x.n}</td><td>{x.raw.toFixed(2)}m</td><td>{x.cal.toFixed(2)}m</td><td>{x.med.toFixed(1)}m</td></tr>)}</tbody></table></section><section className="fantasy-card"><h2>Prisfordeling</h2><table><thead><tr><th>Bånd</th><th>Spillere</th></tr></thead><tbody>{bands.map(x=><tr key={x.x}><td>{x.x}</td><td>{x.n}</td></tr>)}</tbody></table></section><section className="fantasy-card"><h2>Klubbkontroll · hele rosteren</h2><table><thead><tr><th>Lag</th><th>N</th><th>Snitt</th><th>Dyreste</th><th>≤6m</th></tr></thead><tbody>{byTeam.map(x=><tr key={x.team}><td>{x.team}</td><td>{x.n}</td><td>{x.avg.toFixed(2)}m</td><td>{x.top.toFixed(1)}m</td><td>{x.cheap}</td></tr>)}</tbody></table></section><section className="fantasy-card"><h2>Topp 20 dyreste</h2><table><thead><tr><th>Spiller</th><th>Lag</th><th>Pos</th><th>Klasse</th><th>Rå</th><th>Pris</th></tr></thead><tbody>{top.map(r=><tr key={r.name}><td>{r.name}</td><td>{r.team}</td><td>{r.pos}</td><td>{r.cls}</td><td>{r.rawEst.toFixed(2)}m</td><td><strong>{r.est.toFixed(1)}m</strong></td></tr>)}</tbody></table></section>{cheapByPos.map(g=><section className="fantasy-card" key={g.pos}><h2>Billigste {g.pos}</h2><table><thead><tr><th>Spiller</th><th>Lag</th><th>Klasse</th><th>Pris</th></tr></thead><tbody>{g.rs.map(r=><tr key={r.name}><td>{r.name}</td><td>{r.team}</td><td>{r.cls}</td><td>{r.est.toFixed(1)}m</td></tr>)}</tbody></table></section>)}<section className="fantasy-card"><h2>Alle 241</h2><table><thead><tr><th>Spiller</th><th>Lag</th><th>Pos</th><th>Klasse</th><th>Rå</th><th>Kalibrert</th><th>Grunnlag</th></tr></thead><tbody>{rows.map(r=><tr key={`${r.team}-${r.name}`}><td>{r.name}</td><td>{r.team}</td><td>{r.pos}</td><td>{r.cls}</td><td>{r.rawEst.toFixed(2)}m</td><td><strong>{r.est.toFixed(1)}m</strong></td><td>{r.reason}</td></tr>)}</tbody></table></section></>}</main>;
}
