"use client";

import {useEffect,useMemo,useState} from "react";
import {useParams,useSearchParams} from "next/navigation";
import {getSupabaseBrowserClient} from "../../../lib/supabase";

const SEASON="2026/27";
type View="tipping"|"fantasy";
type League={league_id:string;league_name:string;invite_code:string;my_role:string;member_count:number;created_at:string};
type TippingRow={standings_position:number;user_id:string;display_name:string;total_points:number;exact_results:number;correct_outcomes:number;scored_tips:number;member_role:string;joined_at:string};
type FantasyRow={standings_position:number;user_id:string;display_name:string;team_id:string|null;team_name:string;total_points:number;rounds_scored:number;round_wins:number;best_round_points:number;average_round_points:number;last_round_no:number|null;last_round_points:number|null;member_role:string;joined_at:string};
const pts=(v:unknown)=>Number(v||0).toFixed(1).replace(".0","");

export default function Page(){
 const params=useParams<{id:string}>(),search=useSearchParams(),id=String(params?.id||"");
 const initial:View=search.get("view")==="fantasy"?"fantasy":"tipping";
 const[view,setView]=useState<View>(initial),[tipping,setTipping]=useState<TippingRow[]>([]),[fantasy,setFantasy]=useState<FantasyRow[]>([]),[league,setLeague]=useState<League|null>(null),[me,setMe]=useState<string|null>(null),[message,setMessage]=useState(""),[copied,setCopied]=useState(false),[busy,setBusy]=useState(false);
 async function load(){if(!id)return;setBusy(true);setMessage("");const sb=getSupabaseBrowserClient();if(!sb){setBusy(false);return}const{data:s}=await sb.auth.getSession();setMe(s.session?.user.id||null);const[tipRows,fantasyRows,myLeagues]=await Promise.all([sb.rpc("get_stang_inn_private_league_tipping_standings_v1",{p_league_id:id,p_season:SEASON}),sb.rpc("get_stang_inn_private_league_fantasy_standings_v1",{p_league_id:id,p_season:SEASON}),sb.rpc("get_my_stang_inn_private_leagues_v1",{p_season:SEASON})]);setBusy(false);const error=tipRows.error||fantasyRows.error||myLeagues.error;if(error){setMessage(error.message);return}setTipping((tipRows.data||[]) as TippingRow[]);setFantasy((fantasyRows.data||[]) as FantasyRow[]);setLeague(((myLeagues.data||[]) as League[]).find(l=>l.league_id===id)||null)}
 useEffect(()=>{load()},[id]);
 function switchView(next:View){setView(next);const url=new URL(window.location.href);url.searchParams.set("view",next);window.history.replaceState({},"",url.toString())}
 async function copyCode(){if(!league?.invite_code)return;try{await navigator.clipboard.writeText(league.invite_code);setCopied(true);window.setTimeout(()=>setCopied(false),1600)}catch{setMessage(`Invitasjonskode: ${league.invite_code}`)}}
 async function leaveLeague(){if(!league||league.my_role==="owner"||!confirm("Melde deg ut av miniligaen? Du forlater både Tipping- og Fantasy-tabellen."))return;setBusy(true);const sb=getSupabaseBrowserClient();if(!sb){setBusy(false);return}const{error}=await sb.rpc("leave_stang_inn_private_league_v1",{p_league_id:id,p_season:SEASON});setBusy(false);if(error)setMessage(error.message);else window.location.assign("/leagues")}
 const memberRows=useMemo(()=>fantasy.length?fantasy.map(r=>({user_id:r.user_id,display_name:r.display_name,team_name:r.team_name,member_role:r.member_role,joined_at:r.joined_at})):tipping.map(r=>({user_id:r.user_id,display_name:r.display_name,team_name:"",member_role:r.member_role,joined_at:r.joined_at})),[fantasy,tipping]);
 const active=view==="fantasy"?fantasy:tipping,leader=active[0],mine=active.find(r=>r.user_id===me);
 return <main className="appShell sharedLeagueDetailPage">
  <header className="topbar"><a className="brand brandButton" href="/leagues" style={{textDecoration:"none"}}><div className="brandMark">🏒</div><div><p className="eyebrow">STANG INN · MINILIGA</p><h1>{league?.league_name||"Miniliga"}</h1></div></a><a className="textButton" href="/leagues">Alle ligaer →</a></header>
  <section className="pageStack sharedLeagueDetailStack" style={{marginTop:24}}>
   {league&&<><article className="heroCard sharedLeagueDetailHero"><div><p className="eyebrow">ÉN LIGA · TO TABELLER</p><h2>{league.league_name}</h2><p className="muted">Samme {league.member_count} medlem{league.member_count===1?"":"mer"} konkurrerer i både Tipping og Fantasy. Poeng og rangering beregnes separat.</p></div><div className="countdown"><strong>{league.member_count}</strong><span>medlemmer</span></div></article>
   <section className="sharedLeagueSummary"><article className="miniCard"><span>Din rolle</span><strong>{league.my_role==="owner"?"👑 Eier":"Medlem"}</strong><small>gjelder begge spill</small></article><article className="miniCard"><span>Invitasjonskode</span><strong className="leagueCode">{league.invite_code}</strong><button className="textButton" onClick={copyCode}>{copied?"✓ Kopiert":"Kopier kode"}</button></article><article className="miniCard"><span>{view==="fantasy"?"Fantasy":"Tipping"} · din plass</span><strong>{mine?`${mine.standings_position}.`:"–"}</strong><small>{mine?`${pts(mine.total_points)} poeng`:"Ingen score ennå"}</small></article></section></>}
   <div className="sharedLeagueTabs" role="tablist" aria-label="Velg konkurranse"><button role="tab" aria-selected={view==="tipping"} className={view==="tipping"?"active":""} onClick={()=>switchView("tipping")}><span>🏒</span><b>Tipping</b><small>Kamptips</small></button><button role="tab" aria-selected={view==="fantasy"} className={view==="fantasy"?"active":""} onClick={()=>switchView("fantasy")}><span>⭐</span><b>Fantasy</b><small>EHL Fantasy</small></button></div>
   {message&&<article className="quoteCard"><span>Status</span><p>{message}</p></article>}
   <article className="panel sharedLeagueStandings"><div className="panelHeading"><div><p className="eyebrow">{view==="fantasy"?"FANTASY-TABELL":"TIPPING-TABELL"}</p><h3>{view==="fantasy"?"Fantasy-stillingen":"Tipping-stillingen"}</h3></div>{leader&&<span className="statusPill">Leder: {view==="fantasy"?(leader as FantasyRow).team_name:leader.display_name}</span>}</div>
    {busy&&!active.length?<p className="muted">Laster tabell …</p>:view==="tipping"?<><div className="sharedLeagueTableHead tipping"><span>#</span><span>Spiller</span><span>Eksakte</span><span>Riktig</span><span>Poeng</span></div><div className="sharedLeagueRows">{tipping.map(r=><div className={`sharedLeagueRow tipping ${r.user_id===me?"mine":""}`} key={r.user_id}><span className="rank">{r.standings_position<=3?["🥇","🥈","🥉"][r.standings_position-1]:`${r.standings_position}.`}</span><span><strong>{r.display_name}</strong><small>{r.member_role==="owner"?"👑 Ligaeier":"Medlem"} · {r.scored_tips} avgjorte tips</small></span><span data-label="Eksakte">{r.exact_results}</span><span data-label="Riktig">{r.correct_outcomes}</span><span className="points" data-label="Poeng">{r.total_points}</span></div>)}</div></>:<><div className="sharedLeagueTableHead fantasy"><span>#</span><span>Lag / eier</span><span>Seire</span><span>Beste</span><span>Poeng</span></div><div className="sharedLeagueRows">{fantasy.map(r=><div className={`sharedLeagueRow fantasy ${r.user_id===me?"mine":""}`} key={r.user_id}><span className="rank">{r.standings_position<=3?["🥇","🥈","🥉"][r.standings_position-1]:`${r.standings_position}.`}</span><span><strong>{r.team_name}</strong><small>{r.display_name} · {r.member_role==="owner"?"👑 Ligaeier":"Medlem"}</small></span><span data-label="Seire">{r.round_wins}</span><span data-label="Beste">{pts(r.best_round_points)}</span><span className="points" data-label="Poeng">{pts(r.total_points)}</span></div>)}</div></>}
    {!active.length&&!busy&&!message&&<div className="emptyState"><strong>Ingen medlemmer å vise.</strong><span>Tabellen fylles automatisk når medlemmer blir med.</span></div>}
   </article>
   <article className="panel sharedLeagueMembers"><div className="panelHeading"><div><p className="eyebrow">MEDLEMMER</p><h3>{memberRows.length} i ligaen</h3></div>{league?.my_role!=="owner"&&league&&<button className="sharedLeagueLeave" disabled={busy} onClick={leaveLeague}>Meld meg ut</button>}</div><div className="sharedLeagueMemberGrid">{memberRows.map(r=><article key={r.user_id}><span>{r.member_role==="owner"?"👑 Ligaeier":"Medlem"}</span><strong>{r.display_name}</strong><small>{r.team_name&&r.team_name!=="Ikke opprettet lag"?`${r.team_name} · `:""}med siden {new Date(r.joined_at).toLocaleDateString("nb-NO")}</small></article>)}</div>{league?.my_role==="owner"&&<p className="muted ownerNote">Ligaeier kan ikke melde seg ut. Dette beskytter ligaen og medlemskapet mot å bli stående uten eier.</p>}</article>
  </section>
 </main>;
}
