"use client";

import {useEffect,useMemo,useState} from "react";
import {getSupabaseBrowserClient} from "../../../../../lib/supabase";
import "../../../fantasy.css";

const SEASON="2024/25", TOURNAMENT="429162";
const sign=(v:any)=>{const n=Number(v);return !Number.isFinite(n)?"—":n>0?`+${n}`:String(n)};
const score=(r:any)=>r?.diffs?Math.abs(r.diffs.goals||0)+Math.abs(r.diffs.assists||0)+Math.abs(r.diffs.shots||0)+Math.abs(r.diffs.pim||0):9999;

export default function Drilldown(){
 const[data,setData]=useState<any>(null),[msg,setMsg]=useState(""),[busy,setBusy]=useState(false);
 async function token(){const s=getSupabaseBrowserClient();if(!s)throw new Error("Supabase mangler");const{data}=await s.auth.getSession();if(!data.session?.access_token)throw new Error("Logg inn som admin");return data.session.access_token}
 async function run(){setBusy(true);setMsg("Henter 2024/25-diagnose …");try{const t=await token();const r=await fetch(`/api/fantasy-skater-season-check?season=${encodeURIComponent(SEASON)}&tournamentId=${TOURNAMENT}`,{headers:{Authorization:`Bearer ${t}`}});const p=await r.json();if(!r.ok||!p.ok)throw new Error(p.error||"Diagnose feilet");setData(p);setMsg("Ferdig. Tabellen er sortert etter størst råavvik.")}catch(e:any){setMsg(e?.message||"Feil")}finally{setBusy(false)}}
 useEffect(()=>{run()},[]);
 const rows=useMemo(()=>data?.result?.filter((r:any)=>r.matched&&!r.clean).sort((a:any,b:any)=>score(b)-score(a))||[],[data]);
 const top=rows.slice(0,12);
 const pattern=useMemo(()=>{if(!rows.length)return null;const fields=["goals","assists","shots","pim","games"];return fields.map(f=>({f,count:rows.filter((r:any)=>Number(r.diffs?.[f])!==0).length,sum:rows.reduce((s:number,r:any)=>s+Math.abs(Number(r.diffs?.[f]||0)),0)})).sort((a,b)=>b.count-a.count)},[rows]);
 return <main className="fantasy-shell"><section className="fantasy-hero"><div><p className="fantasy-kicker">STANG INN · 2024/25 · DIAGNOSE</p><h1>Blindtest · råavvik</h1><p className="fantasy-lead">Ingen fantasyregler endres her. Vi isolerer hvilke importerte råfelt som avviker fra HockeyLive.</p></div><a className="pill" href="/fantasy/diagnose/season-validation">← Sesongvalidering</a></section><section className="fantasy-card"><button onClick={run} disabled={busy}>{busy?"Jobber …":"Kjør diagnose på nytt"}</button> <span>{msg}</span>{data&&<><div style={{display:"grid",gridTemplateColumns:"repeat(auto-fit,minmax(150px,1fr))",gap:10,margin:"18px 0"}}>{pattern?.map((x:any)=><div key={x.f} style={{padding:12,borderRadius:12,background:x.count?"#fff4df":"#eefaf2"}}><b>{x.f.toUpperCase()}</b><div style={{fontSize:22,fontWeight:900}}>{x.count}/{rows.length}</div><small>spillere med avvik · absolutt sum {x.sum}</small></div>)}</div><div style={{padding:12,border:"1px solid #b7d7c4",background:"#eefaf2",borderRadius:12,marginBottom:18}}><b>Les dette først:</b> Hvis ett eller to felt dominerer, er det sannsynligvis feltmapping/import. Hvis alle feltene avviker omtrent samtidig, undersøker vi kamp-/turneringsgrunnlaget. K er kun diagnose.</div><h2>Største råavvik · topp {top.length}</h2><div style={{overflowX:"auto"}}><table style={{width:"100%",minWidth:950,borderCollapse:"collapse",fontSize:12}}><thead><tr>{["Spiller","Lag","K vår/HL","G vår/HL","A vår/HL","SOG vår/HL","PIM vår/HL","Profiler","HL-rader"].map(h=><th key={h} style={{padding:7,textAlign:"left",background:"#eef3f8"}}>{h}</th>)}</tr></thead><tbody>{top.map((r:any)=><tr key={r.local.id}><td style={{padding:7,borderBottom:"1px solid #e2e8f0",fontWeight:800}}>{r.local.name}</td><td>{r.local.teams?.join(", ")||r.local.team}</td><td>{r.local.games}/{r.official.games} ({sign(r.diffs.games)})</td><td>{r.local.goals}/{r.official.goals} ({sign(r.diffs.goals)})</td><td>{r.local.assists}/{r.official.assists} ({sign(r.diffs.assists)})</td><td>{r.local.shots}/{r.official.shots} ({sign(r.diffs.shots)})</td><td>{r.local.pim}/{r.official.pim} ({sign(r.diffs.pim)})</td><td>{r.local.duplicateProfiles}</td><td>{r.official.rows}</td></tr>)}</tbody></table></div><h2 style={{marginTop:24}}>Kontrollsignaler</h2><p>Ferdige kamper i databasen: <b>{data.finishedGames}</b> · statrader: <b>{data.statRows}</b> · HockeyLive-rader: <b>{data.officialCount}</b> · lokale spillere: <b>{data.localPlayers}</b> · navnematchet: <b>{data.matched}</b>.</p><p>Lokale navn med flere profiler: <b>{data.duplicateLocalProfiles}</b> · HockeyLive-navn med flere sesongrader: <b>{data.multiTeamOfficial}</b> · fuzzy navnematcher: <b>{data.fuzzyNameMatches}</b> · tvetydige: <b>{data.ambiguousNameMatches}</b>.</p></>}</section></main>
}
