import {NextRequest,NextResponse} from "next/server";
import {createClient} from "@supabase/supabase-js";

export const runtime="nodejs";
export const dynamic="force-dynamic";

async function requireAdmin(request:NextRequest){const url=process.env.NEXT_PUBLIC_SUPABASE_URL,key=process.env.NEXT_PUBLIC_SUPABASE_PUBLISHABLE_KEY;if(!url||!key)return{ok:false as const,response:NextResponse.json({ok:false,error:"Supabase-konfig mangler"},{status:503})};const h=request.headers.get("authorization"),token=h?.startsWith("Bearer ")?h.slice(7):null;if(!token)return{ok:false as const,response:NextResponse.json({ok:false,error:"Mangler innlogging"},{status:401})};const auth=createClient(url,key,{auth:{persistSession:false,autoRefreshToken:false},global:{headers:{Authorization:`Bearer ${token}`}}});const{data:u}=await auth.auth.getUser(token);if(!u.user)return{ok:false as const,response:NextResponse.json({ok:false,error:"Ugyldig innlogging"},{status:401})};const{data:p}=await auth.from("players").select("admin").eq("id",u.user.id).maybeSingle();if(!p?.admin)return{ok:false as const,response:NextResponse.json({ok:false,error:"Kun admin"},{status:403})};return{ok:true as const}}
function rows(payload:any):any[]{if(Array.isArray(payload))return payload;if(!payload||typeof payload!=="object")return[];for(const k of["data","items","players","goalies","goals","penalties","members","result","results"])if(Array.isArray(payload[k]))return payload[k];return[]}
function matchId(externalId:any){const m=String(externalId||"").match(/(\d+)/);return m?Number(m[1]):null}
async function probe(label:string,url:string){try{const r=await fetch(url,{headers:{Accept:"application/json,text/plain,*/*","User-Agent":"StangInn/1.0 historical-probe"},cache:"no-store"});const txt=await r.text();let payload:any=null;try{payload=JSON.parse(txt)}catch{}const rr=rows(payload);return{label,url,status:r.status,ok:r.ok,count:rr.length,sampleKeys:rr[0]?Object.keys(rr[0]).slice(0,25):[],bodyPreview:rr.length?undefined:txt.slice(0,220)}}catch(e:any){return{label,url,status:0,ok:false,count:0,error:e?.message||String(e)}}}
export async function GET(request:NextRequest){const admin=await requireAdmin(request);if(!admin.ok)return admin.response;const season=new URL(request.url).searchParams.get("season")||"2024/25";try{const sb=process.env.NEXT_PUBLIC_SUPABASE_URL,secret=process.env.SUPABASE_SECRET_KEY;if(!sb||!secret)throw new Error("Supabase server-konfig mangler");const db=createClient(sb,secret,{auth:{persistSession:false,autoRefreshToken:false}});const{data:games,error:ge}=await db.from("fantasy_games").select("id,external_id,starts_at,home_team,away_team,home_score,away_score").eq("season",season).order("starts_at");if(ge)throw ge;const ids=(games||[]).map((g:any)=>g.id);const stats:any[]=[];for(let i=0;i<ids.length;i+=300){const{data,error}=await db.from("fantasy_player_game_stats").select("game_id,did_play,position_snapshot").in("game_id",ids.slice(i,i+300));if(error)throw error;stats.push(...(data||[]))}const c=new Map<string,{s:number;g:number}>();for(const r of stats){if(r.did_play===false)continue;const a=c.get(r.game_id)||{s:0,g:0};if(String(r.position_snapshot||"").toUpperCase()==="G")a.g++;else a.s++;c.set(r.game_id,a)}const target=(games||[]).find((g:any)=>{const a=c.get(g.id)||{s:0,g:0};return a.s<20||a.g<2});if(!target)throw new Error("Fant ingen ufullstendig kamp");const mid=matchId(target.external_id);if(!mid)throw new Error("Fant ikke matchId");const root="https://sf34-terminlister-prod-app.azurewebsites.net";const probes=await Promise.all([
probe("legacy players",`${root}/icehockey/Match/Players/${mid}`),
probe("legacy goalies",`${root}/icehockey/Match/GoalieLeaders/${mid}`),
probe("legacy goals",`${root}/icehockey/Match/Goals/${mid}`),
probe("legacy penalties",`${root}/icehockey/Match/Penalties/${mid}`),
probe("TA match members",`${root}/ta/MatchTeamMembers/${mid}`),
probe("api-v1 players",`${root}/api/v1/icehockey/Match/Players/${mid}`),
probe("api-v1 goalies",`${root}/api/v1/icehockey/Match/GoalieLeaders/${mid}`),
probe("api-v1 members",`${root}/api/v1/ta/MatchTeamMembers/${mid}`)
]);return NextResponse.json({ok:true,season,target:{...target,matchId:mid,currentCoverage:c.get(target.id)||{s:0,g:0}},probes});}catch(e:any){return NextResponse.json({ok:false,error:e?.message||"Probe-feil"},{status:500})}}
