"use client";

import {useEffect,useMemo,useState} from "react";
import {getSupabaseBrowserClient} from "../lib/supabase";
import SIIcon,{type SIIconName} from "./SIIcon";
import styles from "./HomeActivityFeed.module.css";

const SEASON="2026/27";
type TransferBatch={batch_id:string;round_no:number;created_at:string;transfer_count:number;incoming:{name:string}[];outgoing:{name:string}[]};
type HistoryRow={round_id:string;round_no:number;deadline_at:string;round_points:number;round_position:number};
type BoosterRow={booster_type:string;activation_status:string;round_no:number|null;deadline_at:string|null};
type FeedItem={id:string;at:string;icon:SIIconName;kicker:string;title:string;detail:string;href:string};
const boosterName=(type:string)=>type==="captain_boost"?"Kapteinsboost":type==="line_boost"?"Rekkeboost":type==="transfer_boost"?"Bytteboost":"Boosterkort";
const pts=(v:number)=>Number(v||0).toFixed(1).replace(".0","");
const when=(v:string)=>new Intl.DateTimeFormat("nb-NO",{day:"2-digit",month:"2-digit",hour:"2-digit",minute:"2-digit",timeZone:"Europe/Oslo"}).format(new Date(v));

export default function HomeActivityFeed({teamId}:{teamId:string|null}){
 const[transfers,setTransfers]=useState<TransferBatch[]>([]),[history,setHistory]=useState<HistoryRow[]>([]),[boosters,setBoosters]=useState<BoosterRow[]>([]),[loading,setLoading]=useState(Boolean(teamId));
 useEffect(()=>{if(!teamId){setTransfers([]);setHistory([]);setBoosters([]);setLoading(false);return}(async()=>{setLoading(true);try{const sb=getSupabaseBrowserClient();if(!sb)return;const transferReq=sb.rpc("get_my_fantasy_transfer_history_v1",{p_season:SEASON});const boosterReq=sb.rpc("get_my_fantasy_boosters_v1",{p_season:SEASON});let historyData:unknown[]|null=null;const v3=await sb.rpc("get_fantasy_team_season_history_v3",{p_team_id:teamId,p_season:SEASON});if(v3.error){const v2=await sb.rpc("get_fantasy_team_season_history_v2",{p_team_id:teamId,p_season:SEASON});if(!v2.error)historyData=v2.data as unknown[]|null}else historyData=v3.data as unknown[]|null;const[{data:t},{data:b}]=await Promise.all([transferReq,boosterReq]);setTransfers(((t||[])as unknown[]).map(raw=>{const x=raw as Record<string,unknown>;return{batch_id:String(x.batch_id),round_no:Number(x.round_no||0),created_at:String(x.created_at||""),transfer_count:Number(x.transfer_count||0),incoming:(x.incoming||[])as {name:string}[],outgoing:(x.outgoing||[])as {name:string}[]}}));setHistory((historyData||[]).map(raw=>{const x=raw as Record<string,unknown>;return{round_id:String(x.round_id||x.round_no),round_no:Number(x.round_no||0),deadline_at:String(x.deadline_at||""),round_points:Number(x.round_points||0),round_position:Number(x.round_position||0)}}));setBoosters(((b||[])as unknown[]).map(raw=>{const x=raw as Record<string,unknown>;return{booster_type:String(x.booster_type||""),activation_status:String(x.activation_status||""),round_no:x.round_no==null?null:Number(x.round_no),deadline_at:x.deadline_at==null?null:String(x.deadline_at)}}))}finally{setLoading(false)}})()},[teamId]);
 const items=useMemo(()=>{const out:FeedItem[]=[];for(const t of transfers){if(!t.created_at)continue;const incoming=t.incoming.map(p=>p.name).filter(Boolean).join(", ");const outgoing=t.outgoing.map(p=>p.name).filter(Boolean).join(", ");out.push({id:`transfer-${t.batch_id}`,at:t.created_at,icon:"transfer",kicker:`Runde ${t.round_no}`,title:`${t.transfer_count} ${t.transfer_count===1?"bytte":"bytter"} gjennomført`,detail:incoming&&outgoing?`${outgoing} → ${incoming}`:"Fantasy-laget ble oppdatert.",href:"/fantasy/transfers"})}for(const r of history){if(!r.deadline_at)continue;out.push({id:`round-${r.round_id}`,at:r.deadline_at,icon:"stats",kicker:`Runde ${r.round_no}`,title:`${pts(r.round_points)} Fantasy-poeng`,detail:r.round_position===1?"Rundeseier":r.round_position?`${r.round_position}. plass i runden`:"Runden er scoret.",href:"/fantasy/leaderboard"})}for(const b of boosters){if(!b.deadline_at||b.round_no==null||!["selected","committed","used"].includes(b.activation_status))continue;out.push({id:`booster-${b.booster_type}-${b.round_no}`,at:b.deadline_at,icon:"booster",kicker:`Runde ${b.round_no}`,title:`${boosterName(b.booster_type)} ${b.activation_status==="selected"?"valgt":"aktivert"}`,detail:b.activation_status==="selected"?"Kortet er valgt før deadline.":"Boosterkortet gjelder denne runden.",href:"/fantasy/team"})}return out.sort((a,b)=>new Date(b.at).getTime()-new Date(a.at).getTime()).slice(0,6)},[transfers,history,boosters]);
 if(!teamId)return <div className={styles.empty}>Aktivitetsfeeden starter når Fantasy-laget ditt er opprettet.</div>;
 if(loading)return <div className={styles.empty}>Laster aktivitet …</div>;
 if(!items.length)return <div className={styles.empty}>Ingen Fantasy-aktivitet ennå. Feed-en fylles når rundene scores, du gjør bytter eller bruker boosterkort.</div>;
 return <div className={styles.feed}>{items.map(item=><a href={item.href} className={styles.item} key={item.id}><span className={styles.icon}><SIIcon name={item.icon} size={18}/></span><span className={styles.copy}><small>{item.kicker} · {when(item.at)}</small><strong>{item.title}</strong><span>{item.detail}</span></span><b>›</b></a>)}</div>;
}
