import {NextRequest,NextResponse} from "next/server";
import {createClient} from "@supabase/supabase-js";

export const runtime="nodejs";
export const dynamic="force-dynamic";

async function requireAdmin(request:NextRequest){const url=process.env.NEXT_PUBLIC_SUPABASE_URL,key=process.env.NEXT_PUBLIC_SUPABASE_PUBLISHABLE_KEY;if(!url||!key)return{ok:false as const,response:NextResponse.json({ok:false,error:"Supabase-konfig mangler"},{status:503})};const h=request.headers.get("authorization"),token=h?.startsWith("Bearer ")?h.slice(7):null;if(!token)return{ok:false as const,response:NextResponse.json({ok:false,error:"Mangler innlogging"},{status:401})};const auth=createClient(url,key,{auth:{persistSession:false,autoRefreshToken:false},global:{headers:{Authorization:`Bearer ${token}`}}});const{data:u}=await auth.auth.getUser(token);if(!u.user)return{ok:false as const,response:NextResponse.json({ok:false,error:"Ugyldig innlogging"},{status:401})};const{data:p}=await auth.from("players").select("admin").eq("id",u.user.id).maybeSingle();if(!p?.admin)return{ok:false as const,response:NextResponse.json({ok:false,error:"Kun admin"},{status:403})};return{ok:true as const}}
function isHistoricalSeason(season:string){return season==="2024/25"||season==="2025/26"}

export async function GET(request:NextRequest){const admin=await requireAdmin(request);if(!admin.ok)return admin.response;const url=new URL(request.url),season=url.searchParams.get("season")||"2024/25";try{const sb=process.env.NEXT_PUBLIC_SUPABASE_URL,secret=process.env.SUPABASE_SECRET_KEY;if(!sb||!secret)throw new Error("Supabase server-konfig mangler");const db=createClient(sb,secret,{auth:{persistSession:false,autoRefreshToken:false}});let q=db.from("fantasy_games").select("id,external_id,starts_at,home_team,away_team,home_score,away_score,status").eq("season",season).order("starts_at");if(!isHistoricalSeason(season))q=q.eq("status","finished");const{data:games,error:ge}=await q;if(ge)throw ge;const gameIds=(games||[]).map((g:any)=>g.id);const stats:any[]=[];
// Avoid Supabase's per-request row cap by querying a small number of games at a time.
// The previous 300-game chunk could return only ~1000 rows and make the rest of the
// season look empty even though the rows existed in the database.
for(let i=0;i<gameIds.length;i+=10){const{data,error}=await db.from("fantasy_player_game_stats").select("game_id,player_id,did_play,position_snapshot").in("game_id",gameIds.slice(i,i+10));if(error)throw error;stats.push(...(data||[]))}const byGame=new Map<string,{total:number;skaters:number;goalies:number}>();for(const s of stats){const a=byGame.get(s.game_id)||{total:0,skaters:0,goalies:0};if(s.did_play!==false){a.total++;if(String(s.position_snapshot||"").toUpperCase()==="G")a.goalies++;else a.skaters++}byGame.set(s.game_id,a)}const rows=(games||[]).map((g:any)=>{const c=byGame.get(g.id)||{total:0,skaters:0,goalies:0};return{...g,...c,healthy:c.skaters>=20&&c.goalies>=2,empty:c.total===0,thin:c.total>0&&(c.skaters<20||c.goalies<2)}});const team=new Map<string,{games:number;healthy:number;thin:number;empty:number;skaters:number}>();for(const r of rows){for(const name of[r.home_team,r.away_team]){const a=team.get(name)||{games:0,healthy:0,thin:0,empty:0,skaters:0};a.games++;a.healthy+=r.healthy?1:0;a.thin+=r.thin?1:0;a.empty+=r.empty?1:0;a.skaters+=r.skaters;team.set(name,a)}}return NextResponse.json({ok:true,season,totalGames:rows.length,finishedGames:rows.filter((r:any)=>r.status==="finished").length,historicalAllGames:isHistoricalSeason(season),statRows:stats.length,healthyGames:rows.filter((r:any)=>r.healthy).length,thinGames:rows.filter((r:any)=>r.thin).length,emptyGames:rows.filter((r:any)=>r.empty).length,queryBatchSize:10,rows:rows.sort((a:any,b:any)=>a.skaters-b.skaters||a.starts_at.localeCompare(b.starts_at)),teams:[...team.entries()].map(([name,v])=>({name,...v,avgSkaters:v.games?v.skaters/v.games:0})).sort((a,b)=>a.avgSkaters-b.avgSkaters)});}catch(e:any){return NextResponse.json({ok:false,error:e?.message||"Coverage-feil"},{status:500})}}
