"use client";

import { useEffect, useState } from "react";
import { getSupabaseBrowserClient } from "../../lib/supabase";
import "./fantasy.css";

type Recommendation={label:string;name:string;detail:string};
type CheckRow={name:string;team:string;position:string;goals:number;assists:number;shots:number;plusMinus:number;pim:number;saves:number;goalsAgainst:number;win:boolean|null;shutout:boolean|null;didPlay:boolean};
const recommendations:Recommendation[]=[
 {label:"🔥 Kjøp",name:"Ingen data ennå",detail:"Aktiveres når spiller- og kampdata er synkronisert."},
 {label:"👑 Kaptein",name:"Ingen data ennå",detail:"Rangeres etter forventede poeng i neste runde."},
 {label:"⚠️ Selg",name:"Ingen data ennå",detail:"Basert på form, pris, kampprogram og forventede poeng."},
];

export default function FantasyPage(){
 const[allowed,setAllowed]=useState<boolean|null>(null),[snapshotBusy,setSnapshotBusy]=useState(false),[snapshotMessage,setSnapshotMessage]=useState(""),[snapshotSeason,setSnapshotSeason]=useState("2025/26"),[probeBusy,setProbeBusy]=useState(false),[probeMessage,setProbeMessage]=useState(""),[importBusy,setImportBusy]=useState(false),[importMessage,setImportMessage]=useState(""),[checkBusy,setCheckBusy]=useState(false),[checkMessage,setCheckMessage]=useState(""),[checkRows,setCheckRows]=useState<CheckRow[]>([]);
 useEffect(()=>{(async()=>{const supabase=getSupabaseBrowserClient();if(!supabase){setAllowed(false);return}const{data:sessionData}=await supabase.auth.getSession();const user=sessionData.session?.user;if(!user){setAllowed(false);return}const{data:player}=await supabase.from("players").select("admin").eq("id",user.id).maybeSingle();setAllowed(Boolean(player?.admin))})()},[]);
 async function token(){const supabase=getSupabaseBrowserClient();const{data}=await supabase?.auth.getSession()??{data:{session:null}};const access=data.session?.access_token;if(!access)throw new Error("Du må være logget inn som admin.");return access}
 async function captureSnapshot(){setSnapshotBusy(true);setSnapshotMessage("");try{const access=await token();const response=await fetch(`/api/fantasy-snapshot?action=capture&season=${encodeURIComponent(snapshotSeason)}`,{method:"POST",headers:{Authorization:`Bearer ${access}`}});const payload=await response.json();if(!response.ok||!payload.ok)throw new Error(payload.error||"Snapshot feilet");const result=payload.result;setSnapshotMessage(`Snapshot ${result.season} lagret: ${result.skaters} utespillere og ${result.goalies} keepere.`)}catch(error:any){setSnapshotMessage(`Kunne ikke ta snapshot: ${error?.message||"ukjent feil"}`)}finally{setSnapshotBusy(false)}}
 async function probeMatch(){setProbeBusy(true);setProbeMessage("");try{const access=await token();const response=await fetch(`/api/fantasy-snapshot?action=probe-match&matchId=8183135`,{method:"POST",headers:{Authorization:`Bearer ${access}`}});const payload=await response.json();if(!response.ok||!payload.ok)throw new Error(payload.error||"Probe feilet");const hits=(payload.result.results||[]).filter((r:any)=>r.ok||r.rowCount!==null);setProbeMessage(hits.length?hits.map((r:any)=>`${r.path} → HTTP ${r.status}${r.rowCount!==null?`, ${r.rowCount} rader`:""}${r.firstKeys?.length?` · felt: ${r.firstKeys.join(", ")}`:""}`).join(" | "):"Ingen kandidat-ruter ga strukturerte data.")}catch(error:any){setProbeMessage(`Kunne ikke teste kampdata: ${error?.message||"ukjent feil"}`)}finally{setProbeBusy(false)}}
 async function importMatch(){setImportBusy(true);setImportMessage("");try{const access=await token();const response=await fetch(`/api/fantasy-import?matchId=8183135&season=2025%2F26&tournamentId=435587`,{method:"POST",headers:{Authorization:`Bearer ${access}`}});const payload=await response.json();if(!response.ok||!payload.ok)throw new Error(payload.error||"Import feilet");const r=payload.result;const e=r.enrichment;setImportMessage(`Importert ${r.game.home} ${r.game.homeScore}–${r.game.awayScore} ${r.game.away}: ${r.importedSkaters} utespillere + ${r.importedGoalies} keepere.${e?` Berikelse: ${e.positionsUpdated} posisjoner, ${e.plusMinusUpdated} +/−-rader, ${e.plusMinusCountedGoals} tellende mål.`:""}`)}catch(error:any){setImportMessage(`Kunne ikke importere kamp: ${error?.message||"ukjent feil"}`)}finally{setImportBusy(false)}}
 async function loadCheck(){setCheckBusy(true);setCheckMessage("");try{const access=await token();const response=await fetch(`/api/fantasy-match-check?matchId=8183135`,{headers:{Authorization:`Bearer ${access}`}});const payload=await response.json();if(!response.ok||!payload.ok)throw new Error(payload.error||"Kontroll feilet");setCheckRows(payload.result.rows||[]);setCheckMessage(`${payload.result.game.home_team} ${payload.result.game.home_score}–${payload.result.game.away_score} ${payload.result.game.away_team} · ${payload.result.rows?.length||0} spillerrader`) }catch(error:any){setCheckMessage(`Kunne ikke hente kontroll: ${error?.message||"ukjent feil"}`)}finally{setCheckBusy(false)}}
 if(allowed===null)return <main className="fantasy-shell"><p className="fantasy-lead">Sjekker admin-tilgang …</p></main>;
 if(!allowed)return <main className="fantasy-shell"><section className="fantasy-card"><p className="eyebrow">ADMIN ONLY</p><h1>Ingen tilgang</h1><p className="card-copy">Fantasy Hockey er bare tilgjengelig for administratorer.</p><a href="/" className="pill" style={{textDecoration:"none",display:"inline-block",marginTop:12}}>← Tilbake til Stang Inn</a></section></main>;
 return <main className="fantasy-shell">
  <section className="fantasy-hero"><div><p className="fantasy-kicker">STANG INN · ADMIN · FANTASY HOCKEY</p><h1>Fantasy-sentralen</h1><p className="fantasy-lead">Automatisk spillerstatistikk, 19Fantasy-poeng, form, kampprogram og anbefalte bytter – uten regneark.</p></div><div className="fantasy-status"><span className="status-dot"/>Admin only</div></section>
  <section className="fantasy-metrics"><article><span>Lagverdi</span><strong>—</strong><small>Kobles til ditt fantasy-lag</small></article><article><span>Forventede poeng</span><strong>—</strong><small>Neste runde</small></article><article><span>Formspiller</span><strong>—</strong><small>Siste 5 kamper</small></article><article><span>Beste verdi</span><strong>—</strong><small>Poeng per million</small></article></section>
  <section className="fantasy-grid">
   <div className="fantasy-card fantasy-main-card"><div className="card-heading"><div><p className="eyebrow">RUNDEANALYSE</p><h2>Anbefalinger</h2></div><span className="pill">Neste runde</span></div><div className="recommendation-list">{recommendations.map(item=><div className="recommendation" key={item.label}><span className="recommendation-label">{item.label}</span><div><strong>{item.name}</strong><p>{item.detail}</p></div></div>)}</div></div>
   <div className="fantasy-card"><p className="eyebrow">DATASYNK</p><h2>Historisk test 2025/26</h2><p className="card-copy">Testkamp 8183135 brukes til å kontrollere hele kampimporten før 2026/27.</p><button type="button" onClick={importMatch} disabled={importBusy}>{importBusy?"Importerer …":"Importer kamp 8183135"}</button>{importMessage?<p className="card-copy" style={{marginTop:10}}>{importMessage}</p>:null}<button type="button" onClick={loadCheck} disabled={checkBusy} style={{marginTop:10}}>{checkBusy?"Henter kontroll …":"Vis kontrolltabell"}</button>{checkMessage?<p className="card-copy" style={{marginTop:10}}>{checkMessage}</p>:null}</div>
   <div className="fantasy-card"><p className="eyebrow">KOMMENDE KAMPER</p><h2>Fixture rating</h2><div className="empty-state"><p>Terminlisten kobles til automatisk EHL-synk.</p></div></div>
   <div className="fantasy-card"><p className="eyebrow">BYTTEVERKTØY</p><h2>Optimaliser laget</h2><p className="card-copy">Velg budsjett og maks antall bytter. Motoren foreslår beste kombinasjon basert på forventede poeng og kampprogram.</p><button type="button" disabled>Kommer i neste steg</button></div>
  </section>
  {checkRows.length?<section className="fantasy-card" style={{overflowX:"auto"}}><p className="eyebrow">KONTROLL · KAMP 8183135</p><h2>Importert kampstatistikk</h2><table style={{width:"100%",borderCollapse:"collapse",minWidth:850,color:"#102033"}}><thead><tr>{["Spiller","Lag","Pos","G","A","SOG","+/−","PIM","SV","GA"].map(h=><th key={h} style={{textAlign:"left",padding:"9px 8px",borderBottom:"1px solid #cbd5e1"}}>{h}</th>)}</tr></thead><tbody>{checkRows.map((r,i)=><tr key={`${r.name}-${i}`}><td style={{padding:"8px",borderBottom:"1px solid #e2e8f0",fontWeight:700}}>{r.name}</td><td style={{padding:"8px",borderBottom:"1px solid #e2e8f0"}}>{r.team}</td><td style={{padding:"8px",borderBottom:"1px solid #e2e8f0"}}>{r.position}</td><td style={{padding:"8px",borderBottom:"1px solid #e2e8f0"}}>{r.goals}</td><td style={{padding:"8px",borderBottom:"1px solid #e2e8f0"}}>{r.assists}</td><td style={{padding:"8px",borderBottom:"1px solid #e2e8f0"}}>{r.shots}</td><td style={{padding:"8px",borderBottom:"1px solid #e2e8f0"}}>{r.plusMinus>0?`+${r.plusMinus}`:r.plusMinus}</td><td style={{padding:"8px",borderBottom:"1px solid #e2e8f0"}}>{r.pim}</td><td style={{padding:"8px",borderBottom:"1px solid #e2e8f0"}}>{r.position==="G"?r.saves:"—"}</td><td style={{padding:"8px",borderBottom:"1px solid #e2e8f0"}}>{r.position==="G"?r.goalsAgainst:"—"}</td></tr>)}</tbody></table></section>:null}
  <section className="fantasy-card build-status"><div><p className="eyebrow">STATUS</p><h2>Første MVP</h2></div><div className="status-steps"><span className="done">✓ Admin-låst</span><span className="done">✓ Datamodell</span><span className="done">✓ Kampdatakilde</span><span className="done">✓ Kampimport</span><span>○ Poengmotor</span><span>○ Anbefalingsmotor</span></div></section>
 </main>;
}
