"use client";

import { useEffect, useState } from "react";
import { getSupabaseBrowserClient } from "../../../lib/supabase";

type RoundRow={round_id:string;round_no:number;round_name:string|null;starts_at:string|null;deadline_at:string;ends_at:string|null;status:string;game_count:number;snapshot_count:number};
type GameSummary={id:string;round_no:number|null;fantasy_round_id:string|null};

export default function FantasyRoundsPage(){
 const season="2026/27",tournamentId="448981";
 const[allowed,setAllowed]=useState<boolean|null>(null),[busy,setBusy]=useState(false),[message,setMessage]=useState(""),[rounds,setRounds]=useState<RoundRow[]>([]),[games,setGames]=useState<GameSummary[]>([]);
 useEffect(()=>{(async()=>{const sb=getSupabaseBrowserClient();if(!sb){setAllowed(false);return}const{data:s}=await sb.auth.getSession();const user=s.session?.user;if(!user){setAllowed(false);return}const{data:p}=await sb.from("players").select("admin").eq("id",user.id).maybeSingle();setAllowed(Boolean(p?.admin))})()},[]);
 async function load(){const sb=getSupabaseBrowserClient();if(!sb)return;const[{data:r,error:re},{data:g,error:ge}]=await Promise.all([sb.rpc("get_fantasy_round_admin_overview",{p_season:season}),sb.from("fantasy_games").select("id,round_no,fantasy_round_id").eq("season",season)]);if(re||ge){setMessage(`Kunne ikke hente rundekontroll: ${re?.message||ge?.message}`);return}setRounds((r||[]) as RoundRow[]);setGames((g||[]) as GameSummary[])}
 useEffect(()=>{if(allowed)load()},[allowed]);
 async function accessToken(){const sb=getSupabaseBrowserClient();if(!sb)throw new Error("Supabase er ikke tilgjengelig");const{data}=await sb.auth.getSession();if(!data.session?.access_token)throw new Error("Du må være logget inn som admin");return data.session.access_token}
 async function sync(){setBusy(true);setMessage("Henter 2026/27-terminlisten fra HockeyLive …");try{const sb=getSupabaseBrowserClient();if(!sb)throw new Error("Supabase er ikke tilgjengelig");const token=await accessToken();const prep=await fetch(`/api/fantasy-season-prepare?season=${encodeURIComponent(season)}&tournamentId=${tournamentId}`,{method:"POST",headers:{Authorization:`Bearer ${token}`}});const p=await prep.json();if(!prep.ok||!p.ok)throw new Error(p.error||`Terminlisteimport feilet (${prep.status})`);const info=p.result||{};if(!info.totalMatches)throw new Error("HockeyLive ga 0 gyldige kamper");const{data,error}=await sb.rpc("sync_fantasy_rounds_from_games",{p_season:season});if(error)throw error;const row=Array.isArray(data)?data[0]:data;await load();const sample=(info.sampleStartFields||[]).map((x:any)=>`${x.matchId}: ${x.matchDate||x.matchStartDate||"?"} ${x.matchStartTime||"?"} → ${x.parsed||"?"}`).join(" | ");setMessage(`Terminliste: ${info.totalMatches} kamper · ${info.matchesWithRoundNo??0} med rundenummer${info.roundsDerived?` · ${info.derivedRoundCount} runder utledet`:""}. Rundesynk: ${row?.rounds_upserted??0} runder · ${row?.games_linked??0} kampkoblinger.${sample?` Tidsprøve: ${sample}`:""}`)}catch(e:any){setMessage(`Synk stoppet: ${e?.message||"ukjent feil"}`)}finally{setBusy(false)}}
 const linked=games.filter(g=>g.fantasy_round_id).length,withRound=games.filter(g=>g.round_no!=null).length,fmt=(v:string|null)=>v?new Intl.DateTimeFormat("nb-NO",{dateStyle:"medium",timeStyle:"short",timeZone:"Europe/Oslo"}).format(new Date(v)):"—";
 if(allowed===null)return <main style={{maxWidth:1100,margin:"40px auto",padding:20}}>Sjekker admin-tilgang …</main>;if(!allowed)return <main style={{maxWidth:1100,margin:"40px auto",padding:20}}><h1>Ingen tilgang</h1></main>;
 return <main style={{maxWidth:1100,margin:"40px auto",padding:20,fontFamily:"system-ui"}}><p style={{fontWeight:700,letterSpacing:1,fontSize:12}}>STANG INN · ADMIN</p><h1>Fantasy-runder 2026/27</h1><p>Rundene bygges fra EHL-terminlisten. Deadline er første kampstart i hver runde.</p><div style={{display:"flex",gap:12,alignItems:"center",flexWrap:"wrap",margin:"20px 0"}}><button onClick={sync} disabled={busy} style={{padding:"10px 16px"}}>{busy?"Synkroniserer …":"Hent terminliste og synk runder"}</button><button onClick={load} disabled={busy} style={{padding:"10px 16px"}}>Oppdater kontroll</button><b>{rounds.length} runder · {linked}/{games.length} kamper koblet · {withRound}/{games.length} med round_no</b></div>{message&&<p style={{padding:12,background:"#fff",color:"#000",border:"1px solid #e5e7eb",borderRadius:10}}>{message}</p>}<div style={{overflowX:"auto"}}><table style={{width:"100%",borderCollapse:"collapse",fontSize:14}}><thead><tr><th style={{textAlign:"left",padding:8}}>Runde</th><th style={{textAlign:"left",padding:8}}>Deadline</th><th style={{textAlign:"left",padding:8}}>Siste kamp / slutt</th><th style={{textAlign:"left",padding:8}}>Status</th><th style={{textAlign:"right",padding:8}}>Kamper</th><th style={{textAlign:"right",padding:8}}>Snapshots</th></tr></thead><tbody>{rounds.map(r=><tr key={r.round_id} style={{borderTop:"1px solid #e5e7eb"}}><td style={{padding:8}}><b>{r.round_name||`Runde ${r.round_no}`}</b></td><td style={{padding:8}}>{fmt(r.deadline_at)}</td><td style={{padding:8}}>{fmt(r.ends_at)}</td><td style={{padding:8}}>{r.status}</td><td style={{padding:8,textAlign:"right"}}><b>{r.game_count}</b></td><td style={{padding:8,textAlign:"right"}}>{r.snapshot_count}</td></tr>)}</tbody></table></div>{rounds.length===0&&<p style={{marginTop:20}}>Ingen fantasy-runder er opprettet ennå.</p>}</main>;
}
