"use client";

import {useMemo,useState} from "react";
import {getSupabaseBrowserClient} from "../../../../lib/supabase";
import {HISTORICAL_PRICES_2025} from "../../../../lib/fantasy/historical-prices-2025";
import {preEhlBacktestHistoryFor} from "../../../../lib/fantasy/import-backtest-history-2025";
import {importHistoryFor,type ImportHistory} from "../../../../lib/fantasy/import-history-2026";
import {importEstimateV43,type V43Position} from "../../../../lib/fantasy/import-pricing-v4-3";
import {importEstimateV46} from "../../../../lib/fantasy/import-pricing-v4-6";
import "../../fantasy.css";

const S24="2024/25",S25="2025/26",VALID=new Set(["C","W","D","G"]);
const norm=(v:any)=>String(v??"").toLocaleLowerCase("nb-NO").normalize("NFD").replace(/[\u0300-\u036f]/g,"").replace(/ø/g,"o").replace(/æ/g,"ae").replace(/[^a-z0-9]+/g," ").trim();
const natural=(s:string)=>{const[last,...r]=String(s||"").split(",");return r.length?`${r.join(",").trim()} ${last.trim()}`:String(s||"")};
const arr=(s:string)=>norm(s).split(" ").filter(Boolean).filter(x=>x!=="jr"&&x!=="junior"),tok=(s:string)=>new Set(arr(s));
function score(a:string,b:string){if(norm(a)===norm(natural(b)))return 1000;const A=tok(a),B=tok(natural(b));let c=0;for(const x of A)if(B.has(x))c++;const mn=Math.min(A.size,B.size),mx=Math.max(A.size,B.size);return c===mn&&mn>=2?800+c*10-mn*Math.abs(mx-mn):c>=2?c*100-Math.abs(A.size-B.size)*10:0}
function best(name:string,src:any[]){let row:any=null,bs=0;for(const x of src){const s=score(name,x.name??x[0]);if(s>bs){bs=s;row=x}}return bs>=800?row:null}
async function auth(){const s=getSupabaseBrowserClient(),{data}=await s!.auth.getSession();if(!data.session?.access_token)throw new Error("Logg inn som admin");return data.session.access_token}
function canonTeam(v:any){const s=norm(v);if(s.includes("storhamar"))return"Storhamar";if(s.includes("stavanger")||s.includes("oilers"))return"Stavanger";if(s.includes("valerenga"))return"Vålerenga";if(s.includes("frisk"))return"Frisk Asker";if(s.includes("sparta"))return"Sparta";if(s.includes("narvik"))return"Narvik";if(s.includes("stjernen"))return"Stjernen";if(s.includes("lillehammer"))return"Lillehammer";if(s.includes("ringerike"))return"Ringerike";if(s.includes("nidaros"))return"Nidaros";return String(v||"").trim()}
const avg=(xs:number[])=>xs.length?xs.reduce((a,b)=>a+b,0)/xs.length:0;
const mae=(xs:number[])=>xs.length?avg(xs.map(Math.abs)):0;
const rmse=(xs:number[])=>xs.length?Math.sqrt(avg(xs.map(x=>x*x))):0;

type HRow={name:string;team:string;pos:string;start:number;track:string;league:string;games:number;ppg:number|null;sv:number|null;gaa:number|null};
type Model=HRow&{v43:number;v46:number;e43:number;e46:number;delta:number};
type Current={name:string;team:string;pos:string;league:string;metric:string;v43:number;v46:number;delta:number;basis:string};
function hist(r:HRow):ImportHistory|null{if(r.pos==="G"){if(r.sv==null||r.gaa==null)return null;return{kind:"goalie",season:"2025/26",previousTeam:"historical",league:r.league,games:r.games,savePct:r.sv,gaa:r.gaa,source:"EliteProspects"}}if(r.ppg==null)return null;return{kind:"skater",season:"2025/26",previousTeam:"historical",league:r.league,games:r.games,goals:0,assists:r.ppg*r.games,points:r.ppg*r.games,source:"EliteProspects"}}

export default function Page(){const[busy,setBusy]=useState(false),[msg,setMsg]=useState("Klar for V4.6"),[models,setModels]=useState<Model[]>([]),[current,setCurrent]=useState<Current[]>([]);
async function run(){setBusy(true);try{const t=await auth();const[a,b,c]=await Promise.all([fetch(`/api/fantasy-player-form?season=${encodeURIComponent(S24)}`,{headers:{Authorization:`Bearer ${t}`}}),fetch(`/api/fantasy-player-form?season=${encodeURIComponent(S25)}`,{headers:{Authorization:`Bearer ${t}`}}),fetch('/api/fantasy-roster-enriched-2026',{cache:'no-store'})]);const p24=await a.json(),p25=await b.json(),roster=await c.json();if(!a.ok||!p24.ok||!b.ok||!p25.ok||!c.ok||!roster.ok)throw new Error("Kunne ikke hente backtest-data");const old=p24.result?.rows||[],cur=p25.result?.rows||[],rows:HRow[]=[];for(const p of cur){if(Number(p.games||0)<10||!VALID.has(String(p.position||"")))continue;const prev=best(String(p.name),old);if(prev&&Number(prev.games||0)>=3)continue;const pr=best(String(p.name),HISTORICAL_PRICES_2025 as any[]),h=preEhlBacktestHistoryFor(String(p.name));if(!pr||!h)continue;rows.push({name:String(p.name),team:String(p.team||pr?.[1]||""),pos:String(p.position),start:Number(pr[2])/1e6,track:h.track,league:h.league,games:h.games,ppg:h.points!=null?h.points/h.games:null,sv:h.savePct??null,gaa:h.gaa??null})}
const out:Model[]=[];for(const r of rows){const h=hist(r);if(!h)continue;const v43=importEstimateV43(h,r.pos as V43Position,canonTeam(r.team),r.name),v46=importEstimateV46(h,r.pos as V43Position,canonTeam(r.team),r.name);if(!v43||!v46)continue;out.push({...r,v43:v43.raw,v46:v46.raw,e43:v43.raw-r.start,e46:v46.raw-r.start,delta:v46.raw-v43.raw})}setModels(out);
const ci:Current[]=[];for(const r of roster.rows||[]){const name=String(r.name||""),pos=String(r.position||"").toUpperCase();if(!VALID.has(pos))continue;const h=importHistoryFor(name);if(!h)continue;const team=canonTeam(r.team),v43=importEstimateV43(h,pos as V43Position,team,name),v46=importEstimateV46(h,pos as V43Position,team,name);if(!v43||!v46)continue;ci.push({name,team,pos,league:h.league,metric:v43.metric,v43:v43.raw,v46:v46.raw,delta:v46.raw-v43.raw,basis:v46.empiricalBasis})}ci.sort((x,y)=>Math.abs(y.delta)-Math.abs(x.delta));setCurrent(ci);setMsg(`Ferdig · ${out.length} historiske observasjoner · ${ci.length} årets importer`)}catch(e:any){setMsg(`Feil: ${e.message||e}`)}finally{setBusy(false)}}
const metrics=useMemo(()=>({n:models.length,mae43:mae(models.map(x=>x.e43)),rmse43:rmse(models.map(x=>x.e43)),mae46:mae(models.map(x=>x.e46)),rmse46:rmse(models.map(x=>x.e46)),bias43:avg(models.map(x=>x.e43)),bias46:avg(models.map(x=>x.e46))}),[models]);
const groups=useMemo(()=>["senior-import","norway2-transition","junior/talent"].map(k=>{const rs=models.filter(x=>x.track===k);return{k,n:rs.length,m43:mae(rs.map(x=>x.e43)),m46:mae(rs.map(x=>x.e46)),bias:avg(rs.map(x=>x.e46))}}).filter(x=>x.n),[models]);
return <main className="fantasy-page"><section className="fantasy-card"><h1>V4.6 · Guarded production candidate</h1><p>Seniorimporter får full empirisk V4.5.8-kalibrering, Norway2 får kun 25% av empirisk flytt med maks ±0.30m, og junior/talent beholder V4.3.3 uendret. Dette er fortsatt en kandidat og skriver ikke produksjonspriser.</p><button onClick={run} disabled={busy}>{busy?"Tester…":"Kjør V4.6 kandidat-backtest"}</button><p><strong>{msg}</strong></p></section>{models.length>0&&<><section className="fantasy-card"><h2>Historisk modelltest</h2><table><thead><tr><th>Modell</th><th>N</th><th>MAE</th><th>RMSE</th><th>Bias</th></tr></thead><tbody><tr><td>V4.3.3</td><td>{metrics.n}</td><td>{metrics.mae43.toFixed(2)}m</td><td>{metrics.rmse43.toFixed(2)}m</td><td>{metrics.bias43>=0?"+":""}{metrics.bias43.toFixed(2)}m</td></tr><tr><td><strong>V4.6 kandidat</strong></td><td>{metrics.n}</td><td><strong>{metrics.mae46.toFixed(2)}m</strong></td><td><strong>{metrics.rmse46.toFixed(2)}m</strong></td><td>{metrics.bias46>=0?"+":""}{metrics.bias46.toFixed(2)}m</td></tr></tbody></table><p>MAE-endring: <strong>{(metrics.mae46-metrics.mae43).toFixed(2)}m</strong> · RMSE-endring: <strong>{(metrics.rmse46-metrics.rmse43).toFixed(2)}m</strong></p><h3>Track-kontroll</h3><table><thead><tr><th>Track</th><th>N</th><th>V4.3.3 MAE</th><th>V4.6 MAE</th><th>V4.6 bias</th></tr></thead><tbody>{groups.map(g=><tr key={g.k}><td>{g.k}</td><td>{g.n}</td><td>{g.m43.toFixed(2)}m</td><td><strong>{g.m46.toFixed(2)}m</strong></td><td>{g.bias>=0?"+":""}{g.bias.toFixed(2)}m</td></tr>)}</tbody></table></section><section className="fantasy-card"><h2>2026/27-importer · V4.3.3 mot V4.6 kandidat</h2><table><thead><tr><th>Spiller</th><th>Lag</th><th>Pos</th><th>Liga</th><th>Metric</th><th>V4.3.3</th><th>V4.6</th><th>Δ</th><th>Guardrail</th></tr></thead><tbody>{current.map(r=><tr key={r.name}><td>{r.name}</td><td>{r.team}</td><td>{r.pos}</td><td>{r.league}</td><td>{r.metric}</td><td>{r.v43.toFixed(1)}m</td><td><strong>{r.v46.toFixed(1)}m</strong></td><td>{r.delta>=0?"+":""}{r.delta.toFixed(1)}m</td><td>{r.basis}</td></tr>)}</tbody></table></section></>}</main>}
