"use client";
import {useEffect,useMemo,useState} from "react";
import {getSupabaseBrowserClient} from "../../../../lib/supabase";
import "../../fantasy.css";import "../xfp-admin.css";

type Row={id:string;name:string;team:string;position:string;availability:{status:string;note?:string|null;expected_return?:string|null;source_url?:string|null;source_label?:string|null;updated_at?:string|null}};
const labels:any={available:"🟢 Kampklar",questionable:"🟡 Usikker",out:"🔴 Bekreftet ute",long_term:"⛔ Langtidsskadd",returning:"🔵 Tilbake i trening"};
export default function AvailabilityPage(){const[token,setToken]=useState<string|null>(null),[rows,setRows]=useState<Row[]>([]),[q,setQ]=useState(""),[team,setTeam]=useState("ALL"),[msg,setMsg]=useState("Laster …"),[busy,setBusy]=useState<string|null>(null);
 async function load(t=token){if(!t)return;const r=await fetch("/api/admin/fantasy/availability",{headers:{Authorization:`Bearer ${t}`},cache:"no-store"});const b=await r.json();if(!r.ok||!b.ok)throw new Error(b.error||"Kunne ikke laste");setRows(b.rows||[]);setMsg(`${(b.rows||[]).length} spillere`)}
 useEffect(()=>{(async()=>{try{const s=getSupabaseBrowserClient();const{data}=await s!.auth.getSession();const t=data.session?.access_token;if(!t)throw new Error("Du må være logget inn");setToken(t);await load(t)}catch(e:any){setMsg(e.message)}})()},[]);
 async function save(r:Row,status:string){if(!token)return;setBusy(r.id);try{const note=window.prompt("Notat / bekreftet informasjon (valgfritt)",r.availability.note||"")||"";const sourceUrl=window.prompt("Kilde-URL (anbefalt ved skade/usikkerhet)",r.availability.source_url||"")||"";const sourceLabel=sourceUrl?(window.prompt("Kildenavn",r.availability.source_label||"nitten.no")||""):"";const res=await fetch("/api/admin/fantasy/availability",{method:"POST",headers:{Authorization:`Bearer ${token}`,"Content-Type":"application/json"},body:JSON.stringify({playerId:r.id,status,note,sourceUrl,sourceLabel})});const b=await res.json();if(!res.ok||!b.ok)throw new Error(b.error||"Lagring feilet");await load(token);setMsg(`✓ ${r.name}: ${labels[status]}`)}catch(e:any){setMsg(e.message)}finally{setBusy(null)}}
 const teams=useMemo(()=>[...new Set(rows.map(r=>r.team))].sort((a,b)=>a.localeCompare(b,"nb")),[rows]);const shown=rows.filter(r=>(team==="ALL"||r.team===team)&&(!q||`${r.name} ${r.team}`.toLowerCase().includes(q.toLowerCase())));
 return <main className="fantasy-shell xfp-command-center"><section className="xfp-command-hero"><p className="fantasy-kicker">STANG INN · ADMIN ANALYSE</p><h1>Skader & tilgjengelighet</h1><p>Dokumentert spillerstatus. Foreløpig påvirker dette ikke xFP eller optimizer.</p></section><section className="xfp-panel"><div className="xfp-panel-head"><div><p className="eyebrow">AVAILABILITY v1</p><h2>Spillerstatus</h2><p>Bekreftet ute bør ha dokumentert kilde. Manglende lineup alene er ikke nok.</p></div><a className="xfp-secondary" href="/fantasy/admin-analysis">← Kommandosenter</a></div><div style={{display:"flex",gap:10,flexWrap:"wrap",margin:"14px 0"}}><input className="xfp-search" placeholder="Søk spiller …" value={q} onChange={e=>setQ(e.target.value)}/><select className="xfp-select" value={team} onChange={e=>setTeam(e.target.value)}><option value="ALL">Alle lag</option>{teams.map(t=><option key={t}>{t}</option>)}</select></div><p className="preseason-message">{msg}</p><div className="preseason-table-wrap"><table className="preseason-table"><thead><tr><th>Spiller</th><th>Lag</th><th>Status</th><th>Notat/kilde</th><th>Endre</th></tr></thead><tbody>{shown.map(r=><tr key={r.id}><td><strong>{r.name}</strong><small>{r.position}</small></td><td>{r.team}</td><td>{labels[r.availability.status]||r.availability.status}</td><td>{r.availability.note||"—"}{r.availability.source_url&&<small><a href={r.availability.source_url} target="_blank" rel="noreferrer">{r.availability.source_label||"Kilde"}</a></small>}</td><td><select disabled={busy===r.id} value={r.availability.status||"available"} onChange={e=>save(r,e.target.value)}>{Object.entries(labels).map(([k,v])=><option key={k} value={k}>{String(v)}</option>)}</select></td></tr>)}</tbody></table></div></section></main>}
