import { NextRequest, NextResponse } from "next/server";
import { createClient } from "@supabase/supabase-js";

export const runtime = "nodejs";
export const dynamic = "force-dynamic";

const BASE = "https://sf34-terminlister-prod-app.azurewebsites.net/";
type Row = Record<string, any>;
const num=(v:any,f=0)=>Number.isFinite(Number(v))?Number(v):f;
const nk=(v:any)=>String(v??"").toLocaleLowerCase("nb-NO").normalize("NFD").replace(/[\u0300-\u036f]/g,"").replace(/[^a-z0-9]+/g," ").trim();
const tokens=(v:any)=>nk(v).split(/\s+/).filter(Boolean);
function sameName(a:any,b:any){const ak=nk(a),bk=nk(b);if(ak===bk)return true;const at=tokens(a),bt=tokens(b);return at.length>=2&&bt.length>=2&&at[0]===bt[0]&&at.at(-1)===bt.at(-1)}
function rows(p:any){if(Array.isArray(p))return p;if(Array.isArray(p?.data))return p.data;if(Array.isArray(p?.goalies))return p.goalies;if(Array.isArray(p?.data?.goalies))return p.data.goalies;return []}
const rawSeconds=(r:any)=>num(r?.secondsPlayed??r?.SecondsPlayed??r?.playerTimeSeconds??r?.PlayerTimeSeconds,0);
function teamKey(v:any){const s=nk(v);for(const [k,parts] of Object.entries({nidaros:["nidaros"],lorenskog:["lorenskog"],storhamar:["storhamar"],oilers:["stavanger","oilers"],valerenga:["valerenga"],frisk:["frisk"],sparta:["sparta"],narvik:["narvik"],stjernen:["stjernen"],lillehammer:["lillehammer"],ringerike:["ringerike"]}) as any)if(parts.some((x:string)=>s.includes(x)))return k;return s}
async function requireAdmin(request:NextRequest){const url=process.env.NEXT_PUBLIC_SUPABASE_URL,key=process.env.NEXT_PUBLIC_SUPABASE_PUBLISHABLE_KEY;if(!url||!key)return{ok:false as const,response:NextResponse.json({ok:false,error:"Supabase public-konfigurasjon mangler."},{status:503})};const h=request.headers.get("authorization"),token=h?.startsWith("Bearer ")?h.slice(7):null;if(!token)return{ok:false as const,response:NextResponse.json({ok:false,error:"Mangler innlogging."},{status:401})};const auth=createClient(url,key,{auth:{persistSession:false,autoRefreshToken:false},global:{headers:{Authorization:`Bearer ${token}`}}});const{data:u,error:e}=await auth.auth.getUser(token);if(e||!u.user)return{ok:false as const,response:NextResponse.json({ok:false,error:"Ugyldig innlogging."},{status:401})};const{data:p}=await auth.from("players").select("admin").eq("id",u.user.id).maybeSingle();if(!p?.admin)return{ok:false as const,response:NextResponse.json({ok:false,error:"Kun admin."},{status:403})};return{ok:true as const}}

export async function POST(request:NextRequest){const admin=await requireAdmin(request);if(!admin.ok)return admin.response;const url=new URL(request.url),season=url.searchParams.get("season")||"2025/26",tournamentId=(url.searchParams.get("tournamentId")||"435587").replace(/\D/g,"");try{const secret=process.env.SUPABASE_SECRET_KEY,base=process.env.NEXT_PUBLIC_SUPABASE_URL;if(!secret||!base)throw new Error("Supabase server-konfigurasjon mangler");const db=createClient(base,secret,{auth:{persistSession:false,autoRefreshToken:false}});const hr=await fetch(`${BASE}icehockey/TournamentGoalieLeaders/${tournamentId}`,{headers:{Accept:"application/json","User-Agent":"StangInn/1.0 goalie-reconcile"},cache:"no-store"});if(!hr.ok)throw new Error(`HockeyLive svarte ${hr.status}`);const official=rows(await hr.json());const{data:players,error:pe}=await db.from("fantasy_players").select("id,name,team,position").eq("position","G");if(pe)throw pe;const{data:games,error:ge}=await db.from("fantasy_games").select("id,home_team,away_team,home_score,away_score,season,starts_at").eq("season",season);if(ge)throw ge;const gameMap=new Map((games||[]).map((g:any)=>[g.id,g])),playerMap=new Map((players||[]).map((p:any)=>[p.id,p])),playerIds=(players||[]).map((p:any)=>p.id);const{data:stats,error:se}=playerIds.length?await db.from("fantasy_player_game_stats").select("id,player_id,game_id,saves,goals_against,minutes_played,shutout,team_snapshot,raw").in("player_id",playerIds):{data:[],error:null};if(se)throw se;const byPlayer=new Map<string,any[]>(),byGame=new Map<string,any[]>();for(const s of stats||[]){byPlayer.set(s.player_id,[...(byPlayer.get(s.player_id)||[]),s]);byGame.set(s.game_id,[...(byGame.get(s.game_id)||[]),s])}const groups=new Map<string,any[]>();for(const p of players||[])groups.set(nk(p.name),[...(groups.get(nk(p.name))||[]),p]);const results:any[]=[];
for(const group of groups.values()){const p=group[0],off=official.find((r:Row)=>sameName(`${r.firstName??""} ${r.lastName??""}`,p.name));if(!off)continue;const target=num(off.so,0),ids=new Set(group.map((x:any)=>x.id)),ps=group.flatMap((x:any)=>byPlayer.get(x.id)||[]),candidateGames:any[]=[],rejectedGames:any[]=[];
for(const s of ps){const g:any=gameMap.get(s.game_id);if(!g)continue;const profile:any=playerMap.get(s.player_id),statTeam=s.team_snapshot||profile?.team||p.team,pk=teamKey(statTeam),hk=teamKey(g.home_team),ak=teamKey(g.away_team),home=pk===hk,away=pk===ak;if(!home&&!away)continue;const opp=home?num(g.away_score,-1):num(g.home_score,-1),own=home?num(g.home_score,-1):num(g.away_score,-1);const sameTeam=(byGame.get(s.game_id)||[]).filter((x:any)=>teamKey(x.team_snapshot||(playerMap.get(x.player_id) as any)?.team)===pk),other=sameTeam.filter((x:any)=>!ids.has(x.player_id)&&(num(x.saves)>0||num(x.goals_against)>0||rawSeconds(x.raw)>0||num(x.minutes_played)>0));const reasons:string[]=[];if(opp!==0)reasons.push(`laget slapp inn ${opp}`);if(own<=0)reasons.push("laget scoret ikke");if(num(s.goals_against)!==0)reasons.push(`keeper GA ${num(s.goals_against)}`);if(num(s.saves)<=0)reasons.push("0 redninger");if(other.length)reasons.push(`annen aktiv keeper: ${other.map((o:any)=>(playerMap.get(o.player_id) as any)?.name||o.player_id).join(", ")}`);const info={gameId:s.game_id,date:g.starts_at??null,homeTeam:g.home_team??"",awayTeam:g.away_team??"",score:`${g.home_score??"–"}–${g.away_score??"–"}`,side:home?"H":"B",teamSnapshot:statTeam,saves:num(s.saves),seconds:rawSeconds(s.raw),minutes:Math.round(num(s.minutes_played)*10)/10,ga:num(s.goals_against),sourcePlayerId:s.player_id,otherActive:other.map((o:any)=>(playerMap.get(o.player_id) as any)?.name||o.player_id)};if(!reasons.length)candidateGames.push({stat:s,...info});else if(opp===0||num(s.goals_against)===0)rejectedGames.push({...info,reasons})}
const uniqueCandidates=[...new Map(candidateGames.map((x:any)=>[x.gameId,x])).values()],uniqueRejected=[...new Map(rejectedGames.map((x:any)=>[`${x.gameId}|${x.reasons.join("|")}`,x])).values()];
// Ny, read-only diagnose: start i LAGETS faktiske nullkamper, ikke keeperens eksisterende stat-rader.
const groupTeamKeys=new Set(group.map((x:any)=>teamKey(x.team)).filter(Boolean));for(const s of ps)groupTeamKeys.add(teamKey(s.team_snapshot||(playerMap.get(s.player_id) as any)?.team));const teamZeroGames=(games||[]).filter((g:any)=>{const hk=teamKey(g.home_team),ak=teamKey(g.away_team);return(groupTeamKeys.has(hk)&&num(g.away_score,-1)===0)||(groupTeamKeys.has(ak)&&num(g.home_score,-1)===0)}).map((g:any)=>{const hk=teamKey(g.home_team),teamIsHome=groupTeamKeys.has(hk),pk=teamIsHome?hk:teamKey(g.away_team),all=(byGame.get(g.id)||[]).filter((x:any)=>teamKey(x.team_snapshot||(playerMap.get(x.player_id) as any)?.team)===pk),mine=all.filter((x:any)=>ids.has(x.player_id)),active=all.filter((x:any)=>num(x.saves)>0||num(x.goals_against)>0||rawSeconds(x.raw)>0||num(x.minutes_played)>0);return{gameId:g.id,date:g.starts_at??null,homeTeam:g.home_team,awayTeam:g.away_team,score:`${g.home_score??"–"}–${g.away_score??"–"}`,side:teamIsHome?"H":"B",keeperRows:mine.map((x:any)=>({name:(playerMap.get(x.player_id) as any)?.name||p.name,saves:num(x.saves),ga:num(x.goals_against),minutes:num(x.minutes_played),seconds:rawSeconds(x.raw),shutout:!!x.shutout})),activeGoalies:active.map((x:any)=>({name:(playerMap.get(x.player_id) as any)?.name||x.player_id,saves:num(x.saves),ga:num(x.goals_against),minutes:num(x.minutes_played),seconds:rawSeconds(x.raw)})),diagnosis:mine.length===0?"MANGLER_KEEPERRAD":active.some((x:any)=>ids.has(x.player_id))?"KEEPER_AKTIV":"KEEPERRAD_UTEN_AKTIVITET"}});
const secondsUpdates=ps.filter((s:any)=>rawSeconds(s.raw)>0).map((s:any)=>({id:s.id,minutes:rawSeconds(s.raw)/60}));for(const u of secondsUpdates){const{error}=await db.from("fantasy_player_game_stats").update({minutes_played:u.minutes}).eq("id",u.id);if(error)throw error}let applied=false;if(uniqueCandidates.length===target){const statIds=ps.map((s:any)=>s.id);if(statIds.length){const{error}=await db.from("fantasy_player_game_stats").update({shutout:false}).in("id",statIds);if(error)throw error}const cids=uniqueCandidates.map((x:any)=>x.stat.id);if(cids.length){const{error}=await db.from("fantasy_player_game_stats").update({shutout:true}).in("id",cids);if(error)throw error}applied=true}results.push({name:p.name,team:p.team,targetSO:target,candidates:uniqueCandidates.length,applied,secondsFixed:secondsUpdates.length,duplicateProfiles:group.length,candidateGames:uniqueCandidates.map(({stat,...x}:any)=>x),rejectedGames:uniqueRejected,teamZeroGames,teamZeroCount:teamZeroGames.length,teamZeroMissingKeeperRows:teamZeroGames.filter((x:any)=>x.diagnosis==="MANGLER_KEEPERRAD").length})}
return NextResponse.json({ok:true,season,tournamentId,results});}catch(error:any){return NextResponse.json({ok:false,error:error?.message||"Keeperavstemming feilet"},{status:500})}}
