import { NextRequest, NextResponse } from "next/server";
import { createClient } from "@supabase/supabase-js";
export const runtime="nodejs";export const dynamic="force-dynamic";
async function requireAdmin(request:NextRequest){const url=process.env.NEXT_PUBLIC_SUPABASE_URL,key=process.env.NEXT_PUBLIC_SUPABASE_PUBLISHABLE_KEY;if(!url||!key)return{ok:false as const,response:NextResponse.json({ok:false,error:"Supabase public-konfigurasjon mangler."},{status:503})};const header=request.headers.get("authorization"),token=header?.startsWith("Bearer ")?header.slice(7):null;if(!token)return{ok:false as const,response:NextResponse.json({ok:false,error:"Mangler innlogging."},{status:401})};const auth=createClient(url,key,{auth:{persistSession:false,autoRefreshToken:false},global:{headers:{Authorization:`Bearer ${token}`}}});const{data:userData,error:userError}=await auth.auth.getUser(token);if(userError||!userData.user)return{ok:false as const,response:NextResponse.json({ok:false,error:"Ugyldig innlogging."},{status:401})};const{data:player}=await auth.from("players").select("admin").eq("id",userData.user.id).maybeSingle();if(!player?.admin)return{ok:false as const,response:NextResponse.json({ok:false,error:"Kun admin."},{status:403})};return{ok:true as const}}
function server(){const u=process.env.NEXT_PUBLIC_SUPABASE_URL,k=process.env.SUPABASE_SECRET_KEY;if(!u||!k)throw new Error("Supabase server-variabler mangler");return createClient(u,k,{auth:{persistSession:false,autoRefreshToken:false}})}
function n(v:any){const x=Number(v);return Number.isFinite(x)?x:0}
function rawVal(raw:any,...keys:string[]){for(const k of keys)if(raw?.[k]!==undefined&&raw?.[k]!==null&&raw?.[k]!=="")return raw[k];return null}
function mins(row:any){const raw=row.raw||{};const sec=rawVal(raw,"secondsPlayed","SecondsPlayed","playerTimeSeconds","PlayerTimeSeconds");if(sec!=null)return Math.round((n(sec)/60)*10)/10;return Math.round(n(row.minutes_played)*10)/10}
export async function GET(request:NextRequest){const admin=await requireAdmin(request);if(!admin.ok)return admin.response;const ids=(new URL(request.url).searchParams.get("ids")||"").split(",").map(x=>x.replace(/\D/g,"")).filter(Boolean);if(!ids.length)return NextResponse.json({ok:true,matches:{}});const s=server();try{const candidates=ids.flatMap(id=>[`hockeylive:${id}`,id,`nif:${id}`]);const{data:games,error:ge}=await s.from("fantasy_games").select("id,external_id,starts_at,home_team,away_team,home_score,away_score").in("external_id",candidates);if(ge)throw ge;const out:Record<string,any>={};for(const g of games||[]){const{data:stats,error:se}=await s.from("fantasy_player_game_stats").select("player_id,team_snapshot,saves,goals_against,minutes_played,win,shutout,position_snapshot,raw").eq("game_id",g.id).eq("position_snapshot","G");if(se)throw se;const pids=(stats||[]).map((x:any)=>x.player_id);const{data:players,error:pe}=pids.length?await s.from("fantasy_players").select("id,name,team").in("id",pids):{data:[],error:null};if(pe)throw pe;const pm=new Map((players||[]).map((p:any)=>[p.id,p]));const rows=(stats||[]).map((r:any)=>{const p:any=pm.get(r.player_id)||{};const raw=r.raw||{};return{name:p.name||"?",team:r.team_snapshot||p.team||"",minutes:mins(r),saves:n(r.saves),ga:n(r.goals_against),storedWin:Boolean(r.win),storedSO:Boolean(r.shutout),rawWins:rawVal(raw,"wins","Wins","win","Win"),rawLosses:rawVal(raw,"losses","Losses","loss","Loss"),rawSO:rawVal(raw,"shutouts","Shutouts","shutout","Shutout","so","SO"),rawMinutes:rawVal(raw,"minutesPlayed","MinutesPlayed","secondsPlayed","SecondsPlayed","playerTimeSeconds","PlayerTimeSeconds")}});const id=String(g.external_id||"").replace(/\D/g,"");out[id]={game:{date:g.starts_at,home:g.home_team,away:g.away_team,score:`${g.home_score}–${g.away_score}`},goalies:rows}}
return NextResponse.json({ok:true,matches:out})}catch(e:any){return NextResponse.json({ok:false,error:e.message||"Feil"},{status:500})}}
