"use client";
import {useState} from "react";
import {HISTORICAL_PRICES_2025} from "../../../../lib/fantasy/historical-prices-2025";
import "../../fantasy.css";

const norm=(v:any)=>String(v??"").toLocaleLowerCase("nb-NO").normalize("NFD").replace(/[\u0300-\u036f]/g,"").replace(/ø/g,"o").replace(/æ/g,"ae").replace(/[^a-z0-9]+/g," ").trim();
const natural=(s:string)=>{const[last,...r]=s.split(",");return r.length?`${r.join(",").trim()} ${last.trim()}`:s};
function canonTeam(v:string){const s=norm(v);if(s.includes("storhamar"))return"Storhamar";if(s.includes("stavanger")||s.includes("oilers"))return"Stavanger";if(s.includes("valerenga"))return"Vålerenga";if(s.includes("frisk"))return"Frisk Asker";if(s.includes("sparta"))return"Sparta";if(s.includes("narvik"))return"Narvik";if(s.includes("stjernen"))return"Stjernen";if(s.includes("lillehammer"))return"Lillehammer";if(s.includes("lorenskog"))return"Lørenskog";if(s.includes("nidaros"))return"Nidaros";return v}

export default function Page(){
 const[busy,setBusy]=useState(false),[msg,setMsg]=useState("Klar"),[rows,setRows]=useState<any[]>([]),[stats,setStats]=useState<any>(null);
 async function run(){setBusy(true);try{const r=await fetch('/api/fantasy-roster-2026',{cache:'no-store'}),j=await r.json();if(!r.ok||!j.ok)throw new Error(j.error||'Import feilet');const prev=new Map<string,any>();for(const x of HISTORICAL_PRICES_2025)prev.set(norm(natural(x[0])),x);const out=j.rows.map((x:any)=>{const p=prev.get(norm(x.name));const oldTeam=p?canonTeam(String(p[1])):null,newTeam=canonTeam(String(x.team));return{...x,team:newTeam,oldTeam,oldPrice:p?Number(p[2])/1e6:null,status:!p?'Ny spiller':oldTeam!==newTeam?'Klubbskifte':'Samme klubb'}}).sort((a:any,b:any)=>a.team.localeCompare(b.team,'nb')||a.name.localeCompare(b.name,'nb'));const counts=out.reduce((m:any,x:any)=>(m[x.status]=(m[x.status]||0)+1,m),{});setRows(out);setStats({n:out.length,teams:new Set(out.map((x:any)=>x.team)).size,...counts});setMsg(`Ferdig · ${out.length} spillere hentet fra HockeyLive`)}catch(e:any){setMsg(e.message||'Feil')}finally{setBusy(false)}}
 return <main className="fantasy-shell"><section className="fantasy-hero"><div><p className="fantasy-kicker">STANG INN · 2026/27 ROSTER</p><h1>HockeyLive spillerimport</h1><p className="fantasy-lead">Henter faktisk 2026/27-spillerpool og sammenligner mot 2025/26-prislisten for å finne klubbskifter og nye spillere.</p></div><a className="pill" href="/fantasy">← Fantasy-sentralen</a></section><section className="fantasy-card"><button disabled={busy} onClick={run}>{busy?'Henter …':'Importer 2026/27-spillere'}</button> <span>{msg}</span>{stats&&<><div style={{display:'grid',gridTemplateColumns:'repeat(auto-fit,minmax(170px,1fr))',gap:10,margin:'18px 0'}}>{[["Spillere",stats.n],["Lag",stats.teams],["Samme klubb",stats['Samme klubb']||0],["Klubbskifte",stats['Klubbskifte']||0],["Nye spillere",stats['Ny spiller']||0]].map(([a,b]:any)=><div key={a} style={{padding:14,borderRadius:12,background:'#f5f7fa'}}><b>{a}</b><div style={{fontSize:26,fontWeight:900}}>{b}</div></div>)}</div><div style={{overflowX:'auto'}}><table style={{width:'100%',minWidth:900,borderCollapse:'collapse',fontSize:12}}><thead><tr>{['Spiller','Pos','26/27 lag','25/26 lag','25/26 pris','Status'].map(h=><th key={h} style={{padding:8,textAlign:'left',background:'#eef3f8'}}>{h}</th>)}</tr></thead><tbody>{rows.map((x:any,i:number)=><tr key={`${x.personId||x.name}-${i}`}><td style={{padding:8,fontWeight:700}}>{x.name}</td><td>{x.position||'—'}</td><td>{x.team}</td><td>{x.oldTeam||'—'}</td><td>{x.oldPrice!=null?`${x.oldPrice.toFixed(1)}m`:'—'}</td><td style={{fontWeight:800}}>{x.status}</td></tr>)}</tbody></table></div></>}</section></main>}
