export type EliteProspectsRosterRole = "G" | "D" | "F";
export type EliteProspectsRosterPlayer = {name:string;team:string;role:EliteProspectsRosterRole};

// Versioned preseason source-of-truth snapshot verified against current EliteProspects 2026/27 team rosters.
// HockeyLive/NIF remains valuable for person IDs and game data, but its preseason TeamMembers fallback is not authoritative for membership.
export const ELITEPROSPECTS_ROSTER_2026_VERIFIED_AT="2026-08-16";
export const ELITEPROSPECTS_ROSTER_2026:EliteProspectsRosterPlayer[]=[
// Frisk Asker · 23
{name:"Aron Breivold",team:"Frisk Asker",role:"G"},{name:"Mitch Gillam",team:"Frisk Asker",role:"G"},
{name:"Alexander Anderberg",team:"Frisk Asker",role:"D"},{name:"Nicolay Andresen",team:"Frisk Asker",role:"D"},{name:"Anton Björkman",team:"Frisk Asker",role:"D"},{name:"Charlie Callaghan",team:"Frisk Asker",role:"D"},{name:"Christian Kåsastul",team:"Frisk Asker",role:"D"},{name:"Nils Sunde",team:"Frisk Asker",role:"D"},{name:"Patrick Ulriksen",team:"Frisk Asker",role:"D"},
{name:"Fredrik Bjørndal",team:"Frisk Asker",role:"F"},{name:"Christian Vethe Bye",team:"Frisk Asker",role:"F"},{name:"Sebastian Dyk",team:"Frisk Asker",role:"F"},{name:"Marcus Valkvæ Erevik",team:"Frisk Asker",role:"F"},{name:"Tobias Fladeby",team:"Frisk Asker",role:"F"},{name:"Magnus Geheb",team:"Frisk Asker",role:"F"},{name:"Felix Granath",team:"Frisk Asker",role:"F"},{name:"Viktor Granholm",team:"Frisk Asker",role:"F"},{name:"Hampus Gustafsson",team:"Frisk Asker",role:"F"},{name:"Michael Haga",team:"Frisk Asker",role:"F"},{name:"Thomas Valkvæ Olsen",team:"Frisk Asker",role:"F"},{name:"Tobias Skuterud",team:"Frisk Asker",role:"F"},{name:"Eskil Wold",team:"Frisk Asker",role:"F"},{name:"Sander Wold",team:"Frisk Asker",role:"F"},
// Lillehammer · 22
{name:"Niilo Halonen",team:"Lillehammer",role:"G"},{name:"Albin Mörck",team:"Lillehammer",role:"G"},
{name:"Filip Bratt",team:"Lillehammer",role:"D"},{name:"Viljami Juusola",team:"Lillehammer",role:"D"},{name:"Mathias Despotovic Kristiansen",team:"Lillehammer",role:"D"},{name:"David Nilsson",team:"Lillehammer",role:"D"},{name:"Lucas Øvrebø Ondrcka",team:"Lillehammer",role:"D"},{name:"Emils Skeltins",team:"Lillehammer",role:"D"},{name:"Erlend Sletmoe-Kjærnet",team:"Lillehammer",role:"D"},
{name:"Joakim Eidsa Arnestad",team:"Lillehammer",role:"F"},{name:"Adam Bäckstrand",team:"Lillehammer",role:"F"},{name:"Adrian Ellingsen",team:"Lillehammer",role:"F"},{name:"Martin Ellingsen",team:"Lillehammer",role:"F"},{name:"Nicolai Evjen",team:"Lillehammer",role:"F"},{name:"Vegard Kjellevold Fredriksen",team:"Lillehammer",role:"F"},{name:"Santeri Hartikainen",team:"Lillehammer",role:"F"},{name:"Oliver Tufte Langland",team:"Lillehammer",role:"F"},{name:"Jakop Leibnitz",team:"Lillehammer",role:"F"},{name:"Emil Nyhus",team:"Lillehammer",role:"F"},{name:"Mathias Storlien Olsen",team:"Lillehammer",role:"F"},{name:"Vetle Østrem Salsten",team:"Lillehammer",role:"F"},{name:"Peder Skarpjordet",team:"Lillehammer",role:"F"},
// Narvik · 24
{name:"Anton Hjalmarsson",team:"Narvik",role:"G"},{name:"Joona Partanen",team:"Narvik",role:"G"},
{name:"Noah Jacobsen",team:"Narvik",role:"D"},{name:"Oskar Matushkin",team:"Narvik",role:"D"},{name:"Jeppe Meyer",team:"Narvik",role:"D"},{name:"Matteo Mitrovic",team:"Narvik",role:"D"},{name:"Isak Pantzare",team:"Narvik",role:"D"},{name:"Johan Tørres Selnes",team:"Narvik",role:"D"},{name:"Kyrre Haarberg Svarstad",team:"Narvik",role:"D"},{name:"Sondre Bolling Vaaler",team:"Narvik",role:"D"},
{name:"Noah Andersson",team:"Narvik",role:"F"},{name:"Benjamin Byrkjeland",team:"Narvik",role:"F"},{name:"Douglas Byrkjeland",team:"Narvik",role:"F"},{name:"Johan Ceder",team:"Narvik",role:"F"},{name:"Mathias Dehli",team:"Narvik",role:"F"},{name:"Albin Eriksson",team:"Narvik",role:"F"},{name:"Philip Hägerström",team:"Narvik",role:"F"},{name:"Jesper Kokkonen",team:"Narvik",role:"F"},{name:"Rasmus Koskinen",team:"Narvik",role:"F"},{name:"William Magnusson",team:"Narvik",role:"F"},{name:"Kristian Røykås Marthinsen",team:"Narvik",role:"F"},{name:"Tobias Tveter",team:"Narvik",role:"F"},{name:"Esbjørn Fogstad Vold",team:"Narvik",role:"F"},{name:"Tobias Åhström",team:"Narvik",role:"F"},
// Nidaros · 23
{name:"Oscar Darnell",team:"Nidaros",role:"G"},{name:"Daniel Lebedeff",team:"Nidaros",role:"G"},
{name:"Adam Bäckehag",team:"Nidaros",role:"D"},{name:"Noah Sandø Gagnås",team:"Nidaros",role:"D"},{name:"Wilhelm Gullhav",team:"Nidaros",role:"D"},{name:"Anders Jonassen",team:"Nidaros",role:"D"},{name:"Bård Valstad Solheim",team:"Nidaros",role:"D"},{name:"Sander Vedul-Kjelsås",team:"Nidaros",role:"D"},{name:"Jack York",team:"Nidaros",role:"D"},{name:"Anton Öhman",team:"Nidaros",role:"D"},
{name:"Max Henrik Hagesveen Andresen",team:"Nidaros",role:"F"},{name:"Alieu Moldal Bah",team:"Nidaros",role:"F"},{name:"Joachim Johannesen Barmoen",team:"Nidaros",role:"F"},{name:"Alexander Bjurström",team:"Nidaros",role:"F"},{name:"Fredrik Vethe Bye",team:"Nidaros",role:"F"},{name:"Lukas Fransson",team:"Nidaros",role:"F"},{name:"Edvard Dehli Gjøs",team:"Nidaros",role:"F"},{name:"Simen Solbakken Haugen",team:"Nidaros",role:"F"},{name:"Ole Indergaard",team:"Nidaros",role:"F"},{name:"Leonards Rimjans",team:"Nidaros",role:"F"},{name:"Teemu Siironen",team:"Nidaros",role:"F"},{name:"Håkon Imset Stormli",team:"Nidaros",role:"F"},{name:"Ludwig Wistén",team:"Nidaros",role:"F"},
// Ringerike · 24
{name:"Trym Gran",team:"Ringerike",role:"G"},{name:"Jørgen Rønning",team:"Ringerike",role:"G"},
{name:"Robin Bjørnstad",team:"Ringerike",role:"D"},{name:"Johan Dehli Gjøs",team:"Ringerike",role:"D"},{name:"Lars Erik Francke-Enersen",team:"Ringerike",role:"D"},{name:"Ludvig Hedström",team:"Ringerike",role:"D"},{name:"Thomas Lyngås Higson",team:"Ringerike",role:"D"},{name:"Jens Jøsok Holstad",team:"Ringerike",role:"D"},{name:"Albert Lyckåsen",team:"Ringerike",role:"D"},{name:"Magnus Grønvold Menkerud",team:"Ringerike",role:"D"},
{name:"Isac Andersson",team:"Ringerike",role:"F"},{name:"Ludvik Kind Bakkevig",team:"Ringerike",role:"F"},{name:"John Beaton",team:"Ringerike",role:"F"},{name:"Christian Blomqvist",team:"Ringerike",role:"F"},{name:"Thomas Bækken",team:"Ringerike",role:"F"},{name:"Oliver Calik",team:"Ringerike",role:"F"},{name:"Tobias Skogstad Falkeid",team:"Ringerike",role:"F"},{name:"Max Freyschuss Nordin",team:"Ringerike",role:"F"},{name:"Iver Wick Karlsen",team:"Ringerike",role:"F"},{name:"Natanael Lindholm",team:"Ringerike",role:"F"},{name:"Jakob Aasen Rian",team:"Ringerike",role:"F"},{name:"Alex Sjøthun",team:"Ringerike",role:"F"},{name:"Herman Teslo Skjefstad",team:"Ringerike",role:"F"},{name:"Mateusz Szurowski",team:"Ringerike",role:"F"},
// Sparta · 25
{name:"Blake Pietila",team:"Sparta",role:"G"},{name:"Marcus Walberg",team:"Sparta",role:"G"},
{name:"Felix Haugen Amundsen",team:"Sparta",role:"D"},{name:"Marcus Fagerudd",team:"Sparta",role:"D"},{name:"Niks Fenenko",team:"Sparta",role:"D"},{name:"Daniel Gloppen",team:"Sparta",role:"D"},{name:"Tine Klofutar",team:"Sparta",role:"D"},{name:"Daniil Kovalenko",team:"Sparta",role:"D"},{name:"Jonas Meisingset",team:"Sparta",role:"D"},{name:"Maksims Ponomarenko",team:"Sparta",role:"D"},
{name:"Simen Ahlsen",team:"Sparta",role:"F"},{name:"Rasmus Olsen Brekke",team:"Sparta",role:"F"},{name:"Magnus Eisenmenger",team:"Sparta",role:"F"},{name:"Tinius Schiager Ekhaugen",team:"Sparta",role:"F"},{name:"Nicolai Eliesen",team:"Sparta",role:"F"},{name:"Anton Gradin",team:"Sparta",role:"F"},{name:"Martin Grönberg",team:"Sparta",role:"F"},{name:"Jonathan Hermansson",team:"Sparta",role:"F"},{name:"Sebastian Johansen",team:"Sparta",role:"F"},{name:"Henrik Knold",team:"Sparta",role:"F"},{name:"Filip Lalande",team:"Sparta",role:"F"},{name:"Erlend Løkkeberg",team:"Sparta",role:"F"},{name:"Jørgen Nyhus Myhre",team:"Sparta",role:"F"},{name:"Sander Thoresen",team:"Sparta",role:"F"},{name:"Victor Öhman",team:"Sparta",role:"F"},
// Stavanger · 25
{name:"Zachary Émond",team:"Stavanger",role:"G"},{name:"Jens Auke Hoekstra",team:"Stavanger",role:"G"},{name:"Henrik Holm",team:"Stavanger",role:"G"},
{name:"Isak Hansen",team:"Stavanger",role:"D"},{name:"Andreas Klavestad",team:"Stavanger",role:"D"},{name:"Fredrik Tunge Lunde",team:"Stavanger",role:"D"},{name:"Case McCarthy",team:"Stavanger",role:"D"},{name:"Mattias Nørstebø",team:"Stavanger",role:"D"},{name:"Jonas Eide Pettersen",team:"Stavanger",role:"D"},{name:"Cliff Watson",team:"Stavanger",role:"D"},{name:"Kristian Sjødahl Østby",team:"Stavanger",role:"D"},
{name:"Ludwig Blomstrand",team:"Stavanger",role:"F"},{name:"Niclas Kylevik Ekeland",team:"Stavanger",role:"F"},{name:"Vegard Faret",team:"Stavanger",role:"F"},{name:"Martin Gran",team:"Stavanger",role:"F"},{name:"Anders Tangen Henriksen",team:"Stavanger",role:"F"},{name:"Ludvig Hoff",team:"Stavanger",role:"F"},{name:"Christoffer Karlsen",team:"Stavanger",role:"F"},{name:"Johannes Løkkeberg",team:"Stavanger",role:"F"},{name:"Linus Pettersson",team:"Stavanger",role:"F"},{name:"Ludvig Rensfeldt",team:"Stavanger",role:"F"},{name:"Lars Christian Rødne",team:"Stavanger",role:"F"},{name:"André Bjelland Strandborg",team:"Stavanger",role:"F"},{name:"Mathias Trettenes",team:"Stavanger",role:"F"},{name:"Elias Straume Vatne",team:"Stavanger",role:"F"},
// Stjernen · 25
{name:"Laban Byrkjeland",team:"Stjernen",role:"G"},{name:"Faustas Nauseda",team:"Stjernen",role:"G"},
{name:"Emil Buskoven",team:"Stjernen",role:"D"},{name:"Niclas Jessesen",team:"Stjernen",role:"D"},{name:"Mattias Alexandersen Juntti",team:"Stjernen",role:"D"},{name:"Theo Nordlund",team:"Stjernen",role:"D"},{name:"Håkon Løken Pedersen",team:"Stjernen",role:"D"},{name:"Lukas Rhodin",team:"Stjernen",role:"D"},{name:"Linus Rosdahl",team:"Stjernen",role:"D"},{name:"Jarl Fredrik Tillman",team:"Stjernen",role:"D"},
{name:"Leo Brandbu Andersen",team:"Stjernen",role:"F"},{name:"Didrik Baanerud",team:"Stjernen",role:"F"},{name:"Matheo Werner Dubec",team:"Stjernen",role:"F"},{name:"Stian Nybraaten Hansen",team:"Stjernen",role:"F"},{name:"Linus Hedman",team:"Stjernen",role:"F"},{name:"Andreas Heier",team:"Stjernen",role:"F"},{name:"Kristian Jakobsson",team:"Stjernen",role:"F"},{name:"William Kuisma",team:"Stjernen",role:"F"},{name:"Casper Einvik Myklebust",team:"Stjernen",role:"F"},{name:"Mats Bakke Olsen",team:"Stjernen",role:"F"},{name:"Joakim Aarseth Opsahl",team:"Stjernen",role:"F"},{name:"Sole Marius Ryen",team:"Stjernen",role:"F"},{name:"Theodor Steen",team:"Stjernen",role:"F"},{name:"Didrik Utter",team:"Stjernen",role:"F"},{name:"Oscar Öhman",team:"Stjernen",role:"F"},
// Storhamar · 25
{name:"Tyler Parks",team:"Storhamar",role:"G"},{name:"Theo Rooseboom de Vries",team:"Storhamar",role:"G"},
{name:"Sondre Berg",team:"Storhamar",role:"D"},{name:"Christian Bull",team:"Storhamar",role:"D"},{name:"Joe Gatenby",team:"Storhamar",role:"D"},{name:"Andreas Hjelm",team:"Storhamar",role:"D"},{name:"Sander Dilling Hurrød",team:"Storhamar",role:"D"},{name:"Amil Krupic",team:"Storhamar",role:"D"},{name:"Jesper Martinsen Lilleberg",team:"Storhamar",role:"D"},{name:"Mathias Papuga",team:"Storhamar",role:"D"},{name:"Sverre Rønningen",team:"Storhamar",role:"D"},
{name:"David Aas-Larsen",team:"Storhamar",role:"F"},{name:"Jacob Berglund",team:"Storhamar",role:"F"},{name:"Austin Cangelosi",team:"Storhamar",role:"F"},{name:"Kenneth Pappalardo Gulbrandsen",team:"Storhamar",role:"F"},{name:"Simon Hjalmarsson",team:"Storhamar",role:"F"},{name:"Andreas Martinsen",team:"Storhamar",role:"F"},{name:"Linus Paulsen Morken",team:"Storhamar",role:"F"},{name:"Oliver Kaatorp Nilsgård",team:"Storhamar",role:"F"},{name:"Stian Kaltrud Nystuen",team:"Storhamar",role:"F"},{name:"Martin Rønnild",team:"Storhamar",role:"F"},{name:"Eirik Salsten",team:"Storhamar",role:"F"},{name:"Axel Sandnes",team:"Storhamar",role:"F"},{name:"Isac Skedung",team:"Storhamar",role:"F"},{name:"Liam Sætre",team:"Storhamar",role:"F"},
// Vålerenga · 23
{name:"Mathias Schjerpen Arnkværn",team:"Vålerenga",role:"G"},{name:"Lars Volden",team:"Vålerenga",role:"G"},
{name:"Kristoffer Gunnarsson",team:"Vålerenga",role:"D"},{name:"Gabriel Koch",team:"Vålerenga",role:"D"},{name:"Henrik Larsson",team:"Vålerenga",role:"D"},{name:"Marius Kristian Määttänen",team:"Vålerenga",role:"D"},{name:"Hakon Nilsen",team:"Vålerenga",role:"D"},{name:"Daniel Bøen Rokseth",team:"Vålerenga",role:"D"},{name:"Juuso Vainio",team:"Vålerenga",role:"D"},
{name:"Mikkel Christiansen",team:"Vålerenga",role:"F"},{name:"Patrik Dalen",team:"Vålerenga",role:"F"},{name:"Pontus Finstad",team:"Vålerenga",role:"F"},{name:"Leo Johansen Halmrast",team:"Vålerenga",role:"F"},{name:"Aron Jessli",team:"Vålerenga",role:"F"},{name:"Jørgen Karterud",team:"Vålerenga",role:"F"},{name:"Markus Modigs",team:"Vålerenga",role:"F"},{name:"Sondre Olden",team:"Vålerenga",role:"F"},{name:"Ken Andre Olimb",team:"Vålerenga",role:"F"},{name:"Mathis Olimb",team:"Vålerenga",role:"F"},{name:"Martin Røymark",team:"Vålerenga",role:"F"},{name:"Christian Lillestøl Torrissen",team:"Vålerenga",role:"F"},{name:"Pathrik Westerholm",team:"Vålerenga",role:"F"},{name:"Ponthus Westerholm",team:"Vålerenga",role:"F"}
];

export const ELITEPROSPECTS_ROSTER_COUNTS_2026=Object.freeze(ELITEPROSPECTS_ROSTER_2026.reduce<Record<string,number>>((acc,row)=>{acc[row.team]=(acc[row.team]||0)+1;return acc;},{}));
