"use client";

import {useEffect,useMemo,useState} from "react";
import {getSupabaseBrowserClient} from "../../../../lib/supabase";
import "../../fantasy.css";
import "../xfp-admin.css";
import "./preseason.css";

type Game={id:number;game_date:string;starts_at:string|null;home_team:string;away_team:string;home_score:number|null;away_score:number|null;status:string;hockeylive_match_id:number|null;source_type:string;source_quality:number;source_url:string|null;notes:string|null};
type Stat={preseason_game_id:number;player_id:string|null};
type DiagnoseRow={game:string;rawPlayerName:string;rawTeam:string;matched:boolean;confidence:string;reason:string;matchedPlayer:{name:string;team:string;position:string|null}|null;candidates:{name:string;team:string;position:string|null}[]};
type HockeyDiagRow={game:string;gameDate:string|null;rawPlayerName:string;rawTeam:string;ehlSide:boolean;reason:string};
type AuditRow={category:string;xfpEligible:boolean;gameDate:string|null;game:string|null;preseasonName:string;preseasonTeam:string;sourceType:string;playerId:string;fantasyName:string|null;fantasyTeam:string|null;fantasyPosition:string|null;onCurrentRoster:boolean|null;active:boolean|null;sideLeague:string|null};
type SignalRow={player_id:string;player_name:string;team:string;player_position:string|null;preseason_games:number;preseason_ppg:number;avg_opponent_factor:number;avg_data_weight:number;regular_games:number;preseason_weight:number;data_confidence:string};
type PreviewRow={player_id:string;player_name:string;team:string;player_position:string|null;baseline_xfp:number;preseason_ppg:number;preseason_games:number;preseason_weight:number;preseason_adjustment:number;preview_xfp:number;avg_opponent_factor:number;avg_data_weight:number;regular_games:number;data_confidence:string};

const dt=(g:Game)=>g.starts_at?new Date(g.starts_at).toLocaleString("nb-NO",{day:"2-digit",month:"2-digit",hour:"2-digit",minute:"2-digit"}):new Date(`${g.game_date}T12:00:00`).toLocaleDateString("nb-NO",{day:"2-digit",month:"2-digit"})+" · tid ukjent";
const num=(v:unknown)=>Number(v||0);

export default function PreseasonAdminPage(){
 const[token,setToken]=useState<string|null>(null),[games,setGames]=useState<Game[]>([]),[stats,setStats]=useState<Stat[]>([]),[busy,setBusy]=useState(false),[message,setMessage]=useState("Laster preseason-data …"),[diagnose,setDiagnose]=useState<DiagnoseRow[]>([]),[diagSummary,setDiagSummary]=useState<{total:number;matched:number;unmatched:number;strong:number}|null>(null),[hockeyDiag,setHockeyDiag]=useState<{totalUnmatched:number;ehlUnmatched:number;nonEhlUnmatched:number;rows:HockeyDiagRow[];ehlRows:HockeyDiagRow[]}|null>(null),[audit,setAudit]=useState<{total:number;xfpEligible:number;crossTeam:number;sameTeamNonEhl:number;rows:AuditRow[]}|null>(null),[signal,setSignal]=useState<SignalRow[]>([]),[preview,setPreview]=useState<PreviewRow[]>([]),[previewError,setPreviewError]=useState("");

 useEffect(()=>{(async()=>{try{const sb=getSupabaseBrowserClient();if(!sb)throw new Error("Supabase er ikke tilgjengelig");const{data}=await sb.auth.getSession();const access=data.session?.access_token;if(!access)throw new Error("Du må være logget inn");setToken(access);await load(access)}catch(e:any){setMessage(e?.message||"Kunne ikke laste preseason")}})()},[]);

 async function load(access=token){const sb=getSupabaseBrowserClient();if(!sb)return;const previewPromise=access?fetch("/api/admin/fantasy/preseason-preview",{headers:{Authorization:`Bearer ${access}`},cache:"no-store"}):Promise.resolve(null);const[gRes,sRes,sgRes,pvHttp]=await Promise.all([sb.from("fantasy_preseason_games").select("id,game_date,starts_at,home_team,away_team,home_score,away_score,status,hockeylive_match_id,source_type,source_quality,source_url,notes").eq("season","2026/27").order("game_date").order("starts_at"),sb.from("fantasy_preseason_player_stats").select("preseason_game_id,player_id"),(sb as any).rpc("get_fantasy_preseason_signal_admin_v1",{p_season:"2026/27"}),previewPromise]);if(gRes.error)throw gRes.error;if(sRes.error)throw sRes.error;if(sgRes.error)throw sgRes.error;setGames((gRes.data||[]) as Game[]);setStats((sRes.data||[]) as Stat[]);setSignal((sgRes.data||[]) as SignalRow[]);if(pvHttp){const pvBody=await pvHttp.json();if(!pvHttp.ok||!pvBody.ok){setPreview([]);setPreviewError(pvBody.error||"Kunne ikke beregne preview")}else{setPreview((pvBody.rows||[]) as PreviewRow[]);setPreviewError("")}}setMessage(`${(gRes.data||[]).length} treningskamper · ${(sRes.data||[]).length} spillerlinjer · ${(sgRes.data||[]).length} xFP-signaler`) }

 async function run(path:string,label:string){if(!token)return;setBusy(true);setMessage(`${label} …`);try{const res=await fetch(path,{method:"POST",headers:{Authorization:`Bearer ${token}`,"Content-Type":"application/json"},body:path.includes("preseason-import")?JSON.stringify({all:true}):JSON.stringify({}),cache:"no-store"});const body=await res.json();if(!res.ok||!body.ok)throw new Error(body.error||`${label} feilet`);await load(token);const failed=Number(body.failed||0);setMessage(`${label} fullført ✓${failed?` · ${failed} feilet`:""}`)}catch(e:any){setMessage(e?.message||`${label} feilet`)}finally{setBusy(false)}}

 async function runDiagnose(){if(!token)return;setBusy(true);setMessage("Diagnostiserer preseason-matching …");try{const res=await fetch("/api/admin/fantasy/preseason-match-diagnose",{headers:{Authorization:`Bearer ${token}`},cache:"no-store"});const body=await res.json();if(!res.ok||!body.ok)throw new Error(body.error||"Diagnose feilet");setDiagnose(body.rows||[]);setDiagSummary({total:Number(body.total||0),matched:Number(body.matched||0),unmatched:Number(body.unmatched||0),strong:Number(body.strong||0)});setHockeyDiag(body.hockeylive||null);setMessage(`Ekstern: ${body.matched}/${body.total} sikre treff · HockeyLive EHL-unmatched: ${body.hockeylive?.ehlUnmatched||0}`)}catch(e:any){setMessage(e?.message||"Diagnose feilet")}finally{setBusy(false)}}

 async function runRosterAudit(){if(!token)return;setBusy(true);setMessage("Kontrollerer roster/lagtilhørighet …");try{const res=await fetch("/api/admin/fantasy/preseason-roster-audit",{headers:{Authorization:`Bearer ${token}`},cache:"no-store"});const body=await res.json();if(!res.ok||!body.ok)throw new Error(body.error||"Roster-audit feilet");setAudit(body);setMessage(`Roster-audit: ${body.xfpEligible} xFP-berettiget · ${body.crossTeam} cross-team · ${body.sameTeamNonEhl} same-team utenfor EHL`)}catch(e:any){setMessage(e?.message||"Roster-audit feilet")}finally{setBusy(false)}}

 const counts=useMemo(()=>{const m=new Map<number,{rows:number,matched:number}>();for(const s of stats){const x=m.get(s.preseason_game_id)||{rows:0,matched:0};x.rows++;if(s.player_id)x.matched++;m.set(s.preseason_game_id,x)}return m},[stats]);
 const hockeylive=games.filter(g=>g.hockeylive_match_id).length,finished=games.filter(g=>g.status==="finished").length,external=games.filter(g=>g.source_type==="web"||g.source_type==="official").length;
 const unmatched=diagnose.filter(r=>!r.matched);
 const auditRows=audit?.rows.filter(r=>r.category!=="XFP_ELIGIBLE")||[];
 const sortedSignal=useMemo(()=>[...signal].sort((a,b)=>num(b.preseason_ppg)-num(a.preseason_ppg)||a.player_name.localeCompare(b.player_name,"nb")),[signal]);
 const sortedPreview=useMemo(()=>[...preview].sort((a,b)=>num(b.preview_xfp)-num(a.preview_xfp)||a.player_name.localeCompare(b.player_name,"nb")),[preview]);

 return <main className="fantasy-shell xfp-command-center preseason-admin">
  <section className="xfp-command-hero"><p className="fantasy-kicker">STANG INN · ADMIN ANALYSE</p><h1>Preseason-form</h1><p>Isolert treningskampdata for xFP. Ingenting her påvirker faktisk Fantasy-scoring.</p></section>

  <section className="xfp-panel">
   <div className="xfp-panel-head"><div><p className="eyebrow">PRESEASON 2026/27</p><h2>Datapipeline</h2><p>HockeyLive brukes når tilgjengelig. Utenlandske/andre kamper fylles fra dokumenterte eksterne kilder med egen datakvalitet.</p></div><a className="xfp-secondary" href="/fantasy/admin-analysis" style={{textDecoration:"none"}}>← Kommandosenter</a></div>
   <div className="preseason-actions"><button className="xfp-primary" disabled={busy} onClick={()=>run("/api/admin/fantasy/preseason-import","HockeyLive-import")}>🏒 Importer HockeyLive</button><button className="xfp-primary" disabled={busy} onClick={()=>run("/api/admin/fantasy/preseason-external","Ekstern import")}>🌍 Importer eksterne kilder</button><button className="xfp-secondary" disabled={busy} onClick={runDiagnose}>🔎 Diagnostiser matching</button><button className="xfp-secondary" disabled={busy} onClick={runRosterAudit}>🧭 Roster-audit</button><button className="xfp-secondary" disabled={busy} onClick={()=>load(token)}>↻ Oppdater</button></div>
   <p className="preseason-message">{message}</p>
   <div className="preseason-summary"><div><span>Kamper</span><strong>{games.length}</strong></div><div><span>Ferdige</span><strong>{finished}</strong></div><div><span>HockeyLive-ID</span><strong>{hockeylive}</strong></div><div><span>Ekstern kilde</span><strong>{external}</strong></div><div><span>Spillerlinjer</span><strong>{stats.length}</strong></div></div>
  </section>

  <section className="xfp-panel">
   <div className="xfp-panel-head"><div><p className="eyebrow">PRESEASON xFP v2 · PREVIEW</p><h2>Effekt på xFP</h2><p>Viser hva preseason-signalet ville gjort med dagens xFP. Baseline × (1 − vekt) + preseason PPG × vekt. Dette er kun simulering og endrer ikke hovedmodellen.</p></div></div>
   {previewError?<p className="preseason-message">Preview-feil: {previewError}</p>:sortedPreview.length===0?<p className="preseason-message">Ingen preview-rader ennå.</p>:<div className="preseason-table-wrap"><table className="preseason-table"><thead><tr><th>Spiller</th><th>Lag</th><th>Pos</th><th>Grunn-xFP</th><th>Preseason PPG</th><th>Kamper</th><th>Vekt</th><th>Justering</th><th>Preview xFP</th><th>Confidence</th></tr></thead><tbody>{sortedPreview.map(r=><tr key={r.player_id}><td><strong>{r.player_name}</strong></td><td>{r.team}</td><td>{r.player_position||"—"}</td><td>{num(r.baseline_xfp).toFixed(2)}</td><td>{num(r.preseason_ppg).toFixed(2)}</td><td>{r.preseason_games}</td><td>{Math.round(num(r.preseason_weight)*100)}%</td><td><strong>{num(r.preseason_adjustment)>=0?"+":""}{num(r.preseason_adjustment).toFixed(2)}</strong></td><td><strong>{num(r.preview_xfp).toFixed(2)}</strong></td><td>{r.data_confidence}</td></tr>)}</tbody></table></div>}
  </section>

  <section className="xfp-panel">
   <div className="xfp-panel-head"><div><p className="eyebrow">PRESEASON xFP v1</p><h2>Preseason-signal</h2><p>Kun xFP-berettigede EHL-spillere. Justert for motstandsnivå, datakvalitet og antall treningskamper. Dette er fortsatt analyse — ikke hoved-xFP.</p></div></div>
   {sortedSignal.length===0?<p className="preseason-message">Ingen xFP-berettigede preseason-signaler ennå.</p>:<div className="preseason-table-wrap"><table className="preseason-table"><thead><tr><th>Spiller</th><th>Lag</th><th>Pos</th><th>Kamper</th><th>Preseason PPG</th><th>Motstand</th><th>Datakvalitet</th><th>Vekt</th><th>Confidence</th></tr></thead><tbody>{sortedSignal.map(r=><tr key={r.player_id}><td><strong>{r.player_name}</strong></td><td>{r.team}</td><td>{r.player_position||"—"}</td><td>{r.preseason_games}</td><td><strong>{num(r.preseason_ppg).toFixed(2)}</strong></td><td>{num(r.avg_opponent_factor).toFixed(3)}</td><td>{Math.round(num(r.avg_data_weight)*100)}%</td><td>{Math.round(num(r.preseason_weight)*100)}%</td><td>{r.data_confidence}</td></tr>)}</tbody></table></div>}
  </section>

  {audit&&<section className="xfp-panel"><div className="xfp-panel-head"><div><p className="eyebrow">ROSTER-AUDIT</p><h2>{audit.xfpEligible} xFP-berettigede identiteter</h2><p>{audit.crossTeam} cross-team-identiteter er blokkert fra xFP. {audit.sameTeamNonEhl} spillere matcher Fantasy-laget sitt, men spiller for en ikke-EHL-side og er også blokkert.</p></div></div>{auditRows.length>0&&<div className="preseason-table-wrap"><table className="preseason-table"><thead><tr><th>Status</th><th>Preseason-spiller</th><th>Kamplag</th><th>Fantasy-spiller</th><th>Fantasy-lag</th><th>Side</th><th>Kamp</th></tr></thead><tbody>{auditRows.map((r,i)=><tr key={`${r.playerId}-${r.game}-${i}`}><td><strong>{r.category==="CROSS_TEAM_IDENTITY"?"Cross-team":r.category==="SAME_TEAM_NON_EHL"?"Same-team / ikke EHL":r.category}</strong></td><td>{r.preseasonName}</td><td>{r.preseasonTeam}</td><td>{r.fantasyName||"—"}</td><td>{r.fantasyTeam||"—"}</td><td>{r.sideLeague||"—"}</td><td>{r.game||"—"}</td></tr>)}</tbody></table></div>}</section>}

  {diagSummary&&<section className="xfp-panel"><div className="xfp-panel-head"><div><p className="eyebrow">MATCH-DIAGNOSE</p><h2>{diagSummary.matched}/{diagSummary.total} sikre eksterne treff</h2><p>{diagSummary.strong} treff bruker sikker mellomnavn-/navnetoken-match. {diagSummary.unmatched} må fortsatt vurderes.</p></div></div>{unmatched.length===0?<p className="preseason-message">Alle eksterne spillerlinjer er sikkert matchet.</p>:<div className="preseason-table-wrap"><table className="preseason-table diagnose-table"><thead><tr><th>Spiller</th><th>Lag</th><th>Kamp</th><th>Årsak</th><th>Kandidater</th></tr></thead><tbody>{unmatched.map((r,i)=><tr key={`${r.game}-${r.rawPlayerName}-${i}`}><td><strong>{r.rawPlayerName}</strong></td><td>{r.rawTeam}</td><td>{r.game}</td><td>{r.reason}</td><td>{r.candidates.length?r.candidates.map(c=>`${c.name} (${c.team})`).join(", "):"—"}</td></tr>)}</tbody></table></div>}
   {hockeyDiag&&<div style={{marginTop:18}}><p className="eyebrow">HOCKEYLIVE-SIKKERHET</p><h3 style={{margin:"4px 0 8px"}}>{hockeyDiag.ehlUnmatched===0?"✓ Ingen EHL-spillere falt ut":"⚠ EHL-spillere mangler match"}</h3><p className="preseason-message">{hockeyDiag.totalUnmatched} unmatched HockeyLive-rader totalt · {hockeyDiag.nonEhlUnmatched} fra ikke-EHL-siden · {hockeyDiag.ehlUnmatched} fra EHL-siden.</p>{hockeyDiag.ehlRows.length>0&&<div className="preseason-table-wrap"><table className="preseason-table"><thead><tr><th>Spiller</th><th>Lag</th><th>Kamp</th><th>Årsak</th></tr></thead><tbody>{hockeyDiag.ehlRows.map((r,i)=><tr key={`${r.game}-${r.rawPlayerName}-${i}`}><td><strong>{r.rawPlayerName}</strong></td><td>{r.rawTeam}</td><td>{r.game}</td><td>{r.reason}</td></tr>)}</tbody></table></div>}</div>}
  </section>}

  <section className="xfp-panel"><div className="xfp-panel-head"><div><p className="eyebrow">KAMPSTATUS</p><h2>Treningskamper</h2></div></div>
   <div className="preseason-table-wrap"><table className="preseason-table"><thead><tr><th>Dato</th><th>Kamp</th><th>Resultat</th><th>Kilde</th><th>Data</th><th>Match</th></tr></thead><tbody>{games.map(g=>{const c=counts.get(g.id)||{rows:0,matched:0};return <tr key={g.id}><td>{dt(g)}</td><td><strong>{g.home_team} – {g.away_team}</strong><small>{g.hockeylive_match_id?`HockeyLive ${g.hockeylive_match_id}`:g.source_url?"Ekstern kilde":"Manuell/venter"}</small></td><td>{g.home_score==null||g.away_score==null?"—":`${g.home_score}–${g.away_score}`}</td><td><span className={`preseason-source ${g.source_type}`}>{g.source_type}</span><small>{Math.round(Number(g.source_quality||0)*100)}%</small></td><td>{c.rows}</td><td>{c.rows?`${c.matched}/${c.rows}`:"—"}</td></tr>})}</tbody></table></div>
  </section>
 </main>;
}
