"use client";
import {useEffect,useMemo,useState} from "react";
import {getSupabaseBrowserClient} from "../../../../lib/supabase";
import "../../fantasy.css";
type H={matchId:string;date:string;opponent:string;side:string;score:string;saves:number;goalsAgainst:number;minutesPlayed:number;win:boolean;shutout:boolean};
type R={id:string;name:string;team:string;position:string;history:H[]};
const NAMES=["Joona Partanen","Mathias Schjerpen Arnkværn","Jere Huhtamaa"];
const nk=(v:string)=>String(v||"").toLocaleLowerCase("nb-NO").normalize("NFD").replace(/[\u0300-\u036f]/g,"").replace(/[^a-z0-9]+/g," ").trim();
const toks=(v:string)=>nk(v).split(/\s+/).filter(Boolean);
function same(a:string,b:string){if(nk(a)===nk(b))return true;const x=toks(a),y=toks(b);return x.length>=2&&y.length>=2&&x[0]===y[0]&&x[x.length-1]===y[y.length-1]}
export default function KeeperContext(){const[keepers,setKeepers]=useState<R[]>([]),[selected,setSelected]=useState(""),[ctx,setCtx]=useState<Record<string,any>>({}),[msg,setMsg]=useState("Laster …");
useEffect(()=>{(async()=>{try{const s=getSupabaseBrowserClient();const{data}=await s!.auth.getSession();const a=data.session?.access_token;if(!a)throw new Error("Du må være logget inn som admin.");const r=await fetch("/api/fantasy-player-form?season=2025%2F26",{headers:{Authorization:`Bearer ${a}`}}),p=await r.json();if(!r.ok||!p.ok)throw new Error(p.error||"Feil");const k=(p.result.rows||[]).filter((x:R)=>x.position==="G"&&NAMES.some(n=>same(x.name,n)));setKeepers(k);setSelected(k.find((x:R)=>same(x.name,"Joona Partanen"))?.id||k[0]?.id||"");setMsg(`${k.length} kontrollkeepere`)}catch(e:any){setMsg(e.message||"Feil")}})()},[]);
const player=keepers.find(k=>k.id===selected);
useEffect(()=>{if(!player)return;(async()=>{const s=getSupabaseBrowserClient();const{data}=await s!.auth.getSession();const a=data.session?.access_token;if(!a)return;const ids=player.history.map(h=>h.matchId).filter(Boolean);const r=await fetch(`/api/fantasy-goalie-game-context?ids=${encodeURIComponent(ids.join(","))}`,{headers:{Authorization:`Bearer ${a}`}}),p=await r.json();if(r.ok&&p.ok)setCtx(p.matches||{})})()},[player?.id]);
const rows=useMemo(()=>{if(!player)return[];return player.history.map(h=>{const c=ctx[h.matchId];const own=(c?.goalies||[]).find((g:any)=>same(g.name,player.name));const mates=(c?.goalies||[]).filter((g:any)=>!same(g.name,player.name));return{h,c,own,mates}}).filter(x=>x.own).sort((a,b)=>String(b.h.date).localeCompare(String(a.h.date)))},[player,ctx]);
return <main className="fantasy-shell"><section className="fantasy-hero"><div><p className="fantasy-kicker">STANG INN · ADMIN · FANTASY</p><h1>Keeper kampkontekst</h1><p className="fantasy-lead">Viser rå HockeyLive-felt, spilletid og andre keepere i samme kamp for å finne riktig W/SO-logikk.</p></div><a className="pill" href="/fantasy/diagnose/keeper-season" style={{textDecoration:"none"}}>← Sesongavstemming</a></section><section className="fantasy-card"><p>{msg}</p><select value={selected} onChange={e=>setSelected(e.target.value)} style={{padding:10,borderRadius:10,minWidth:320}}>{keepers.map(k=><option key={k.id} value={k.id}>{k.name} · {k.team}</option>)}</select>{player&&<><div style={{marginTop:14,padding:12,border:"1px solid #b7d7c4",borderRadius:12,background:"#eefaf2"}}><b>Se spesielt etter:</b> lagseier der <code>rawWins=0</code>, og GA=0 der <code>rawSO=0</code>. Slike rader viser at fallback-logikken vår har laget W/SO selv om HockeyLive ikke gjorde det.</div><div style={{overflowX:"auto",marginTop:14}}><table style={{width:"100%",borderCollapse:"collapse",minWidth:1250,fontSize:12}}><thead><tr>{["Dato","Motstander","Resultat","MIN","SV","GA","Lagret W","rawWins","Lagret SO","rawSO","Andre keepere i kampen","Signal"].map(h=><th key={h} style={{padding:6,textAlign:"left",background:"#eef3f8"}}>{h}</th>)}</tr></thead><tbody>{rows.map((r,i)=>{const fakeW=r.own.storedWin&&Number(r.own.rawWins||0)<=0;const fakeSO=r.own.storedSO&&Number(r.own.rawSO||0)<=0;const signal=[fakeW&&"W fra fallback",fakeSO&&"SO fra GA=0",r.mates.length>0&&"keeperbytte/kontekst"].filter(Boolean).join(" · ")||"—";return <tr key={i} style={{background:fakeW||fakeSO?"#fff4df":"transparent"}}><td style={{padding:6,borderBottom:"1px solid #e2e8f0"}}>{r.h.date?new Date(r.h.date).toLocaleDateString("nb-NO"):"—"}</td><td>{r.h.opponent}</td><td>{r.h.score}</td><td>{r.own.minutes??"—"}</td><td>{r.own.saves}</td><td>{r.own.ga}</td><td>{r.own.storedWin?"✓":"—"}</td><td>{r.own.rawWins??"—"}</td><td>{r.own.storedSO?"✓":"—"}</td><td>{r.own.rawSO??"—"}</td><td>{r.mates.map((m:any)=>`${m.name}: ${m.minutes}m, ${m.saves}SV/${m.ga}GA, Wraw ${m.rawWins??"—"}, SOraw ${m.rawSO??"—"}`).join(" | ")||"—"}</td><td style={{fontWeight:800,color:fakeW||fakeSO?"#a23b2a":"#16794b"}}>{signal}</td></tr>})}</tbody></table></div></>}</section></main>}
