"use client";
import {useEffect,useState} from "react";
import {getSupabaseBrowserClient} from "../../../../lib/supabase";
import "../../fantasy.css";
const SEASON="2026/27",TOURNAMENT="448981";
export default function FantasyRoundAdmin(){const[allowed,setAllowed]=useState<boolean|null>(null),[busy,setBusy]=useState(false),[msg,setMsg]=useState("");
useEffect(()=>{(async()=>{const sb=getSupabaseBrowserClient();if(!sb){setAllowed(false);return}const{data:s}=await sb.auth.getSession();const u=s.session?.user;if(!u){setAllowed(false);return}const{data:p}=await sb.from("players").select("admin").eq("id",u.id).maybeSingle();setAllowed(Boolean(p?.admin))})()},[]);
async function sb(){const c=getSupabaseBrowserClient();if(!c)throw new Error("Supabase mangler");return c}async function token(){const c=await sb();const{data}=await c.auth.getSession();if(!data.session?.access_token)throw new Error("Ikke innlogget");return data.session.access_token}
async function run(label:string,fn:()=>Promise<string>){setBusy(true);setMsg(`${label} …`);try{setMsg(await fn())}catch(e:any){setMsg(`${label} feilet: ${e?.message||e}`)}finally{setBusy(false)}}
const sync=()=>run("Synk",async()=>{const c=await sb(),t=await token();const r=await fetch(`/api/fantasy-season-prepare?season=${encodeURIComponent(SEASON)}&tournamentId=${TOURNAMENT}`,{method:"POST",headers:{Authorization:`Bearer ${t}`}});const j=await r.json();if(!r.ok||!j.ok)throw new Error(j.error||`HTTP ${r.status}`);const{data,error}=await c.rpc("sync_fantasy_calendar_rounds_from_games",{p_season:SEASON});if(error)throw error;const x=Array.isArray(data)?data[0]:data;return `${j.result?.totalMatches||0} kamper · ${x?.rounds_upserted||0} runder · ${x?.games_assigned||0} kamper plassert.`});
const readiness=()=>run("Snapshot-kontroll",async()=>{const c=await sb();const{data,error}=await c.rpc("get_fantasy_snapshot_readiness",{p_season:SEASON});if(error)throw error;const x=Array.isArray(data)?data[0]:data;return `${x?.valid_teams||0}/${x?.total_teams||0} gyldige lag · neste runde ${x?.next_round_no||"—"} · ${x?.snapshots_for_next_round||0} snapshots.`});
const freeze=()=>run("Lagfrysing",async()=>{const c=await sb();const{data,error}=await c.rpc("freeze_due_fantasy_rounds",{p_season:SEASON});if(error)throw error;const x=Array.isArray(data)?data[0]:data;return `${x?.due_rounds||0} forfalte runder · ${x?.snapshots_created||0} nye snapshots · ${x?.errors||0} feil.`});
const createTest=()=>run("Opprett snapshot-test",async()=>{const c=await sb();const{error}=await c.rpc("create_fantasy_snapshot_test_round",{p_season:SEASON});if(error)throw error;return "Test-runde 9999 opprettet."});
const checkTest=()=>run("Kontroller snapshot-test",async()=>{const c=await sb();const{data,error}=await c.rpc("get_fantasy_snapshot_test_state",{p_season:SEASON});if(error)throw error;const x=Array.isArray(data)?data[0]:data;return x?.snapshot_exists?`${x.snapshot_player_count} spillere · spillerstall lik: ${x.same_player_set?"JA":"NEI"} · C: ${x.same_captain?"JA":"NEI"} · VC: ${x.same_vice_captain?"JA":"NEI"}`:"Ingen snapshot ennå."});
const cleanup=()=>run("Rydd snapshot-test",async()=>{const c=await sb();const{data,error}=await c.rpc("cleanup_fantasy_snapshot_test_round",{p_season:SEASON});if(error)throw error;return `${Number(data||0)} testrunde slettet.`});
if(allowed===null)return <main className="fantasy-shell"><p>Sjekker admin …</p></main>;if(!allowed)return <main className="fantasy-shell"><h1>Ingen tilgang</h1></main>;
return <main className="fantasy-shell"><section className="fantasy-hero"><div><p className="fantasy-kicker">ADMIN · FANTASY</p><h1>Rundeverktøy</h1><p className="fantasy-lead">Terminlistesynk, snapshot-kontroll og isolert snapshot-test.</p></div></section><section className="fantasy-card" style={{marginTop:18}}><div style={{display:"flex",gap:10,flexWrap:"wrap"}}><button onClick={sync} disabled={busy}>Synk terminliste/runder</button><button onClick={readiness} disabled={busy}>Kontroller lagfrysing</button><button onClick={freeze} disabled={busy}>Frys forfalte runder</button></div><hr style={{margin:"20px 0",opacity:.2}}/><div style={{display:"flex",gap:10,flexWrap:"wrap"}}><button onClick={createTest} disabled={busy}>1. Opprett test</button><button onClick={checkTest} disabled={busy}>2. Kontroller test</button><button onClick={cleanup} disabled={busy}>3. Rydd test</button></div>{msg&&<p className="card-copy" style={{marginTop:16}}>{msg}</p>}</section></main>}
