"use client";

import {useMemo,useState} from "react";
import {getSupabaseBrowserClient} from "../../../../lib/supabase";
import {HISTORICAL_PRICES_2024} from "../../../../lib/fantasy/historical-prices-2024";
import {HISTORICAL_GOALIE_PRICES_2024} from "../../../../lib/fantasy/historical-goalie-prices-2024";
import {HISTORICAL_PRICES_2025} from "../../../../lib/fantasy/historical-prices-2025";
import {importHistoryFor} from "../../../../lib/fantasy/import-history-2026";
import {returnHistoryFor} from "../../../../lib/fantasy/return-history-2026";
import {importEstimateV46} from "../../../../lib/fantasy/import-pricing-v4-6";
import {talentEstimateV43,TALENT_HISTORY_2026_V43,type TalentHistoryV43,type V43Position} from "../../../../lib/fantasy/import-pricing-v4-3";
import {calibrateMarket,clamp,repricingScore} from "../../../../lib/fantasy/market-calibration";
import "../../fantasy.css";

const S24="2024/25",S25="2025/26",POS=["C","W","D","G"] as const;
const EXTRA_TALENTS:TalentHistoryV43[]=[{name:"Markus Walberg",position:"G",league:"Norway U20",games:33,savePct:0.916,gaa:3.0,sourceNote:"Sparta U20 2025/26; promoted to A-team goalie duo."}];
const norm=(v:any)=>String(v??"").toLocaleLowerCase("nb-NO").normalize("NFD").replace(/[\u0300-\u036f]/g,"").replace(/ø/g,"o").replace(/æ/g,"ae").replace(/[^a-z0-9]+/g," ").trim();
const natural=(s:string)=>{const[last,...r]=String(s||"").split(",");return r.length?`${r.join(",").trim()} ${last.trim()}`:String(s||"")};
const arr=(s:string)=>norm(s).split(" ").filter(Boolean).filter(x=>x!=="jr"&&x!=="junior"),tok=(s:string)=>new Set(arr(s));
function siblingGuard(a:string,b:string){const A=arr(a),B=arr(natural(b));return A.length>=3&&B.length>=3&&A[A.length-1]===B[B.length-1]&&A[A.length-2]===B[B.length-2]&&A[0]!==B[0]}
function score(a:string,b:string){if(norm(a)===norm(natural(b)))return 1000;if(siblingGuard(a,b))return 0;const A=tok(a),B=tok(natural(b));let c=0;for(const x of A)if(B.has(x))c++;const mn=Math.min(A.size,B.size),mx=Math.max(A.size,B.size);if(c===mn&&mn>=2)return 800+c*10-mn*Math.abs(mx-mn);return c>=2?c*100-Math.abs(A.size-B.size)*10:0}
function match(name:string,src:any[],used?:Set<number>){let bi=-1,bs=0;for(let i=0;i<src.length;i++){if(used?.has(i))continue;const s=score(name,src[i][0]);if(s>bs){bs=s;bi=i}}return bi>=0&&bs>=200?{i:bi,row:src[bi],score:bs}:null}
function bestPlayerMatch(name:string,src:any[]){let best:any=null,bs=0;for(const x of src){const sc=score(name,x.name);if(sc>bs){bs=sc;best=x}}return bs>=800?best:null}
function solve(A:number[][],b:number[]){const n=b.length,m=A.map((r,i)=>[...r,b[i]]);for(let i=0;i<n;i++){let p=i;for(let j=i+1;j<n;j++)if(Math.abs(m[j][i])>Math.abs(m[p][i]))p=j;[m[i],m[p]]=[m[p],m[i]];const d=m[i][i]||1e-9;for(let k=i;k<=n;k++)m[i][k]/=d;for(let j=0;j<n;j++)if(j!==i){const f=m[j][i];for(let k=i;k<=n;k++)m[j][k]-=f*m[i][k]}}return m.map(r=>r[n])}
const feat=(r:any)=>[1,r.oldPrice/1e6,Number(r.ppg||0),Math.min(1,Number(r.games||0)/45),(r.oldPrice/1e6)*Math.min(1,Number(r.games||0)/45)];
const featStats=(r:any)=>[1,Number(r.ppg||0),Math.min(1,Number(r.games||0)/45),Number(r.ppg||0)*Math.min(1,Number(r.games||0)/45)];
function fit(rs:any[]){const n=5,A=Array.from({length:n},()=>Array(n).fill(0)),b=Array(n).fill(0);for(const r of rs){const x=feat(r),y=r.newPrice/1e6;for(let j=0;j<n;j++){b[j]+=x[j]*y;for(let k=0;k<n;k++)A[j][k]+=x[j]*x[k]}}for(let i=0;i<n;i++)A[i][i]+=0.4;return solve(A,b)}
function fitStats(rs:any[]){const n=4,A=Array.from({length:n},()=>Array(n).fill(0)),b=Array(n).fill(0);for(const r of rs){const x=featStats(r),y=r.newPrice/1e6;for(let j=0;j<n;j++){b[j]+=x[j]*y;for(let k=0;k<n;k++)A[j][k]+=x[j]*x[k]}}for(let i=0;i<n;i++)A[i][i]+=0.7;return solve(A,b)}
const predict=(c:number[],r:any)=>clamp(feat(r).reduce((s,v,i)=>s+v*c[i],0),1,20),predictStats=(c:number[],r:any)=>clamp(featStats(r).reduce((s,v,i)=>s+v*c[i],0),1,20),statsWeight=(g:any)=>clamp(Number(g||0)/35,0.15,0.9);
function median(v:number[]){const a=[...v].filter(Number.isFinite).sort((x,y)=>x-y);if(!a.length)return 5;const m=Math.floor(a.length/2);return a.length%2?a[m]:(a[m-1]+a[m])/2}
function canonTeam(v:any){const s=norm(v);if(s.includes("storhamar"))return"Storhamar";if(s.includes("stavanger")||s.includes("oilers"))return"Stavanger";if(s.includes("valerenga"))return"Vålerenga";if(s.includes("frisk"))return"Frisk Asker";if(s.includes("sparta"))return"Sparta";if(s.includes("narvik"))return"Narvik";if(s.includes("stjernen"))return"Stjernen";if(s.includes("lillehammer"))return"Lillehammer";if(s.includes("ringerike"))return"Ringerike";if(s.includes("nidaros"))return"Nidaros";return String(v||"").trim()}
async function auth(){const s=getSupabaseBrowserClient(),{data}=await s!.auth.getSession();if(!data.session?.access_token)throw new Error("Logg inn som admin");return data.session.access_token}

export default function Page(){const[busy,setBusy]=useState(false),[msg,setMsg]=useState("Klar for V4.6.1-preview"),[rows,setRows]=useState<any[]>([]),[market,setMarket]=useState<any>(null);
async function run(){setBusy(true);try{const t=await auth(),[a,b,rr]=await Promise.all([fetch(`/api/fantasy-player-form?season=${encodeURIComponent(S24)}`,{headers:{Authorization:`Bearer ${t}`}}),fetch(`/api/fantasy-player-form?season=${encodeURIComponent(S25)}`,{headers:{Authorization:`Bearer ${t}`}}),fetch('/api/fantasy-roster-enriched-2026',{cache:'no-store'})]),p24=await a.json(),p25=await b.json(),roster=await rr.json();if(!a.ok||!p24.ok||!b.ok||!p25.ok||!rr.ok||!roster.ok||!roster.rows?.length)throw new Error("Kunne ikke hente komplett prisgrunnlag");
const oldPlayers=p24.result?.rows||[],curPlayers=p25.result?.rows||[],oldSk=HISTORICAL_PRICES_2024.filter(x=>x[1]!=null),oldG=HISTORICAL_GOALIE_PRICES_2024.filter(x=>x[1]!=null),p25src=HISTORICAL_PRICES_2025.filter(x=>x[2]>0),uS=new Set<number>(),uG=new Set<number>(),uN=new Set<number>(),train:any[]=[];
for(const pl of oldPlayers){const G=String(pl.position).toUpperCase()==="G",mo=match(pl.name,(G?oldG:oldSk) as any[],G?uG:uS),mn=match(pl.name,p25src as any[],uN);if(mo&&mn){(G?uG:uS).add(mo.i);uN.add(mn.i);train.push({...pl,oldPrice:mo.row[1],newPrice:mn.row[2]})}}
const coef:any={},coefStats:any={};for(const z of POS){const sm=train.filter(x=>String(x.position).toUpperCase()===z&&x.games>=3);if(sm.length>=5){coef[z]=fit(sm);coefStats[z]=fitStats(sm)}}const statMap=new Map(curPlayers.map((x:any)=>[norm(x.name),x])),oldStatMap=new Map(oldPlayers.map((x:any)=>[norm(x.name),x])),priceMap=new Map(p25src.map((x:any)=>[norm(natural(x[0])),x]));
const priceByPos:any={C:[],W:[],D:[],G:[]};for(const pl of curPlayers){const pos=String(pl.position||"").toUpperCase();if(!priceByPos[pos])continue;const pr=match(pl.name,p25src as any[]);if(pr)priceByPos[pos].push(Number(pr.row[2])/1e6)}const allMedian=median(p25src.map(x=>Number(x[2])/1e6)),posMedian:any={C:median(priceByPos.C),W:median(priceByPos.W),D:median(priceByPos.D),G:median(priceByPos.G)},talents=new Map([...TALENT_HISTORY_2026_V43,...EXTRA_TALENTS].map(x=>[norm(x.name),x])),raw:any[]=[];
for(const r of roster.rows){const name=String(r.name),team=canonTeam(r.team);let s:any=statMap.get(norm(name))||bestPlayerMatch(name,curPlayers),hist:any=null;if(!s)hist=oldStatMap.get(norm(name))||bestPlayerMatch(name,oldPlayers);let pr:any=priceMap.get(norm(name));if(!pr){const m=match(name,p25src as any[]);if(m&&m.score>=800)pr=m.row}const pos=String(r.position||s?.position||hist?.position||"").toUpperCase() as V43Position,valid=(POS as readonly string[]).includes(pos);let old=pr?Number(pr[2])/1e6:null,rawEst=0,cls="Provisorisk",confidence="Lav",reason="",metric="",source="";
if(valid&&s&&old!=null&&coef[pos]){const base=predict(coef[pos],{...s,oldPrice:old*1e6}),rs=repricingScore({...s,old,position:pos}),blend=0.35+0.65*(rs/100);rawEst=clamp(old+(base-old)*blend,1,20);cls="EHL-modell";confidence="Høy";reason="2025/26-statistikk + 19F-pris";source="EHL 2025/26"}
else if(valid&&s&&old==null&&coefStats[pos]&&Number(s.games||0)>=3){const anchor=Number(posMedian[pos]),model=predictStats(coefStats[pos],s),w=statsWeight(s.games);old=anchor;rawEst=clamp(anchor+(model-anchor)*w,1,20);cls="EHL statsmodell";confidence=Number(s.games||0)>=15?"Middels":"Lav";reason="2025/26-statistikk uten historisk pris";source="EHL 2025/26"}
else if(valid&&hist&&old==null&&coefStats[pos]&&Number(hist.games||0)>=3){const anchor=Number(posMedian[pos]),model=predictStats(coefStats[pos],hist),w=statsWeight(hist.games)*0.75;old=anchor;rawEst=clamp(anchor+(model-anchor)*w,1,20);cls="Returmodell";confidence=Number(hist.games||0)>=20?"Middels":"Lav";reason="2024/25-returhistorikk";source="EHL 2024/25"}
else if(valid){const anchor=Number(posMedian[pos]||allMedian),ih=importHistoryFor(name),tal:any=talents.get(norm(name));if(ih){const est=importEstimateV46(ih,pos,team,name);old=anchor;if(est){rawEst=est.raw;cls=est.note;confidence=est.confidence;metric=est.metric;reason=est.empiricalBasis;source=`${ih.league} · ${est.metric}`}else{rawEst=anchor;reason="Importdata utilstrekkelig";source=ih.league}}
else if(tal){const est=talentEstimateV43(tal);old=anchor;rawEst=est.raw;cls="Talentmodell V4.3.3";confidence=est.confidence;metric=est.metric;reason="Junior guardrail";source=`${tal.league} · ${est.metric}`}
else if(old!=null){rawEst=old;cls="Videreført";reason="Historisk pris";source="19F 2025/26"}
else{const rh=returnHistoryFor(name);old=anchor;if(rh&&Number.isFinite(rh.seniorPoints)&&rh.seniorGames>=15){const ppg=Number(rh.seniorPoints)/rh.seniorGames,expected=pos==="D"?0.28:0.55,scale=pos==="D"?7:8,w=clamp(rh.seniorGames/70,0.35,0.65);rawEst=clamp(anchor+(ppg-expected)*scale*w,1,20);cls="Returmodell";metric=`${ppg.toFixed(2)} P/GP`;reason="EHL-returhistorikk";source="EHL seniorhistorikk"}else{rawEst=anchor;reason="Posisjonsmedian – krever manuell kontroll";source="Fallback"}}}else{old=allMedian;rawEst=allMedian;reason="Mangler gyldig posisjon – BLOKKER";source="Fallback"}
const blocking=!valid||source==="Fallback"||reason==="Importdata utilstrekkelig";const lowConfidence=!blocking&&confidence==="Lav";raw.push({name,team,pos:valid?pos:"—",old:Number(old??allMedian),rawEst,cls,confidence,reason,metric,source,blocking,lowConfidence,review:blocking||lowConfidence});}
const calibrated=calibrateMarket(raw);setRows(calibrated.rows);setMarket(calibrated.stats);const blockers=raw.filter(x=>x.blocking).length,low=raw.filter(x=>x.lowConfidence).length;setMsg(`Ferdig · ${calibrated.rows.length} spillere · ${blockers} reelle kontrollsaker · ${low} lav-konfidens varsler · ingen priser skrevet`)}catch(e:any){setMsg(`Feil: ${e.message||e}`)}finally{setBusy(false)}}
const summary=useMemo(()=>({imports:rows.filter(r=>String(r.cls).includes("V4.6")).length,ehl:rows.filter(r=>String(r.cls).includes("EHL")).length,blocking:rows.filter(r=>r.blocking).length,low:rows.filter(r=>r.lowConfidence).length,missing:rows.filter(r=>r.pos==="—").length}),[rows]);
return <main className="fantasy-page"><section className="fantasy-card"><h1>V4.6.1 · 2026/27 full pris-preview</h1><p>Read-only produksjonskontroll. Eksisterende EHL-spillere routes til EHL-modellen, importer til godkjent V4.6, junior/talent beholder guardrail. Markedskalibrering kjøres til slutt. Ingen priser skrives til databasen.</p><button onClick={run} disabled={busy}>{busy?"Bygger preview…":"Bygg komplett 2026/27 pris-preview"}</button><p><strong>{msg}</strong></p></section>{rows.length>0&&<><section className="fantasy-card"><h2>Routing-kontroll</h2><p><strong>{rows.length}</strong> spillere · EHL-rutet <strong>{summary.ehl}</strong> · V4.6-importer <strong>{summary.imports}</strong> · reelle kontrollsaker <strong>{summary.blocking}</strong> · lav-konfidens varsler <strong>{summary.low}</strong> · mangler posisjon <strong>{summary.missing}</strong></p>{market&&<p>Rå snittpris {market.rawAvg.toFixed(2)}m → markedskalibrert {market.calibratedAvg.toFixed(2)}m · skala {market.scale.toFixed(3)}</p>}</section><section className="fantasy-card"><h2>Spiller-for-spiller</h2><div style={{overflowX:"auto"}}><table><thead><tr><th>Spiller</th><th>Lag</th><th>Pos</th><th>Routing/modell</th><th>Datagrunnlag</th><th>Før kal.</th><th>Preview</th><th>Konfidens</th><th>Årsak / guardrail</th><th>Kontroll</th></tr></thead><tbody>{rows.map(r=><tr key={`${r.team}-${r.name}`}><td><strong>{r.name}</strong></td><td>{r.team}</td><td>{r.pos}</td><td>{r.cls}</td><td>{r.source}</td><td>{r.rawEst.toFixed(1)}m</td><td><strong>{r.est.toFixed(1)}m</strong></td><td>{r.confidence}</td><td>{r.reason}</td><td>{r.blocking?"⛔ Må sjekkes":r.lowConfidence?"⚠ Lav konfidens":"✓"}</td></tr>)}</tbody></table></div></section></>}</main>