"use client";
import {useState} from "react";
import {getSupabaseBrowserClient} from "../../../../lib/supabase";
import "../../fantasy.css";

const CONFIRM="SYNK 2026/27 ROSTER";
async function auth(){const s=getSupabaseBrowserClient(),{data}=await s!.auth.getSession();if(!data.session?.access_token)throw new Error("Logg inn som admin");return data.session.access_token}

export default function Page(){
  const[busy,setBusy]=useState(false),[syncing,setSyncing]=useState(false),[msg,setMsg]=useState("Kjør preflight først"),[pre,setPre]=useState<any>(null),[rows,setRows]=useState<any[]>([]),[confirm,setConfirm]=useState(""),[syncMsg,setSyncMsg]=useState("");
  async function check(){setBusy(true);setSyncMsg("");setConfirm("");try{const t=await auth();const rr=await fetch("/api/fantasy-roster-enriched-2026",{cache:"no-store"}),roster=await rr.json();if(!rr.ok||!roster.ok)throw new Error(roster.error||"Rosterfeil");const current=Array.isArray(roster.rows)?roster.rows:[];const p=await fetch("/api/admin/fantasy/roster-preflight",{method:"POST",headers:{"Content-Type":"application/json",Authorization:`Bearer ${t}`},body:JSON.stringify({rows:current})}),j=await p.json();if(!p.ok||!j.ok)throw new Error(j.error||"Preflight feilet");setRows(current);setPre(j);const joakim=j.details?.ambiguous?.length===1&&j.details.ambiguous[0]?.name==="Joakim Eidsa Arnestad";const expected=current.length===243&&j.missing===43&&j.ambiguous===1&&joakim;setMsg(expected?"Forventet differanse bekreftet. Synk kan låses opp.":"Roster/DB-differansen har endret seg. Ikke synk før ny kontroll.")}catch(e:any){setMsg(`Feil: ${e.message||e}`);setPre(null);setRows([])}finally{setBusy(false)}}
  const joakim=pre?.details?.ambiguous?.length===1&&pre.details.ambiguous[0]?.name==="Joakim Eidsa Arnestad";
  const canSync=rows.length===243&&pre?.missing===43&&pre?.ambiguous===1&&joakim;
  async function sync(){if(!canSync||confirm!==CONFIRM)return;setSyncing(true);setSyncMsg("");try{const t=await auth();const res=await fetch("/api/admin/fantasy/sync-roster",{method:"POST",headers:{"Content-Type":"application/json",Authorization:`Bearer ${t}`},body:JSON.stringify({confirmation:confirm,rows})}),j=await res.json();if(!res.ok||!j.ok)throw new Error(j.error||"Sync feilet");setSyncMsg(`Synk fullført · ${j.result.inserted} nye · ${j.result.updated} oppdatert · duplikat håndtert ${j.result.duplicateFixed}. Kjør roster-preflight på nytt.`);setConfirm("")}catch(e:any){setSyncMsg(`Synk stoppet: ${e.message||e}`)}finally{setSyncing(false)}}
  return <main className="fantasy-page"><section className="fantasy-card"><h1>2026/27 roster → database sync</h1><p>Kontrollert synk. Oppretter manglende HockeyLive-spillere, oppdaterer lag/posisjon/external_id på eksisterende spillere og deaktiverer kun den verifiserte Joakim-duplikaten. De gamle 251 spillerne røres ikke i dette steget.</p><button onClick={check} disabled={busy||syncing}>{busy?"Kontrollerer…":"Kjør preflight før synk"}</button><p><strong>{msg}</strong></p></section>{pre&&<><section className="fantasy-card"><h2>Gate</h2><p>Roster <strong>{rows.length}</strong> · match <strong>{pre.matched}</strong> · mangler <strong>{pre.missing}</strong> · tvetydige <strong>{pre.ambiguous}</strong> · lagavvik <strong>{pre.teamMismatch}</strong>.</p>{canSync?<p><strong>✓ Differansen matcher den validerte kontrollen: 243 roster, 43 nye og kun Joakim som duplikat.</strong></p>:<p><strong>⛔ Synk blokkert fordi differansen ikke lenger matcher kontrollen.</strong></p>}</section>{canSync&&<section className="fantasy-card"><h2>Utfør atomisk synk</h2><p>Beholder Joakim-ID <code>e9647e74-9745-450d-a27a-3cc5852026ed</code> og deaktiverer <code>99c086a2-3742-4478-9a6c-ad7425c50605</code>. Historiske rader slettes ikke.</p><label htmlFor="sync-confirm"><strong>Skriv {CONFIRM}:</strong></label><br/><input id="sync-confirm" value={confirm} onChange={e=>setConfirm(e.target.value)} disabled={syncing} style={{marginTop:8,marginRight:8,minWidth:260}}/><button onClick={sync} disabled={syncing||confirm!==CONFIRM}>{syncing?"Synkroniserer…":"Synk 243 spillere"}</button>{syncMsg&&<p><strong>{syncMsg}</strong></p>}</section>}</>}</main>
}
