"use client";
import {useEffect,useMemo,useState} from "react";
import {getSupabaseBrowserClient} from "../../../../lib/supabase";
import {calculate19FantasyPoints} from "../../../../lib/fantasy/scoring";
import "../../fantasy.css";

type H={matchId:string;date:string;opponent:string;side:string;score:string;saves:number;goalsAgainst:number;minutesPlayed:number;win:boolean;shutout:boolean};
type R={id:string;name:string;team:string;position:string;history:H[]};
type GoalInfo={teamName:string;homeOrAwayTeam:string;emptyNet:boolean;goalType:string};
const FASIT:Record<string,number>={"joona partanen":315,"alexander johansson":267,"marcus stensrud":388,"jere huhtamaa":297,"mathias schjerpen arnkværn":321};
const nk=(v:string)=>String(v||"").toLocaleLowerCase("nb-NO").normalize("NFD").replace(/[\u0300-\u036f]/g,"").replace(/[^a-z0-9]+/g," ").trim();
const toks=(v:string)=>nk(v).split(/\s+/).filter(Boolean);
const r1=(v:number)=>Math.round(v*10)/10;
function fasit(name:string){const n=nk(name);if(FASIT[n]!=null)return FASIT[n];const t=toks(name);if(t.length<2)return undefined;const first=t[0],last=t[t.length-1];const matches=Object.entries(FASIT).filter(([k])=>{const q=toks(k);return q.length>=2&&q[0]===first&&q[q.length-1]===last});return matches.length===1?matches[0][1]:undefined}
function teamGA(h:H){const p=String(h.score||"").split(/[–-]/).map(x=>Number(x.trim()));if(p.length!==2||p.some(Number.isNaN))return null;return h.side==="H"?p[1]:h.side==="B"?p[0]:null}
function enAgainst(h:H,goals:GoalInfo[]){const opp=nk(h.opponent);return goals.filter(g=>g.emptyNet&&(nk(g.teamName)===opp||(h.side==="H"&&g.homeOrAwayTeam==="B")||(h.side==="B"&&g.homeOrAwayTeam==="H"))).length}
function calc(h:H,ga:number,win:boolean,so:boolean){return calculate19FantasyPoints({position:"G",didPlay:true,minutesPlayed:h.minutesPlayed,saves:h.saves,goalsAgainst:ga,win,shutout:so})}
export default function KeeperAB(){
 const[keepers,setKeepers]=useState<R[]>([]),[selected,setSelected]=useState(""),[goalMap,setGoalMap]=useState<Record<string,GoalInfo[]>>({}),[msg,setMsg]=useState("Laster …");
 useEffect(()=>{(async()=>{try{const s=getSupabaseBrowserClient();const{data}=await s!.auth.getSession();const a=data.session?.access_token;if(!a)throw new Error("Du må være logget inn som admin.");const res=await fetch("/api/fantasy-player-form?season=2025%2F26",{headers:{Authorization:`Bearer ${a}`}}),p=await res.json();if(!res.ok||!p.ok)throw new Error(p.error||"Kunne ikke hente data");const k=(p.result.rows||[]).filter((r:R)=>r.position==="G"&&fasit(r.name)!=null);setKeepers(k);setSelected(k.find((r:R)=>{const t=toks(r.name);return t[0]==="joona"&&t[t.length-1]==="partanen"})?.id||k[0]?.id||"");setMsg(`${k.length} kontrollkeepere`) }catch(e:any){setMsg(e.message||"Feil")}})()},[]);
 const player=keepers.find(k=>k.id===selected);
 useEffect(()=>{if(!player)return;(async()=>{const s=getSupabaseBrowserClient();const{data}=await s!.auth.getSession();const a=data.session?.access_token;if(!a)return;const ids=player.history.map(h=>h.matchId).filter(Boolean);const res=await fetch(`/api/fantasy-empty-net?ids=${encodeURIComponent(ids.join(","))}`,{headers:{Authorization:`Bearer ${a}`}});const p=await res.json();if(res.ok&&p.ok)setGoalMap(p.matches||{})})()},[player?.id]);
 const test=useMemo(()=>{if(!player)return null;let base=0,en=0,strict=0,enStrict=0;const games=player.history.map(h=>{const tg=teamGA(h),empty=enAgainst(h,goalMap[h.matchId]||[]);const b=calc(h,h.goalsAgainst,h.win,h.shutout);const e=calc(h,h.goalsAgainst+empty,h.win,h.shutout);const accounted=tg==null?true:Math.max(0,tg-h.goalsAgainst)<=empty;const strictWin=h.win&&accounted;const strictSO=h.shutout&&tg===0&&h.goalsAgainst===0;const st=calc(h,h.goalsAgainst,strictWin,strictSO);const es=calc(h,h.goalsAgainst+empty,strictWin,strictSO);base+=b.total;en+=e.total;strict+=st.total;enStrict+=es.total;return{h,tg,empty,accounted,b,e,st,es,strictWin}});return{base,en,strict,enStrict,games}},[player,goalMap]);
 const target=player?fasit(player.name):undefined;const variants=test&&target!=null?[{name:"A · Nåværende modell",v:test.base,note:"Keeper GA + lagseier slik vi gjør nå"},{name:"B · Empty net som keeper-GA",v:test.en,note:"Legger EN-mål til keeperens GA"},{name:"C · Streng seier/shutout",v:test.strict,note:"Gir W/SO bare når keeperens GA forklarer lagets baklengs"},{name:"D · EN + streng W/SO",v:test.enStrict,note:"Kombinerer B og C"}].map(x=>({...x,d:r1(x.v-target)})).sort((a,b)=>Math.abs(a.d)-Math.abs(b.d)):[];
 return <main className="fantasy-shell"><section className="fantasy-hero"><div><p className="fantasy-kicker">STANG INN · ADMIN · FANTASY</p><h1>Keeper A/B-diagnose</h1><p className="fantasy-lead">Tester keeperreglene mot 19Fantasy uten å endre poengmotoren.</p></div><a className="pill" href="/fantasy/diagnose" style={{textDecoration:"none"}}>← FP-diagnose</a></section><section className="fantasy-card"><p>{msg}</p><select value={selected} onChange={e=>setSelected(e.target.value)} style={{padding:10,borderRadius:10,minWidth:300}}>{keepers.map(k=><option key={k.id} value={k.id}>{k.name} · {k.team}</option>)}</select>{player&&test&&target!=null&&<><div style={{marginTop:14,padding:14,border:"1px solid #cbd8e5",borderRadius:12,background:"white"}}><h2 style={{margin:"0 0 8px"}}>{player.name}</h2><b>19Fantasy-fasit: {target} FP</b><p style={{marginBottom:0,color:"#607086"}}>Beste hypotese står øverst. Ingen av disse endrer produksjonspoengene.</p></div><div style={{marginTop:14,overflowX:"auto"}}><table style={{width:"100%",borderCollapse:"collapse",minWidth:720}}><thead><tr>{["Test","Beregnet FP","Avvik","Forklaring"].map(h=><th key={h} style={{padding:8,textAlign:"left",background:"#eef3f8"}}>{h}</th>)}</tr></thead><tbody>{variants.map((x,i)=><tr key={x.name} style={{background:i===0?"#eaf8ef":"transparent"}}><td style={{padding:8,borderBottom:"1px solid #e2e8f0",fontWeight:800}}>{x.name}{i===0?" ★":""}</td><td style={{padding:8,borderBottom:"1px solid #e2e8f0"}}>{r1(x.v)}</td><td style={{padding:8,borderBottom:"1px solid #e2e8f0",fontWeight:800,color:Math.abs(x.d)<.001?"#16794b":"#a23b2a"}}>{x.d>0?"+":""}{x.d}</td><td style={{padding:8,borderBottom:"1px solid #e2e8f0"}}>{x.note}</td></tr>)}</tbody></table></div><h3>Kampene som kan påvirke keeperreglene</h3><div style={{overflowX:"auto"}}><table style={{width:"100%",borderCollapse:"collapse",minWidth:1050,fontSize:12}}><thead><tr>{["Dato","Motstander","Resultat","SV","Keeper GA","Lag GA","EN","Lag-W","Streng W","A FP","B FP","C FP","D FP"].map(h=><th key={h} style={{padding:6,textAlign:"left",background:"#eef3f8"}}>{h}</th>)}</tr></thead><tbody>{test.games.filter(g=>g.empty>0||!g.accounted||g.h.win).map((g,i)=><tr key={i} style={{background:g.empty>0||!g.accounted?"#fff4df":"transparent"}}>{[g.h.date?new Date(g.h.date).toLocaleDateString("nb-NO"):"—",g.h.opponent,g.h.score,g.h.saves,g.h.goalsAgainst,g.tg??"—",g.empty,g.h.win?"✓":"—",g.strictWin?"✓":"—",r1(g.b.total),r1(g.e.total),r1(g.st.total),r1(g.es.total)].map((v,j)=><td key={j} style={{padding:6,borderBottom:"1px solid #e2e8f0"}}>{v}</td>)}</tr>)}</tbody></table></div></>}</section></main>}
